### ISSUE TITLE
ms-upgrade-conf

### ISSUE THREAD

**Issue by jcbenton** [MailScanner/v5#1]
This throws a warning/error:

Substitution pattern not terminated at -e line 1

I am pretty sure it is doing it because part of the pattern it is searching for is empty.

**Comment by shawniverson** [comment]
Haven't seen this message in a while, and it is not manifesting during current runs of ms-upgrade-conf during my tests...

**Comment by shawniverson** [comment]
Appears long since resolved, closing for now.
