### ISSUE TITLE
Mails considered larger than they are

### ISSUE THREAD

**Issue by DanielMalmgren** [MailScanner/v5#107]
I recently started getting quite much spam through in to my mailboxes. When I started looking closer it turns out many of those spam messages aren't being checked at all, I found lines like this in my log:

> Oct  4 07:20:20 cube MailScanner[5367]: Message 16FAB40011.A7A61 from 217.12.202.119 (akqitvm@sobainon.eu) to <mydomain_removed> is too big for spam checks (934815 > 200000 bytes)

The particular message in this error message is a very small one, 4679 bytes (after MailScanner headers being added), so somehow MailScanner seems to misjudge the size. Don't really know where to search next...

Attaching the full message after removal of sensitive information.

[spam.txt](https://github.com/MailScanner/v5/files/1354713/spam.txt)

**Comment by DanielMalmgren** [comment]
Sorry, forgot to mention. I'm running 5.0.3-7 on Debian 8.9. I know it's starting to get old but I don't see anything in the changelog that seems to have with this problem to do...

**Comment by shawniverson** [comment]
What is the size of the message (the file that contains it) on the filesystem?  Should be located in /var/spool/MailScanner/quarantine/  by date and ID.

**Comment by DanielMalmgren** [comment]
The size I mentioned in my initial comment (4679 bytes) IS the size of the file in /var/spool...

**Comment by msapiro** [comment]
Your log looks like Postfix. Following the entry
```
Oct 4 07:20:20 cube MailScanner[5367]: Message 16FAB40011.A7A61 from 217.12.202.119 (akqitvm@sobainon.eu) to <mydomain_removed> is too big for spam checks (934815 > 200000 bytes)
```
you should see messages like:
```
Oct 4 07:20:ss cube MailScanner[5367]: Requeue: 16FAB40011.A7A61 to xxxxxxxxxx
Oct 4 07:20:ss cube postfix/qmgr[pppp]: xxxxxxxxxx: from=<akqitvm@sobainon.eu>, size=dddddd, nrcpt=1 (queue active)
```
What is the size in the  postfix/qmgr message? If it is close to 934815, are there other queue ID xxxxxxxxxx messages that give a clue as to what may have removed something from the message?

**Comment by DanielMalmgren** [comment]
Not that I can find. I might as well include the relevant part of mail.log (just replaced my domain name):

`Oct  4 07:19:09 cube postfix/smtpd[7168]: connect from mail.sobainon.eu[217.12.202.119]
Oct  4 07:19:10 cube policyd-spf[7189]: None; identity=helo; client-ip=217.12.202.119; helo=mail.sobainon.eu; envelope-from=akqitvm@sobainon.eu; receiver=daniel@<mydomain>
Oct  4 07:19:10 cube policyd-spf[7189]: Pass; identity=mailfrom; client-ip=217.12.202.119; helo=mail.sobainon.eu; envelope-from=akqitvm@sobainon.eu; receiver=daniel@<mydomain>
Oct  4 07:19:10 cube postfix/smtpd[7168]: 16FAB40011: client=mail.sobainon.eu[217.12.202.119]
Oct  4 07:19:10 cube postfix/cleanup[7190]: 16FAB40011: hold: header Received: from mail.sobainon.eu (mail.sobainon.eu [217.12.202.119])??by cube.<mydomain> (Postfix) with ESMTP id 16FAB40011??for <daniel@<mydomain>>; Wed,  4 Oct 2017 07:19:09 +0200 (CEST) from mail.sobainon.eu[217.12.202.119]; from=<akqitvm@sobainon.eu> to=<daniel@<mydomain>> proto=ESMTP helo=<mail.sobainon.eu>
Oct  4 07:19:10 cube postfix/cleanup[7190]: 16FAB40011: message-id=<akqitvm08814317.25454611@mail.sobainon.eu>
Oct  4 07:19:11 cube postfix/smtpd[7168]: disconnect from mail.sobainon.eu[217.12.202.119]
Oct  4 07:19:14 cube MailScanner[5367]: New Batch: Scanning 1 messages, 934815 bytes
Oct  4 07:19:15 cube MailScanner[5367]: Virus and Content Scanning: Starting
Oct  4 07:20:20 cube MailScanner[5367]: Expired 2 records from the SpamAssassin cache
Oct  4 07:20:20 cube MailScanner[5367]: Whitelist refresh time reached
Oct  4 07:20:20 cube MailScanner[5367]: Starting up SQL Whitelist
Oct  4 07:20:20 cube MailScanner[5367]: Read 19 whitelist entries
Oct  4 07:20:20 cube MailScanner[5367]: Blacklist refresh time reached
Oct  4 07:20:20 cube MailScanner[5367]: Starting up SQL Blacklist
Oct  4 07:20:20 cube MailScanner[5367]: Read 36 blacklist entries
Oct  4 07:20:20 cube MailScanner[5367]: Message 16FAB40011.A7A61 from 217.12.202.119 (akqitvm@sobainon.eu) to <mydomain> is too big for spam checks (934815 > 200000 bytes)
Oct  4 07:20:21 cube MailScanner[5367]: Requeue: 16FAB40011.A7A61 to B20E9401BC
Oct  4 07:20:21 cube MailScanner[5367]: Uninfected: Delivered 1 messages
Oct  4 07:20:21 cube postfix/qmgr[5806]: B20E9401BC: from=<akqitvm@sobainon.eu>, size=934143, nrcpt=1 (queue active)
Oct  4 07:20:21 cube MailScanner[5367]: Deleted 1 messages from processing-database
Oct  4 07:20:21 cube MailScanner[5367]: Logging message 16FAB40011.A7A61 to SQL
Oct  4 07:20:22 cube dovecot: lmtp(7237): Connect from local
Oct  4 07:20:22 cube dovecot: lmtp(malmgren): MJk7CpZv1FlFHAAAs8rsrw: sieve: msgid=<akqitvm08814317.25454611@mail.sobainon.eu>: stored mail into mailbox 'INBOX'
Oct  4 07:20:22 cube postfix/lmtp[7236]: B20E9401BC: to=<malmgren@<mydomain>>, orig_to=<daniel@<mydomain>>, relay=cube.<mydomain>[private/dovecot-lmtp], delay=73, delays=73/0.12/0.21/0.31, dsn=2.0.0, status=sent (250 2.0.0 <malmgren@<mydomain>> MJk7CpZv1FlFHAAAs8rsrw Saved)
Oct  4 07:20:22 cube dovecot: lmtp(7237): Disconnect from local: Successful quit
Oct  4 07:20:22 cube postfix/qmgr[5806]: B20E9401BC: removed
Oct  4 07:20:28 cube postfix/smtpd[7168]: connect from localhost[127.0.0.1]
Oct  4 07:20:28 cube postfix/smtpd[7168]: disconnect from localhost[127.0.0.1]
`

**Comment by msapiro** [comment]
The message is still 934143 bytes after MailScanner per
```
Oct  4 07:20:21 cube postfix/qmgr[5806]: B20E9401BC: from=<akqitvm@sobainon.eu>, size=934143, nrcpt=1 (queue active)
```
I suspect the issue is sieve removed a message part.
```
Oct  4 07:20:22 cube dovecot: lmtp(malmgren): MJk7CpZv1FlFHAAAs8rsrw: sieve: msgid=<akqitvm08814317.25454611@mail.sobainon.eu>: stored mail into mailbox 'INBOX'
```

**Comment by DanielMalmgren** [comment]
It shouldn't do... The only thing I do with sieve is moving messages to specific folders, like this:

```
if header :contains "to" "daniel" {
        fileinto "Daniel";
}
```

Any way of knowing for sure if it's sieve making something strange?

I'm on dovecot 2.2.27.

**Comment by msapiro** [comment]
I don't know for sure. What I can see from the logs is MailScanner finishes processing the message and requeues it as `B20E9401BC` and when Postfix picks up the requeued message, it's still 934143 bytes. After that, it is passed via lmtp to dovecot which delivers it via sieve. If it is significantly smaller than that upon delivery to `INBOX`, I think it must be something in the dovecot delivery chain that's filtering something out.

I do see that the message in https://github.com/MailScanner/v5/files/1354713/spam.txt is not the one that these log messages are about. Its `Message-ID: <2ab184a164adcf913355de0fa3dadc1d@cheepisps.com>`and MailScanner queue ID `3A6E540005.A4200` are different and it's time stamps are around `04 Oct 2017 02:22:39 +0200`.

**Comment by DanielMalmgren** [comment]
Oh, you're right. Clearly a mixup from my part. Found the correct place in mail.log:

```
Oct  4 02:21:18 cube postfix/smtpd[30209]: connect from vpshost211.cheepisps.com[167.160.165.211]
Oct  4 02:21:20 cube policyd-spf[30242]: None; identity=helo; client-ip=167.160.165.211; helo=vpshost211.cheepisps.com; envelope-from=return@cheepisps.com; receiver=daniel@<mydomain>
Oct  4 02:21:21 cube policyd-spf[30242]: Pass; identity=mailfrom; client-ip=167.160.165.211; helo=vpshost211.cheepisps.com; envelope-from=return@cheepisps.com; receiver=daniel@<mydomain>
Oct  4 02:21:21 cube postfix/smtpd[30209]: 3A6E540005: client=vpshost211.cheepisps.com[167.160.165.211]
Oct  4 02:21:21 cube postfix/cleanup[30244]: 3A6E540005: hold: header Received: from vpshost211.cheepisps.com (vpshost211.cheepisps.com [167.160.165.211])??by cube.<mydomain> (Postfix) with ESMTPS id 3A6E540005??for <daniel@<mydomain>>; Wed,  4 Oct 2017 02:21:19 +0200 from vpshost211.cheepisps.com[167.160.165.211]; from=<return@cheepisps.com> to=<daniel@<mydomain>> proto=ESMTP helo=<vpshost211.cheepisps.com>
Oct  4 02:21:21 cube postfix/cleanup[30244]: 3A6E540005: message-id=<2ab184a164adcf913355de0fa3dadc1d@cheepisps.com>
Oct  4 02:21:21 cube postfix/smtpd[30209]: disconnect from vpshost211.cheepisps.com[167.160.165.211]
Oct  4 02:21:30 cube MailScanner[29320]: New Batch: Scanning 1 messages, 4878 bytes
Oct  4 02:21:30 cube MailScanner[29320]: Virus and Content Scanning: Starting
Oct  4 02:22:34 cube MailScanner[29320]: Whitelist refresh time reached
Oct  4 02:22:34 cube MailScanner[29320]: Starting up SQL Whitelist
Oct  4 02:22:34 cube MailScanner[29320]: Read 19 whitelist entries
Oct  4 02:22:34 cube MailScanner[29320]: Blacklist refresh time reached
Oct  4 02:22:34 cube MailScanner[29320]: Starting up SQL Blacklist
Oct  4 02:22:34 cube MailScanner[29320]: Read 36 blacklist entries
Oct  4 02:22:38 cube MailScanner[30368]: Found phishing fraud from http://cheepisps.com/B5qiL30401511/C5s04060_JKZt5179.g85XH.html claiming to be www.viablehealth.net in 3A6E540005.A4200
Oct  4 02:22:38 cube MailScanner[29320]: Content Checks: Detected and have disarmed phishing tags in HTML message in 3A6E540005.A4200 from return@cheepisps.com
Oct  4 02:22:39 cube MailScanner[29320]: Requeue: 3A6E540005.A4200 to E0FD240011
Oct  4 02:22:39 cube MailScanner[29320]: Uninfected: Delivered 1 messages
Oct  4 02:22:39 cube postfix/qmgr[5806]: E0FD240011: from=<return@cheepisps.com>, size=4124, nrcpt=1 (queue active)
Oct  4 02:22:39 cube MailScanner[29320]: Deleted 1 messages from processing-database
Oct  4 02:22:39 cube MailScanner[29320]: Logging message 3A6E540005.A4200 to SQL
Oct  4 02:22:39 cube MailScanner[29329]: 3A6E540005.A4200: Logged to MailWatch SQL
Oct  4 02:22:39 cube dovecot: lmtp(30372): Connect from local
Oct  4 02:22:39 cube dovecot: lmtp(malmgren): MHGmHM8p1FmkdgAAs8rsrw: sieve: msgid=<2ab184a164adcf913355de0fa3dadc1d@cheepisps.com>: stored mail into mailbox 'Daniel'
Oct  4 02:22:39 cube postfix/lmtp[30371]: E0FD240011: to=<malmgren@<mydomain>>, orig_to=<daniel@<mydomain>>, relay=cube.<mydomain>[private/dovecot-lmtp], delay=80, delays=80/0.11/0.12/0.17, dsn=2.0.0, status=sent (250 2.0.0 <malmgren@<mydomain>> MHGmHM8p1FmkdgAAs8rsrw Saved)
Oct  4 02:22:39 cube dovecot: lmtp(30372): Disconnect from local: Successful quit
Oct  4 02:22:39 cube postfix/qmgr[5806]: E0FD240011: removed
```

Since a few weeks have passed I'm not sure about what happened here and the original messages have been deleted. I know something was wrong though. I'll see if I can find a more recent example and post back...

**Comment by shawniverson** [comment]
Thanks @DanielMalmgren.  We'll keep this open for a while to give you time to reproduce the issue.

**Comment by msapiro** [comment]
Just to note, both the log messages in the above [comment](https://github.com/MailScanner/v5/issues/107#issuecomment-338421042) and [the message itself](https://github.com/MailScanner/v5/files/1354713/spam.txt) show that that particular message was spam scanned by MailScanner.

**Comment by DanielMalmgren** [comment]
Ok, got another bunch of those today and it turns out I must have been mixing messages up. The bastards really _are_ sending huge spam messages. Guess my only option is to raise the "Max Spam Check Size". So I'll close this issue, sorry for wasting your time...
