### ISSUE TITLE
MailScanner marks Office 365 safe links as possible fraud attempts

### ISSUE THREAD

**Issue by vansieleghemstijn** [MailScanner/v5#108]
Office 365's safe link feature rewrites URLs as x.safelinks.protection.outlook.com?url=... where x is an area reference. (e.g. emea01)

Unfortunately MailScanner marks these links as possible fraud attempts. 

Would it be possible to whitelist these URLs? 

See: 
https://support.office.com/en-us/article/ATP-safe-links-in-Office-365-dd6a1fef-ec4a-4cf4-a25a-bb591c5811e3

**Comment by shawniverson** [comment]
The current implementation of MailScanner does not do this.  However, we can look into it for a future release.  This also is not any real rfc standard that I am aware of at this point.  Please correct me if I am mistaken.

**Comment by Skywalker-11** [comment]
Maybe it can be impletmented in a ways so that we can have black and white list for domains or urls?

**Comment by shawniverson** [comment]
@Skywalker-11 It would be nice if we could do this.  I'll mark this for enhancement.

**Comment by shawniverson** [comment]
@vansieleghemstijn can you provide me a sample of a full safe link that I can use?

**Comment by Skywalker-11** [comment]
An example is here: https://answers.microsoft.com/en-us/outlook_com/forum/oemail-osend/how-to-turn-off-atp-safe-links-please-help/48ab78ad-de36-4001-94a4-05bec2a576fd

**Comment by shawniverson** [comment]
Is it possible to just add *.safelinks.protection.outlook.com to the phishing safe sites list?

**Comment by stefaweb** [comment]
Hi @shawniverson!

I tried "*.safelinks.protection.outlook.com" in /etc/MailScanner/phishing.safe.sites.custom. 

Don't work.

Sample from a message sent by Microsoft staff.

![capture d ecran 2018-03-07 a 09 32 23](https://user-images.githubusercontent.com/12907102/37081693-8bff69ba-21ea-11e8-93d2-d7cc008f6eaf.png)

**Comment by shawniverson** [comment]
@stefaweb Did you run this script after adding it to the file and restart MailScanner?

`ms-update-phishing`

**Comment by stefaweb** [comment]
Yes

**Comment by shawniverson** [comment]
@stefaweb Ok, thanks.  I will continue work on this issue.

**Comment by shawniverson** [comment]
@stefaweb Found a bug and squashed it!

This should work now.  I am preparing a 5.0.7-4 release that will include the fix for this problem.  Basically, wildcards were being ignored in the phishing lists, which turns out not to be a good thing since the whitelist is full of them by default.
