### ISSUE TITLE
Local part and domain part not correctly split

### ISSUE THREAD

**Issue by Skywalker-11** [MailScanner/v5#109]
MailScanner does not seem to correctly split domain parts from local parts of mail addresses.

Eg if sender is `"test@domain1"@example.com` MailScanner returns `domain1@example.com` for `$msg->{fromdomain}`. It should only be `example.com` as that is the domain part and `"test@domain1"` is the local part of the address.

Section 3.2.3 of [rfc 5322](https://tools.ietf.org/html/rfc5322) says a `quoted-string` can contain a `@` if it is surrounded by `"..."` and a mail address can consist of `local-part "@" domain` (`local-part` can be a `quoted-string` see chapter 3.4.1)

**Comment by Skywalker-11** [comment]
Problem is probably here: [common/usr/share/MailScanner/perl/MailScanner/Message.pm#L480](https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Message.pm#L480)

**Comment by msapiro** [comment]
I agree that https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Message.pm#L480 is wrong.
```
    $domain =~ s/^[^@]*@//;
```
should be
```
    $domain =~ s/^.*@//;
```
to strip everything through the `last`@, not the `first`.
