### ISSUE TITLE
init.d file missing from v5.0.6-5 deb

### ISSUE THREAD

**Issue by stefaweb** [MailScanner/v5#114]
Hello!

Don't know if this problem have still be found.

This is on Debian Jessy.

I upgraded one of my server from MailScanner-5.0.6-4 to MailScanner-5.0.6-5 (from https://www.mailscanner.info/downloads/).

At the end, the symbolic link was missing  : 

/etc/init.d/mailscanner -> /usr/lib/MailScanner/init/ms-init

Have to manually create it.

**Comment by msapiro** [comment]
On systems that support systemd, the latest MailScanner no longer uses an init script. It uses a systemd script. It should install /lib/systemd/system/mailscanner.service and a symlink to that from /etc/systemd/system/multi-user.target.wants/mailscanner.service.

**Comment by stefaweb** [comment]
Ok, thanks.
