### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by vkbaker53** [MailScanner/v5#116]
The newest version of MailScanner seems to restart a child process with each message received and processed.  FYI ... running MS under a RHEL7 O/S.

Is this normal behavior?  If so, if seems to fill the maillog excessively.

Thoughts?

**Comment by shawniverson** [comment]
Fresh install, or upgrade?

**Comment by vkbaker53** [comment]
Upgrade

**Comment by shawniverson** [comment]
Restart after upgrade, just in case something odd lurking in memory?

**Comment by vkbaker53** [comment]
Fresh install

**Comment by vkbaker53** [comment]
Did restart machine.  I don't recall seeing the config read messages, after every message processing event, in prior versions.

**Comment by shawniverson** [comment]
@vkbaker53 Do you have a log snippet you could share?

**Comment by vkbaker53** [comment]
Sorry, I do not.  Due to several issues (only a few with MailScanner v5) I had to revert to an earlier version.

**Comment by shawniverson** [comment]
I will run a compare against an old MailScanner install and try to reproduce this...

**Comment by msapiro** [comment]
FWIW, I'm running MailScanner-5.0.6-5 installed as an upgrade and I don't see this behavior.

**Comment by vkbaker53** [comment]
That is encouraging news.

 

The background story may be helpful.  I’m one of the earliest adopters of MailScanner.  Accordingly, I have several implementations that will require attention over the next two years (all installed on RHEL6).  The need for hardware replacement is the primary driver.

 

My most basic implementation consists of MailScanner, MailWatch, Spamassassin, Vipul’s Razor, Clamav and Sophos.  I add a few proprietary content inspection tools for unique environments.

 

As I evaluate MailScanner V5, I find no significant issues.  However, the complete assembly of addins is problematic due to Perl module changes since RHEL6.  I suspect some of the MailScanner V5 issues I’ve observed are influenced by the addins that haven’t compiled as intended.

 

In any respect, my objective is to build a functional RHEL7 image inclusive of MailScanner/MailWatch and various addins.  My intent is to deploy the new image, as a VM, when it becomes necessary to replace aging hardware supporting MailScanner 4.84.6-1.

 

I’m willing to collaborate on the effort and provide some resources as required.

**Comment by shawniverson** [comment]
@vkbaker53 efa-project.org is working on a CentOS 7 build here:  https://github.com/E-F-A/v4
