### ISSUE TITLE
systemd error message

### ISSUE THREAD

**Issue by stefaweb** [MailScanner/v5#122]
Hello!

May be a problem with systemd.

I found this in syslog.

`[    1.805576] systemd[1]: Configuration file /lib/systemd/system/mailscanner.service is marked executable. Please remove executable permission bits. Proceeding anyway.`

I don't know if this is important.

With Debian Jessie (on KVM) + mailscanner 5.0.6-5.

**Comment by shawniverson** [comment]
Looks like ms-systemd (what mailscanner.service is copied from) has 0644 in the build.

What is your umask on your system out of curiosity?

**Comment by shawniverson** [comment]
I also suspect that ms-systemd may have been 0755 in older builds and was corrected at one point, but that won't show in the commits.  In that case simply chmod -x /lib/systemd/system/mailscanner.service will take care of it.

**Comment by shawniverson** [comment]
I think i will chmod the file during debian install as well.

**Comment by stefaweb** [comment]
Here it goes.

`-rwxr-xr-x 1 root root 450 nov.   4 11:23 /lib/systemd/system/mailscanner.service
`

(same on prod and dev)
