### ISSUE TITLE
MailScanner spam score

### ISSUE THREAD

**Issue by janarzz** [MailScanner/v5#124]
Hey,
i have problem with spam score.
When message spam score is 5, then MailScanner show this message has spam, but this message coming out with {Spam?} note.
I want spam score wich begins score 5 would not able to mailbox.
Help

**Comment by msapiro** [comment]
Ste `High Spam Score` to 5 in your MailScanner configoration or set `Spam Actions` to not include deliver.
See https://www.mailscanner.info/MailScanner.conf.index.html#High%20SpamAssassin%20Score and https://www.mailscanner.info/MailScanner.conf.index.html#Spam%20Actions
