### ISSUE TITLE
Disable SpamLists (RBL) checks for authenticated users ? maybe a feature request :)

### ISSUE THREAD

**Issue by worgenrage** [MailScanner/v5#128]
Hey there! Just a quick review from MS list:
http://lists.mailscanner.info/pipermail/mailscanner/2015-September/102606.html

^^ I got the same problem with a new setup.

Is there any way to implement some feature for these checks in MailScanner? Or i'm forced to do that with the MTA (postfix) config ?

For now, if i try to send an email from my home, then i got a ? spam ? score, because my ISP dynamic hsot is listed at Barracuda or SPAMHAUS ZEN lists. (or even my mobile phone* network).

This is a little bit annoying because this is a perfect setup with all what need nowadays, only TLS auths, no openrelay, SPF / DKIM / DMARC setup perfectly.

Any ideas for this problem?

I don't want to disable spamlists scan at MailScanner side (because of MailWatch & statistics) and move to postfix side checks. Postfix can handle it many ways, recipients, clients, etc. I just want to use MailScanner's RBL checking. But now, i can't because if i'm at "home" my emails gets spam* flag by my own MailScanner :) 

ps.: Sorry for my english. And sorry if this issue was already discussed.

Regards
Christian Hamar
-krix-

**Comment by thctlo** [comment]
>  now, if i try to send an email from my home, then i got a ? spam ? score, because my ISP dynamic host  is listed at Barracuda or SPAMHAUS ZEN lists. (or even my mobile phone* network).

This is not mailscanner problem imo. 
First of all, if YOU are using a server with dynamic ips, then you wil be block even more today. 
Setup the mailrelay of you ISP in postfix  
If thats no option, setup you server with static ip and request for a PTR record. 
last work around, 
setup in postfix a relay with gmail or and other ISP. 
for examplel : https://www.howtoforge.com/tutorial/configure-postfix-to-use-gmail-as-a-mail-relay/ 

Dont try to bypass the RFC's for mail.

**Comment by Skywalker-11** [comment]
As I understood it is not the server that has a dynamic ip but the client. Basically the same situation as if you are using a mail client via mobile network (where you usually can't even get a static IP).

If you only have a single server for "internal" clients (MUA) and "external" clients (other servers/MTAs) on which you are running MailScanner to scan all mails there is the problem. Because the MUAs IP address is probably in a RBL it would be flagged even if you know that the client normally could be trusted (is authenticated).

**Comment by shawniverson** [comment]
@Skywalker-11 I'm okay with merging the PR with a minor change to the comment field in MailScanner.conf (see Review).  Need to mention that it is limited to postfix.

**Comment by worgenrage** [comment]
Thank you, maybe my report wasn't really clear.

But Skywalker-11 figured it out very well :) 

My problem was, that if i use MailScanner with RBL* lists on my server, then if i connect to my own server with a client (mobile APN, etc) that has got on BL, then my own MailScanner marks me as spammer. That is why i suggested this feature, Probably other mail servers will mark my message sent from my phone as probably spam, but, at last not my "own mailscanner MTA" mark my message as spam.

And postfix examples well, yes. But you can control RBL checks in postfix for sendings and for incomings. smtp_* versus smtpd_* . In mailscanner you can't. If you on the list you got marked. Thats all. 

Kinda happy for this implement. :)

Reagards
Christian Hamar
Hungary
