### ISSUE TITLE
customize quarantined filenames?

### ISSUE THREAD

**Issue by waclaw66** [MailScanner/v5#129]
Hello!
I use Posfix together with Mailscanner and few antiviruses.
Is there any possibility to customize quarantine message filenames? It's very messy to have each spam message with it's random ID. I would really appreciated to have an option to add a timestamp as a prefix to the filename.
Is it possible to store quarantined message with all X-MailScanner- headers? I would like to see the spam score of messages.
Thanks in advance.

**Comment by shawniverson** [comment]
@waclaw66 I believe that customizing the quarantine message filenames would be a major breaking change.  Although MailScanner might be rewritten to support it, I'm unsure this a direction we should go.

Are you familiar with MailWatch?  Using MailWatch would help you with both of these issues, as it logs the message metadata and spam scores to searchable database and links back to the message ID.

**Comment by jcbenton** [comment]
Files (email) are stored as postfix queue files and not raw email. This will not work unless you use a milter.

**Comment by waclaw66** [comment]
@shawniverson Thanks for the suggestion, I tried recently to install MailWatch but I found it complicated to install on my server. My original intention was to have a web ui to manage spam over Amavis quarantine folder. Currently I stay with Amavis because it provides me easiest overview over spam. Thanks for your attention.
