### ISSUE TITLE
Add clamav configuration support for CentOS 7

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#132]
clamav is in an unusable state following mailscanner installation on CentOS7 and requires configuration.  Add clamav initial configuration when clamav is installed.

**Comment by shawniverson** [comment]
Problem with EPEL clamav package being too old, critical perl module not installed.

```
  CPAN.pm: Building C/CO/CONVERTER/Mail-ClamAV-0.29.tar.gz

The clamav version you are using is too old. Please upgrade to at least 0.95.1
No 'Makefile' created  CONVERTER/Mail-ClamAV-0.29.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
```

**Comment by shawniverson** [comment]
Check other distros for similar scenario

**Comment by shawniverson** [comment]
Failing across multiple builds.

Options:

- Package clamav >= required version for Mail-ClamAV-0.29

- Package version of Mail-ClamAV compatible with current EPEL release of clamav

**Comment by shawniverson** [comment]
Mail::ClamAV available as package in efa-project.org repo, Testing....

**Comment by shawniverson** [comment]
Actually EPEL is newer, but the CPAN Mail::ClamAV is not detecting the version of clamav present properly.

**Comment by shawniverson** [comment]
Installing Mail::ClamAV package works and fixes the problem.

Package is located here

https://dl.efa-project.org/rpm/CentOS/6/x86_64/perl-Mail-ClamAV-0.29-2.efa.el6.x86_64.rpm

@jcbenton May we get this rpm uploaded to s3 with the other perl modules?  This may be the best route to resolve this issue.   It is also compatible with CentOS 7.

I suspect I will need to check SuSE and Debian as well.

**Comment by shawniverson** [comment]
@jcbenton I have a generalized package built and available here:

https://dl.efa-project.org/build/MailScanner/perl-Mail-ClamAV-0.29-2.x86_64.rpm

Spec:

https://dl.efa-project.org/build/MailScanner/perl-Mail-ClamAV.spec

**Comment by jcbenton** [comment]
Are you doing more testing, or are you sure about this? One of the things I did several years ago was remove all of the additional RPMs in the MailScanner package in favor of using OS tools for all packages except MailScanner itself. Packages become dated and hard as hell to maintain for the numerous distributions. I don't think it would be a good idea to go down this road again unless absolutely necessary. Thoughts?

**Comment by shawniverson** [comment]
@jcbenton I think it is necessary.  Our current builds aren't succeeding on CentOS/RHEL because of this.  When CPAN attempts to build the perl module, it fails.  I'm open to another idea, I'm just not sure what that would be.

**Comment by jcbenton** [comment]
Can we talk? Skype: jcbentonjr 

I will edit delete this comment in a few minutes.

**Comment by shawniverson** [comment]
@jcbenton Found out why it is failing.  It is looking for clamav-devel.  I will add clamav-devel to install.sh and this issue should be resolved without having to maintain a separate rpm package.
