### ISSUE TITLE
mailscanner starts again and is not restarting

### ISSUE THREAD

**Issue by thctlo** [MailScanner/v5#136]
Hai, i noticed that mailscanner ( 5.0.7-1 )  on debian stretch is not restaring ok. 
After running : systemctl restart mailscanner a few times. 

12565 ?        Ss     0:00 MailScanner: starting child
19997 ?        S      0:02  \_ MailScanner: waiting for messages
20074 ?        S      0:02  \_ MailScanner: waiting for messages
20691 ?        S      0:01  \_ MailScanner: waiting for messages
20771 ?        S      0:01  \_ MailScanner: waiting for messages
20802 ?        S      0:01  \_ MailScanner: waiting for messages
18690 ?        Ssl    0:12 /usr/sbin/clamd --foreground=true
19458 ?        Ss     0:00 MailScanner: starting child
19468 ?        S      0:03  \_ MailScanner: waiting for messages
20023 ?        S      0:02  \_ MailScanner: waiting for messages
20657 ?        S      0:02  \_ MailScanner: waiting for messages
20730 ?        S      0:01  \_ MailScanner: waiting for messages
20745 ?        S      0:01  \_ MailScanner: waiting for messages
20599 ?        Ss     0:00 MailScanner: starting child
20600 ?        S      0:02  \_ MailScanner: waiting for messages
20623 ?        S      0:02  \_ MailScanner: waiting for messages
20755 ?        S      0:01  \_ MailScanner: waiting for messages
20763 ?        S      0:01  \_ MailScanner: waiting for messages
20827 ?        S      0:01  \_ MailScanner: waiting for messages
root@mailhopper2:/etc/spamassassin# /usr/lib/MailScanner/init/ms-init stop
MailScanner is already stopped

hmm, already stopped, thats not right.

**Comment by thctlo** [comment]
root@mailhopper2:/etc/spamassassin# /usr/lib/MailScanner/init/ms-init kill
Killing MailScanner and children ... mwa ha ha ha!

That works.  😁

**Comment by thctlo** [comment]
ok, the following fixed it for me. 

(p.s.) I use mysql for spamassassin/mailscanner.
systemctl edit --full mailscanner.service
changed :  
After=network-online.target remote-fs.target rsyslog.service mariadb.service
Wants=network-online.target mariadb.service

added : 
EnvironmentFile=-/etc/MailScanner/defaults
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/var/run/MailScanner.pid

with these changes systemctl restart mailscanner.service works fine.

**Comment by thctlo** [comment]
for completeness the full systemd file. 

[Unit]
Description=LSB: MailScanner daemon
Documentation=man:systemd-sysv-generator(8)
SourcePath=/usr/lib/MailScanner/init/ms-init
After=network-online.target remote-fs.target rsyslog.service mariadb.service
Wants=network-online.target mariadb.service

[Service]
Type=forking
Restart=no
TimeoutSec=1min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/usr/lib/MailScanner/init/ms-init start
ExecStop=/usr/lib/MailScanner/init/ms-init stop

#
EnvironmentFile=-/etc/MailScanner/defaults
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/var/run/MailScanner.pid


[Install]
WantedBy=multi-user.target

**Comment by shawniverson** [comment]
@thctlo Good call.  Updating systemd file.

**Comment by thctlo** [comment]
Hai, small update on this one. 
I noticed a few messages about the reload. due to the msre_reload bug i found in mailwatch.

The "adjusted"  overrided.conf file : 
# /etc/systemd/system/mailscanner.service.d/override.conf
[Unit]
After=network-online.target remote-fs.target rsyslog.service mariadb.service
Wants=network-online.target mariadb.service

[Service]
PIDFile=/var/run/MailScanner.pid
EnvironmentFile=-/etc/MailScanner/defaults
ExecReload=
ExecReload=/bin/kill -HUP $MAINPID

These need al to be clear first before we can set new commands in the override.conf  with : systemctl edit mailscanner.service
and if set directly in mailscanner.service, this is not needed but worth mentioning.
ExecStart
ExecStop
ExecReload 

Rebooted and reloaded multiple times now, and no errors seen anymore.
