### ISSUE TITLE
MailScanner vs google docs

### ISSUE THREAD

**Issue by bostjancvelbar** [MailScanner/v5#14]
Hi guys!

We are tryin' to solve this issue:
"https://forum.efa-project.org/viewtopic.php?f=13&t=1782&p=6792#p6792"

So far the conclusion is that google is inside "/etc/MailScanner/phishing.bad.sites.conf".
Any particular reason for doing that?
We have read some threads that google had some large phishing attacks back in "2014"... but is it necessary to still be in that CONF?
How can we solve that please?
With best regards

**Comment by shawniverson** [comment]
We need to get to Mailscanner v5 to resolve this issue.  It is scheduled
for next release.

**Comment by bostjancvelbar** [comment]
Thank you for your reply.
Are there any "un-official" release date for the v5? ;)
with best regards

**Comment by jcbenton** [comment]
Add docs.google.com to your phishing.safe.sites.custom file.

Not sure what Shawn means about v5 resolving the issue.


-
Jerry Benton
www.mailborder.com
+1 - 844-436-6245


-----Original Message-----

**Comment by bostjancvelbar** [comment]
Thank you for the reply.
Now I'm a little bit confused.
if I take a look of file: "/etc/MailScanner/phishing.safe.sites.conf"
there is already a line:
*.google.com

Shouldn't that work also for docs.google.com ?
Does phishing.bad.sites.conf takes precedence phishing.safe.sites.conf ?

Thanks, with best regards

**Comment by jcbenton** [comment]
I replied on the EFA site.

**Comment by shawniverson** [comment]
In mailscanner v4,  bad sites trump safe sites....I recall seeing a commit
in v5 that resolves this issue....

**Comment by msapiro** [comment]
On 08/19/2016 07:57 AM, Shawn Iverson wrote:
> In mailscanner v4, bad sites trump safe sites....I recall seeing a commit
> in v5 that resolves this issue....


Correct. See <https://github.com/MailScanner/v5/issues/9>

-- 
Mark Sapiro <mark@msapiro.net>        The highway is for gamblers,
San Francisco Bay Area, California    better use your sense - B. Dylan

**Comment by bostjancvelbar** [comment]
Thank you for the replies.
So to wrap things up.
1. Upgrade MailScanner is 1st thing to do.
2. Next, put docs.google.com on good sites config, right?
with best regards

**Comment by msapiro** [comment]
You want to put docs.google.com (or maybe even *.google.com) in phishing.safe.sites.custom. You don't want to put it in phishing.safe.sites.conf because that is overwritten by the daily cron run of ms-update-safe-sites.

**Comment by bostjancvelbar** [comment]
Thank you for your reply. 
But updating MailScanner 1st to version is 5 is mandatory for "phishing.safe.sites.conf" working correctly?
right?

**Comment by jcbenton** [comment]
No. You can simply update that program if you like.
http://phishing.mailscanner.info and download the new cron jobs.


-
Jerry Benton
www.mailborder.com
+1 - 844-436-6245


-----Original Message-----

**Comment by msapiro** [comment]
But, If you do not upgrade to MailScanner v5.3, phishing.safe.sites.conf will not override phishing.bad.sites.conf. See #9.
