### ISSUE TITLE
Wrapper Kaspersky 10 on Linux

### ISSUE THREAD

**Issue by jmuurling** [MailScanner/v5#142]
Does someone use Kaspersky Endpoint Security 10 for Linux?
Mailscanner has old wrappers defined.
Is there a new version?

**Comment by shawniverson** [comment]
Kaspersky 10 is way different than its predecessors, I am going to attempt to draft a wrapper.  I successfully installed the trial version.

**Comment by shawniverson** [comment]
Going to need somebody to do some testing and possibly take it from here.  I have the bones here to try.  Since I don't have a subscription, I don't have a database, so it doesn't work for me.

https://github.com/shawniverson/v5/tree/091918kaspersky

**Comment by shawniverson** [comment]
Notes:
Loosen permissions on config file in /etc/opt/kaspesrky  (mtagroup)
Loosen permissions on /var/log/kaspersky (mtagroup)
Make sure lock file is present

**Comment by shawniverson** [comment]
Using KSfLM: https://support.kaspersky.com/klms8#downloads

**Comment by b3b0** [comment]
I can do some testing in the next few days. I'll get back to you.

**Comment by shawniverson** [comment]
@b3b0 Any updates?  I want to merge this code, if it is actually working.

**Comment by b3b0** [comment]
![alt text](https://i.imgur.com/oS5Mtx7.png "It works!")

Looks great - the wrapper looks to be working.
