### ISSUE TITLE
restart mailscanner fails with ms-update-sa (debian stretch) + fix

### ISSUE THREAD

**Issue by thctlo** [MailScanner/v5#144]
Hai, i noticed that, logrotate make mailscanner fail. 

This is my log of the moment of logrotate. 
Jan 23 06:25:31 hostname systemd[1]: Reloading LSB: MailScanner daemon.
Jan 23 06:25:31 hostname kill[21145]: Usage:
Jan 23 06:25:31 hostname kill[21145]:  kill [options] <pid> [...]
Jan 23 06:25:31 hostname kill[21145]: Options:
Jan 23 06:25:31 hostname kill[21145]:  <pid> [...]            send signal to every <pid> listed
Jan 23 06:25:31 hostname kill[21145]:  -<signal>, -s, --signal <signal>
Jan 23 06:25:31 hostname kill[21145]:                         specify the <signal> to be sent
Jan 23 06:25:31 hostname kill[21145]:  -l, --list=[<signal>]  list all signal names, or convert one to a name
Jan 23 06:25:31 hostname kill[21145]:  -L, --table            list all signal names in a nice table
Jan 23 06:25:31 hostname kill[21145]:  -h, --help     display this help and exit
Jan 23 06:25:31 hostname kill[21145]:  -V, --version  output version information and exit
Jan 23 06:25:31 hostname kill[21145]: For more details see kill(1).
Jan 23 06:25:31 hostname systemd[1]: mailscanner.service: Control process exited, code=exited status=1
Jan 23 06:25:31 hostname systemd[1]: Reload failed for LSB: MailScanner daemon.
Jan 23 06:25:31 hostname systemd[1]: Reloading LSB: MailScanner daemon.
Jan 23 06:25:31 hostname kill[21149]: Usage:
Jan 23 06:25:31 hostname kill[21149]:  kill [options] <pid> [...]
Jan 23 06:25:31 hostname kill[21149]: Options:
Jan 23 06:25:31 hostname kill[21149]:  <pid> [...]            send signal to every <pid> listed
Jan 23 06:25:31 hostname kill[21149]:  -<signal>, -s, --signal <signal>
Jan 23 06:25:31 hostname kill[21149]:                         specify the <signal> to be sent
Jan 23 06:25:31 hostname kill[21149]:  -l, --list=[<signal>]  list all signal names, or convert one to a name
Jan 23 06:25:31 hostname kill[21149]:  -L, --table            list all signal names in a nice table
Jan 23 06:25:31 hostname kill[21149]:  -h, --help     display this help and exit
Jan 23 06:25:31 hostname kill[21149]:  -V, --version  output version information and exit
Jan 23 06:25:31 hostname kill[21149]: For more details see kill(1).
Jan 23 06:25:31 hostname systemd[1]: mailscanner.service: Control process exited, code=exited status=1
Jan 23 06:25:31 hostname systemd[1]: Reload failed for LSB: MailScanner daemon.
Jan 23 06:25:31 hostname systemd[1]: Stopping LSB: MailScanner daemon...
Jan 23 06:25:35 hostname ms-init[21153]: #015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\
Jan 23 06:25:35 hostname ms-init[21153]: MailScanner stopped
Jan 23 06:25:35 hostname systemd[1]: Stopped LSB: MailScanner daemon.
Jan 23 06:25:35 hostname systemd[1]: mailscanner.service: Unit entered failed state.
Jan 23 06:25:35 hostname systemd[1]: mailscanner.service: Failed with result 'exit-code'.
Jan 23 06:26:35 hostname systemd[1]: Starting LSB: MailScanner daemon...
Jan 23 06:26:35 hostname ms-init[21288]: MailScanner starting ...
Jan 23 06:26:38 hostname ms-init[21288]: MailScanner started with process id 21803
Jan 23 06:26:38 hostname systemd[1]: Started LSB: MailScanner daemon.

now even that the latest line states : 
- Jan 23 06:26:38 hostname systemd[1]: Started LSB: MailScanner daemon.
a process check, showed that "MailWatch SQL" wasnot started after the logrotate restart. 

a manual restart with : systemctl restart mailscanner show the folllowing log.
Jan 23 08:23:24 hostname systemd[1]: Stopping LSB: MailScanner daemon...
Jan 23 08:23:28 hostname ms-init[24277]: #015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\
Jan 23 08:23:28 hostname ms-init[24277]: MailScanner stopped
Jan 23 08:23:28 hostname systemd[1]: Stopped LSB: MailScanner daemon.
Jan 23 08:23:28 hostname systemd[1]: Starting LSB: MailScanner daemon...
Jan 23 08:23:28 hostname ms-init[24392]: MailScanner starting ...

And now a ps faux als shows the correct process tree.
24908 ?        S      0:00 MailWatch SQL
24910 ?        Ss     0:00 MailScanner: master process sleeping
24911 ?        S      0:01  \_ MailScanner: waiting for messages
24920 ?        S      0:01  \_ MailScanner: waiting for messages
24925 ?        S      0:01  \_ MailScanner: waiting for messages
24930 ?        S      0:01  \_ MailScanner: waiting for messages
24935 ?        S      0:01  \_ MailScanner: waiting for messages

My complete mailscanner.service and override part.
systemctl cat mailscanner
#/lib/systemd/system/mailscanner.service
[Unit]
Description=LSB: MailScanner daemon
Documentation=man:systemd-sysv-generator(8)
SourcePath=/usr/lib/MailScanner/init/ms-init
After=network-online.target remote-fs.target rsyslog.service

[Service]
Type=forking
Restart=no
TimeoutSec=1min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/usr/lib/MailScanner/init/ms-init start
ExecStop=/usr/lib/MailScanner/init/ms-init stop

[Install]
WantedBy=multi-user.target

#/etc/systemd/system/mailscanner.service.d/override.conf
[Unit]
After=network-online.target remote-fs.target rsyslog.service mariadb.service postfix.service
Wants=network-online.target mariadb.service postfix.service

[Service]
PIDFile=/var/run/MailScanner.pid
EnvironmentFile=-/etc/MailScanner/defaults
ExecReload=
ExecReload=/bin/kill -HUP $MAINPID

#This need to be in apache2.service to make msre_reload work from cron
#[Service]
#PrivateTmp=false

logrotate is left default as of the debian stretch install. 
running the following commands manualy works fine. 
systemctl start mailscanner
systemctl stop mailscanner
systemctl restart mailscanner
systemctl reload mailscanner

! reload did only work after changing the override file a bit.

**Comment by thctlo** [comment]
Ok, tracked this down to the file : /usr/sbin/ms-update-sa

**Comment by thctlo** [comment]
i changed the following part, ( last block ) 
# Only delete the logfile if the update succeeded
if [ $UPDATESUCCESS = 0 -a $COMPILESUCCESS = 0 -o $UPDATESUCCESS = 1 ]; then
        logger -i -p mail.notice "ms-update-sa: spamassassin signatures updated"
        rm -f $LOGFILE
        if [ -d /run/systemd/system ]; then
            systemctl -q is-active mailscanner && systemctl restart mailscanner || true
        else
            /usr/lib/MailScanner/init/ms-init restart >>$LOGFILE 2>&1 || true
        fi
fi

**Comment by shawniverson** [comment]
@thctlo Thanks for the update.  I will prepare a PR to address this issue.
