### ISSUE TITLE
mailscanner reload (partly fail) ms-update-phishing (Debian stretch)

### ISSUE THREAD

**Issue by thctlo** [MailScanner/v5#149]
Hai, 
after ms-update-phishing  was run mailwatch SQL is missing in the process list.

The file /usr/sbin/ms-update-phishing
contians : 
MSSTARTSCRIPT='/etc/init.d/mailscanner';
MSSERVICENAME='mailscanner.service';

i'm testing following. 
in /usr/sbin/ms-update-phishing 
i've changed this part, the reload was changed to restart.  ( its the end of the script)
```
updated=$(($bad_updated + $safe_updated));

if [ $updated -ge 1 ]; then
  if [ "$ms_cron_ps_restart" = "1" ]; then
    if [ ! -f /var/lock/subsys/MailScanner.off ]; then
      logger -p $SYSLOG.info -t ms-update-phishing reload MailScanner....
      if [ -d /etc/systemd ]; then
        systemctl restart $MSSERVICENAME > /dev/null 2>&1
        if [ $? != 0 ] ; then
          #echo "MailScanner reload failed - Retrying..."
          systemctl restart $MSSERVICENAME > /dev/null 2>&1
          if [ $? != 0 ] ; then
            #echo "Stopping MailScanner..."
            systemctl stop $MSSERVICENAME
            #echo "Waiting for a minute..."
            perl -e "sleep 60;"
            #echo "Attemping to start MailScanner..."
            systemctl start $MSSERVICENAME
          fi
        fi


and i report back tomorrow.

**Comment by thctlo** [comment]
Hai, this looks ok, now, mail is processes and scanned, but i still have a small question.
when you run : systemctl restart mailscanner && ps fax 

you see: 
23549 ?        S      0:00 MailWatch SQL
23551 ?        Ss     0:00 MailScanner: starting children
23552 ?        S      0:02  \_ MailScanner: starting children
23560 ?        S      0:02  \_ MailScanner: starting children
23577 ?        R      0:01  \_ MailScanner: starting children

now after the restarts from cron, the MailWatch SQL is missing in the process tree. 
but when i read the logs, i do see the messages: 
MailWatch: Starting up MailWatch SQL Blacklist
MailWatch: Read 1 blacklist entries
.... 

i also notice, when the restart is done from cli, you done see the \-/| rotating. 
but when  cron does the restart this is showin as 15/15-15\15|  in the logs. 
Removing this from the ms-init script may help.

**Comment by shawniverson** [comment]
Thanks, I'll mark this as a bug and work on this :)

**Comment by thctlo** [comment]
Hai, bit extra info. 
I did some more testing, even that after a reload MailWatch SQL isnt seen in the process tree, its used and works ok. Logs also shows the MailWacht white and blacklist. 

removing : 15/15-15\15| from ms-init should do the trick, if i have some time left today i'll have a look.
