### ISSUE TITLE
Long queue IDs in Postfix

### ISSUE THREAD

**Issue by alvarosplit** [MailScanner/v5#15]
Hi,

I've enabled long_queue_ids in Postfix (with hash_queue_depth disabled) and MailScanner works fine, but when it requeues the message, it creates one message with a short queue ID format:

MailScanner[14209]: Requeue: 3sK7N64rr3zJX5T.A6FFB to D74D7218040

The HDOutFileName function generates it in Postfix.pm:

$file = sprintf("%05X%lX", int(rand 1000000)+1, (stat($file))[1]);

that should be in a long format.
There's some info about how the long queue id format is generated:

http://postfix.1071664.n5.nabble.com/long-non-repeating-queue-ID-support-td41746.html

Thanks.

**Comment by alvarosplit** [comment]
In src/global/mail_queue.h there is more info:

 /*
  * The long non-repeating queue ID is encoded in an alphabet of 10 digits,
  * 21 upper-case characters, and 21 or fewer lower-case characters. The
  * alphabet is made "safe" by removing all the vowels (AEIOUaeiou). The ID
  * is the concatenation of:
  * 
  * - the time in seconds (base 52 encoded, six or more chars),
  * 
  * - the time in microseconds (base 52 encoded, exactly four chars),
  * 
  * - the 'z' character to separate the time and inode information,
  * 
  * - the inode number (base 51 encoded so that it contains no 'z').
  */

**Comment by alvarosplit** [comment]
Hi,

I attach a patch that implements this functionality. 

[Postfix.txt](https://github.com/MailScanner/v5/files/442511/Postfix.txt)

**Comment by jcbenton** [comment]
Thank you. How long have you been running this test? Does it also still work with the shorter queue ID's?

**Comment by alvarosplit** [comment]
Hi,
I've just written a message to the mailing list.
I'm running MailScanner-4.84.5-3 (with the patch to manage long queue IDs from 4.85.1-1 version) and it runs fine (the patch attached is done against last stable release code of MailScanner); I'll be watching it for some days.
I'll try to test it with the last version of MS in some days...

**Comment by jcbenton** [comment]
Latest stable is 5.0.3 ...

**Comment by alvarosplit** [comment]
Yes, I know, but the Postfix.pm's code hasn't changed...I'll try to test it with the last version.

**Comment by alvarosplit** [comment]
Hi again,

I've tested it with version 5.0.3 and it runs fine:

MailScanner[30555]: Requeue: 3sNGsC5qlHzJX79.AFFDC to 3sNGsD3k6yzJX72

I attach a new version of the patch (without a substr function call that is not necessary)
[Postfix.txt](https://github.com/MailScanner/v5/files/442867/Postfix.txt)

**Comment by alvarosplit** [comment]
Hi,

I attach 2 patches, for the last stable release, first one to enable long queue IDs format for the requeued message (after MailScanner analizes it) and the second one, to enable hashed queues (hold and incoming) with long queue IDs. 

[Postfix-diff.txt](https://github.com/MailScanner/v5/files/508559/Postfix-diff.txt)
[PFDiskStore-diff.txt](https://github.com/MailScanner/v5/files/508558/PFDiskStore-diff.txt)

**Comment by jcbenton** [comment]
Alvaro,

Can you post the entire files please? (not just the diff)

**Comment by alvarosplit** [comment]
Hi again,

I attach entire files in a zip file.

[ms-patch.zip](https://github.com/MailScanner/v5/files/529241/ms-patch.zip)

**Comment by jcbenton** [comment]
implemented

**Comment by msapiro** [comment]
There is an issue here. Since I installed 5.0.4-3, Mailscanner is requeuing  using short IDs. E.g.

Nov 16 10:17:34 sbh16 MailScanner[28781]: Requeue: 292D611E0061.A51BA to B6C030

**Comment by alvarosplit** [comment]
Hi,

I attach the files again, thank you. I've tested it with all options (long IDs, short IDs, hash queues...etc) and it runs fine. The diff is:

PFDiskStore.pm:

`  @@ -87,7 +87,7 @@
   #
  my $long_queue_id=0;
   my $hex=$this->{hdname};
-  if ( ($this->{hdname} =~ /[A-Za-z0-9]{15}$/) && ($MailScanner::SMDiskStore::HashDirDepth > 0)) {
+  if ($this->{hdname} =~ /[A-Za-z0-9]{15}$/) {
    # long queue id
    $long_queue_id=1;
 `

Postfix.pm:

`@@ -246,7 +246,7 @@
 
     # Bad hash key $file = sprintf("%05X%lX", time % 1000000, (stat($file))[1]);
     # Add 1 so the number is never zero (defensive programming)
-    $file = sprintf("%05X%lX", int(rand 1000000)+1, (stat($file))[1]);
+    #$file = sprintf("%05X%lX", int(rand 1000000)+1, (stat($file))[1]);
     #print STDERR "New Filename is $file\n";
 
     #
@@ -277,7 +277,7 @@
     #
     my $long_queue_id=0;
     my $hex;
-    if ( ($file =~ /\-[A-Za-z0-9]{15}\.[A-Za-z0-9]{5}$/) && ($MailScanner::SMDiskStore::HashDirDepth > 0) ) {
+    if ($file =~ /\-[A-Za-z0-9]{15}\.[A-Za-z0-9]{5}$/) {
         # Long queue IDs
         $long_queue_id=1;
`

[ms-patch2.zip](https://github.com/MailScanner/v5/files/595631/ms-patch2.zip)

**Comment by msapiro** [comment]
I have installed the files from [ms-patch2.zip](https://github.com/MailScanner/v5/files/595631/ms-patch2.zip) and it seems OK so far.

**Comment by jcbenton** [comment]
Added.

**Comment by alvarosplit** [comment]
Hi,

I've seen that Postfix can generate queue IDs longer than 15 chars (due the inode), so 2 regular expressions need to be changed:

Postfix.pm (line 280):
- if ($file =~ /\-[A-Za-z0-9]{15}\.[A-Za-z0-9]{5}$/) {
+ if ($file =~ /\-[A-Za-z0-9]{15,20}\.[A-Za-z0-9]{5}$/) {

PFDiskStore.pm (line 90):

- if ($this->{hdname} =~ /[A-Za-z0-9]{15}$/) {
+ if ($this->{hdname} =~ /[A-Za-z0-9]{15,20}$/) {

to support longer queue IDs.
