### ISSUE TITLE
Mailsceanner und Mailwatsch Cluster Setup

### ISSUE THREAD

**Issue by ghost235** [MailScanner/v5#157]
@Skywalker-11 Hi ich habe vor zwei Server mit Mailscanner zu clustern am liebsten das auch SA incl. Cache von beiden Servern gleich genutzt wird. Ob ein separater  Server für SA und clamav nötig /sinnvoll ist weiß ich noch nicht. 
Gibt es dafür Ansätze die ich beachten sollte? Kann ich das Mailscanner und SA Verzeichnis einfach per NFS sharen? Bei Mailwatch sehe ich noch nicht so das Problem einen zentralen MySQL bzw. eine zentrale Mailwatch Installation und alle Mailscanner loggen dort rein.

Grundsetup : debian9 (am liebsten), postfix 

Gibt es da Erfahrungswerte?

**Comment by Skywalker-11** [comment]
Mailwatch erkennt automatisch, welcher Server die Mail empfangen hat und greift beim Freigeben der Mail automatisch auf den richtigen Server zu. Somit ist es auch möglich separate Dateisysteme zu haben ohne Sychronisierung (habe ich bei mir im Einsatz).
Das einzige worauf du achten solltest ist das die Datenbank ständig erreichbar ist, da sonst nicht mehr gelogged wird und MS neu gestartet werden muss.
Die BayesDB von SpamAssassin kann ebenfalls über MySql laufen.
Bei mir habe ich MariaDB im Galera-Cluster laufen mit jeweils einem Node auf den MS-Servern.
Insgesamt läuft es sehr stabil.

**Comment by ghost235** [comment]
Danke für die Antwort.
Wie mache ich das am schlausten mit den MS Konfigs wie kann ich die syncron  halten?
Ok das heisßt du hast auf allen MS-Servern SA laufen und die rules pflegst du dann auch auf allen sepreat?
Ich habe auch schon ein,zwei Gedanken da ran verschwendet ob man einen dedizierten Server für SA / Clamd macht... da hab ich aber nen Komentar von Julian Field gefunden der das relativiert da  spamd /spamc  nicht so performant ist.

**Comment by Skywalker-11** [comment]
Bei mir ist es der Viren-Scanner, der am meisten Resourcen braucht. SA hat da eher einen geringen Anteil. 
Die MS-Konfigs ändere ich nur selten und manuell. Daher kann ich da nichts zu sagen. Wenn du die Frage nochmal in Englisch formulierst können andere eventuell weiterhelfen

**Comment by ghost235** [comment]
OK we continue in english...

Hi @all 
my plan is to setup 2 (or more) mailscanner servers not primary for load balancing rather for availability.
In my head it looks like thi:
two servers on each:
- debian
- postfix
- mailscanner
- a shared storage ( at the moment I'm not sure if NFS or iSCSI) for the user data ( mailboxes, webpages and so on)
- security stuff (fail2ban, rkhunter, chrrotkit .....) 
- virus scanners

so far ist clear now the tricki part: mailwatch, SA ( with razor, pryzor and custom rules) and clamav/ clamd (with antispam features)

mailwatch may be easy on both host apache sync th sites-available and the www-root on the shared storage the mysql on a ohter cluster or even on the both MS hosts (we will seen) - in any case both ms-host can log in mailwatch.

but what about SA? Have I to install it on both hosts? when yes will it read the rules from mailwatch db? or have I to sync the rules ? - or is it "better" on a dedicatet host ?
skywaker said he put bayesDB in a MySQL cluster on each of the MS-Hosts - this is one part !

by the way syncing ... what's the best way to sync the mailscanner config ? rsync /etc/mailscanner ? /etc/mailscanner -> shared storage ?

clamd in my mind is easy again either on the ms-host or a seperate host and mailscanner uses clamc to connet.

what you guys thik about this?

p.s. while writing I thiking about a amavid-new infront of it for pre queue scanning but this is just a fantasy :)

**Comment by thctlo** [comment]
@Ghost235, I have almost the same as you have.

I use spamassassin and bayes db in SQL, the database is also used on my kopano server, where users and drop an email in a folder and it gets trained. 

If you use the /etc/MailScanner/conf.d folder correclty, you can easy sync configs if you split up your config, in for example, 
1-host-ip.conf  the config part what is unique to the server. not synced.
2-shared-settings.conf   and sync this one. 
3-virusscanner.conf    optional more, for example if you want different viruscanners per mailscanner.
etc etc.

If you setup your servers and you did it exact the same, when you dont need to 
For spamassassin, look here for a good sql ( for debian ) setup. 
https://p5r.uk/blog/2017/spamassassin-with-mariadb.html 
next to that i have Dual delivery, bit fiddeling around, but i got it working within postfix and after the scan of mailscanner. (source : http://pjrlost.blogspot.nl/2012/11/smtp-delivery-to-two-mail-servers-via.html p.s. a rusian site has the scripts. ) 

... es gibt viele möglichkeiten ;-)

**Comment by ghost235** [comment]
@thctlo hey I playing arod a bit. One problem I've: I can't find the script can you give me a hint where I can find it?

**Comment by thctlo** [comment]
sorry for the late reply, but here it is.: 
https://wiki.rtzra.ru/software/postfix/postfix-dualdelivery
[https://wiki.rtzra.ru/software/postfix/postfix-dualdelivery]
