### ISSUE TITLE
Invalid systemd config and garbage output on stop/restart

### ISSUE THREAD

**Issue by Skywalker-11** [MailScanner/v5#169]
Fresh install of mailscanner 5.0.7-2 via deb-file on debian 9.

When installing the mailscanner service in systemd or doing `systemctl daemon-reload` following will be logged in syslog
` [/lib/systemd/system/mailscanner.service:19] Executable path is not absolute, ignoring: no`
The problematic line is `ExecReload=no`. I guess it should be `ExecReload=` (leave the `no` away). The effect is still that `systemctl reload mailscanner` won't be allowed

Second problem: When stopping/restarting the mailscanner service it prints garbage to the log ( `#015\#105|...`) is that intended?
```
Apr 14 18:37:52 master root[30872]: Stopping MailScanner
Apr 14 18:37:52 master MailScanner[30832]: MailScanner child caught a SIGHUP
Apr 14 18:37:52 master MailScanner[30832]: Config: calling custom end function SQLBlacklist
Apr 14 18:37:52 master MailScanner[30832]: MailWatch: Closing down MailWatch SQL Blacklist
Apr 14 18:37:52 master MailScanner[30832]: Config: calling custom end function SQLWhitelist
Apr 14 18:37:52 master MailScanner[30832]: MailWatch: Closing down MailWatch SQL Whitelist
Apr 14 18:37:52 master MailScanner[30832]: Config: calling custom end function MailWatchLogging
Apr 14 18:37:55 master ms-init[30863]: #015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-#015\#015|#015/#015-
Apr 14 18:37:55 master root[30945]: MailScanner syncing ramdisk to persistent store
Apr 14 18:37:55 master root[30950]: MailScanner stopped
```

**Comment by shawniverson** [comment]
Already fixed in recent commits.  I'll prepare a new release.

**Comment by shawniverson** [comment]
Preparing release 5.0.7-3 in commit  35df4330d2c3a26d18d41182027cbb26db1b77a8
