### ISSUE TITLE
Installation without reboot child processes crash (RHEL/CentOS)

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#173]
Apr 29 10:41:43 localhost MailScanner: waiting for children to die: Process did not exit cleanly, returned 29 with signal 0

**Comment by shawniverson** [comment]
Fixed in commit efac485428c342173b50aa88c503d3e8137ccef1

**Comment by shawniverson** [comment]
Can anyone confirm that we can safely ignore a signal 29?  It appears that the children are fine, but MailScanner is taking the non-zero result as a failure to spawn the child process.

**Comment by dkrotil** [comment]
I have SuSE and have similar problem, will look on the exit code and report back.

**Comment by shawniverson** [comment]
Problem is no longer present on CentOS 7 latest.

**Comment by shawniverson** [comment]
Problem is no longer present on openSuSE latest.

**Comment by shawniverson** [comment]
Closing issue, seems that newest OSes are not having this problem anymore.
