### ISSUE TITLE
Problem with fraud link detection

### ISSUE THREAD

**Issue by Skywalker-11** [MailScanner/v5#176]
There seems to be a problem with the fraud link detection. The following mail produces a fraud attempt report. It only contains the url `https://g.co/chrome/symantecpkicerts` for the link url and the link description and so should not be detected as fraud. 
Mail was created via Outlook 2016

```
<body lang=3D"DE" link=3D"#0563C1" vlink=3D"#954F72">
<div class=3D"WordSection1">
<p class=3D"MsoNormal"><a href=3D"https://g.co/chrome/symantecpkicerts">htt=
ps://g.co/chrome/symantecpkicerts</a>
<o:p></o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal"><span style=3D"mso-fareast-language:DE">Mit freundli=
chen Gr=FC=DFen<o:p></o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"mso-fareast-language:DE"><o:p>&nbsp;<=
/o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"mso-fareast-language:DE">Michael Piet=
sch</span><span style=3D"font-size:8.5pt;font-family:&quot;Fedra Sans Pro B=
ook&quot;,sans-serif;color:#7F7F7F;mso-fareast-language:DE">
<o:p></o:p></span></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
</body>
```

**Comment by shawniverson** [comment]
What is this "3D" thing I am seeing throughout the email source?  That doesn't look like a properly formed html to me.

**Comment by msapiro** [comment]
The above text is from a MIME part with Content-Transfer-Encoding: quoted-printable. '=3D' is quoted-printable encoding for '='.

To answer the original question, 'g.co' is in phishing.bad.sites.conf. That's what triggers the fraud alert.

**Comment by shawniverson** [comment]
@msapiro @Skywalker-11 I see, that makes sense. We may need @jcbenton's help to actually get that out of the bad sites, but I think you can override it yourself if I'm not mistaken by dropping it in phishing.safe.sites.conf.local .

**Comment by Skywalker-11** [comment]
Ok I overlooked it when checking the phishing conf. But is there a reason it is on the list? As all urls to that domain go to services provided by google I don't see why it should be on a phishing blacklist.

**Comment by msapiro** [comment]
It's on the list because it's a URL shortening service and phishers use it to hide malicious URLs.

**Comment by Skywalker-11** [comment]
If you look at g.co page you see that it only serves google services so it can only be used to direct to places on the google domain and they are also managed directly by google (https://googleblog.blogspot.de/2011/07/gco-official-url-shortcut-for-google.html). So in opposite to goo.gl which could be used by anyone to generate redirects there seems to little to no risk that the g.co can be used in a malicious way.
```
You’ve arrived at this page because you typed or linked to “g.co”, Google’s official URL shortcut just for Google websites.

Whenever you see a short “g.co” link, you can trust that it will always take you to a Google product or service.

We also have a public URL shortener at goo.gl. You can use this to shorten up URLs across the web.
```

**Comment by msapiro** [comment]
The phishing.bad.sites.conf list is updated from the master at http://phishing.mailscanner.info/phishing.bad.sites.conf which is maintained by @jcbenton, I *think* from data from https://www.phishtank.com/ although g.co is not currently listed at phishtank.

**Comment by jcbenton** [comment]
I added g.co to the exclusions. 

Note that just because it points to something Google owns does not make it safe. People use Google Docs all the time to deliver nasty payloads.

**Comment by jcbenton** [comment]
I added g.co to the exclusions. 

 

Note that just because it points to something Google owns does not make it safe. People use Google Docs all the time to deliver nasty payloads. 

 

 

 

--

Jerry Benton

 <http://www.mailborder.com/> www.mailborder.com
+1   (843) 800-8605

+44 (020) 3883-8605
