### ISSUE TITLE
install generic nix version from scratch and ran into problem with virus scan none not being configured

### ISSUE THREAD

**Issue by maciakt** [MailScanner/v5#180]
I had to build MailScanner for generic linux from scratch today.  Everything worked good (after following the directions and setting permissions correctly ) but I was having a problem with the mail being stuck in the HOLD queue.   Turns out to be a simple fix that took me forever to resolve because I couldn't find the answer anywhere - the logs showed this:

May 27 00:04:37 domain-server MailScanner[10169]: Virus scanner "none" not found in virus.scanners.conf file. Please check your spelling in "Virus Scanners =" line of MailScanner.conf

I added the following to /etc/MailScanner/virus.scanners.conf:

none                    /bin/false                                              /dev/null

then restarted MailScanner and it processed all my held email!

I am going to try to do a pull request to get this updated (surprised nobody else complained about it since it looks like that virus.scanners.conf wasn't updated since c7697bb  on Aug 13, 2016

**Comment by maciakt** [comment]
getting a 403 when I try to push my branch with the change.   If somebody can let me create branches I would be happy to make a PR.

**Comment by msapiro** [comment]
The normal flow is to fork MailScanner/v5 to your own space. Then make your changes to that branch and create a PR. If you are trying to create a new branch within MailScanner/v5, that won't work.

**Comment by maciakt** [comment]
alright thanks! I am making the PR now
