### ISSUE TITLE
error in manual

### ISSUE THREAD

**Issue by John-B** [MailScanner/v5#202]
The manual https://s3.amazonaws.com/msv5/docs/ms-admin-guide.pdfadvises to send false positive reports suport@mailscaner.info. That address does not work.

**Comment by shawniverson** [comment]
@jcbenton Do you have the original word doc for this manual?  It is in need of an update.  I can extract the pdf, but that can sometimes be messy.

**Comment by msapiro** [comment]
This was once published as a physical paper book. I have a copy. It is very out of date. The note on the title page says "Edition 1. This book is based on the implementation of MailScanner as at Version 4.61."

I doubt anyone wants to do a complete update. I think it would be better to either remove it from the web site or link it through a disclaimer page.

**Comment by jcbenton** [comment]
No, I don't. I was given only the PDF.
