### ISSUE TITLE
Systemd+Clamav-daemon

### ISSUE THREAD

**Issue by Skywalker-11** [MailScanner/v5#204]
Mailscanner should be started after clamav-daemon.service and have such dependency in the systemd config.

Otherwise the clamd daemon may not be up yet but mailscanner has already started and begins scanning mails. In that case the clamd scan could theoretically time out (DoS warnings?). Or are there other precautions that prevent such a case?

**Comment by shawniverson** [comment]
To tag along with this issue, it appears that when clamd is an installed scanner and is not running, MailScanner goes nuts trying to scan the same message batch over and over.  I don't like this behavior.  I would rather have MailScanner either stop entirely or periodically post an error to the log instead.

**Comment by Skywalker-11** [comment]
For reference: https://github.com/mailwatch/MailWatch/issues/1088

**Comment by shawniverson** [comment]
There doesn't seem to be a standard way to target clamd...  It is named various different ways in the distros, even differently between versions of the same distro (kind've a bit of a trainwreck with package maintainers...imo).  I need to think about this, but in the meantime I'm going to try track down the loop issue...

**Comment by Skywalker-11** [comment]
Not sure if it is related in any way but I also noticed that in some cases although I stopped MS via `systemctl stop mailscanner` there were still MailScanner processes running. I haven't found a way to reliably reproduce it. (Debian 9)

**Comment by shawniverson** [comment]
https://github.com/MailScanner/v5/pull/207

**Comment by shawniverson** [comment]
After further thought, I'm not sure that adding a/v scanners to the systemd unit should be the job of mailscanner.  Folks can use a variety of scanners (or none) and should probably add them as a dependency as part of the av configuration step.

**Comment by shawniverson** [comment]
@Skywalker-11 Interesting that you are seeing left over processes.  Any chance this is related to the MailWatch Logger being hooked into MailScanner?

**Comment by shawniverson** [comment]
Well, crud, #207 doesn't appear to resolve the logging issue...digging a little deeper into this...

**Comment by thctlo** [comment]
in case of the not started clamav when you start mailscanner, thats a simple one. 

in systemd, this is my personal override.conf. 

# /etc/systemd/system/mailscanner.service.d/override.conf
[Unit]
After=network-online.target remote-fs.target rsyslog.service mariadb.service postfix.service clamav-daemon.service
Wants=network-online.target mariadb.service postfix.service  clamav-daemon.service

Extra part, i dont know it its still needed.
#! Note, run: systemctl edit apache2.service
# Add this in apache2.service.
PrivateTmp=false

**Comment by shawniverson** [comment]
@Skywalker-11 Please test PR #208 if you have time :)

**Comment by Skywalker-11** [comment]
As said I couldn't reliable reproduce the problem but I'll try to keep it in mind and update if I encounter it again

**Comment by shawniverson** [comment]
@Skywalker-11 I am testing by stopping the av daemons while MailScanner is still running.  So far it seems to work, although it seems to miss scanning a few messages initially...

**Comment by Skywalker-11** [comment]
The problem with MS still running seemed to be independent from av daemon as I was using clamav instead of clamd in some cases.

**Comment by shawniverson** [comment]
@Skywalker-11 Yeah, this should work in both cases, since a failure of clamav will trigger the loop as well until it is resolved.  At least it adds another layer to prevent the loggers from being called repeatedly.
