### ISSUE TITLE
new Office docs with brackets in filename detected as old Filetypes

### ISSUE THREAD

**Issue by m3morx** [MailScanner/v5#21]
Hi everyone

I'm running into a issue with the Filetype scan.
If i add a attachment to an e-mail i.e. "example(example)something.docx, it get identified as old Word File instead of passing.

someone ran in the same issue ?

**Comment by msapiro** [comment]
What does the 'file' command on the MailScanner machine report for these files, and what do you have in filetype.rules.conf ?

**Comment by m3morx** [comment]
Can't follow you what you mean with 'file' command.
This is what the MailScanner log say:

Filename Checks:  (9A691E0532.AF785 asdfasdf(asdfasdf).docx)
Other Checks: Found 1 problems
Cleaned: Delivered 1 cleaned messages

filetype.rules.conf
allow   text            -                       -
allow   \bscript        -                       -
allow   archive         -                       -
allow   postscript      -                       -
deny    self-extract    No self-extracting archives     No self-extracting archives allowed
deny    executable      No executables          No programs allowed
#EXAMPLE: deny  -       x-dosexec       No DOS executables      No DOS programs allowed
deny    ELF             No executables          No programs allowed
rename  Registry        Windows Registry entries (renamed)      Windows Registry files (renamed)

#deny   MPEG            No MPEG movies          No MPEG movies allowed
#deny   AVI             No AVI movies           No AVI movies allowed
#deny   MNG             No MNG/PNG movies       No MNG movies allowed
#deny   QuickTime       No QuickTime movies     No QuickTime movies allowed
#deny   ASF             No Windows media        No Windows media files allowed
#deny   metafont        No Windows Metafont drawings    No WMF drawings allowed


For workaround, i've added to filename.rules.conf:
allow   \.docx$                 -       -
allow   \.xlsx$                 -       -
allow   \.pptx$                 -       -

**Comment by msapiro** [comment]
This is not filetype, it is filename so my question about the 'file' command is irrelevant as is filetype.rules.conf.

Is your workaround effective? If so, there is some other rule in filename.rules.conf that is blocking this name. The distributed filename.rules.conf will not block asdfasdf(asdfasdf).docx. Is that the actual name?

The log message

Filename Checks: (9A691E0532.AF785 asdfasdf(asdfasdf).docx)

seems incomplete. Normally there will be a reason from the filename.rules.conf deny entry similar to

Filename Checks: Windows/DOS Executable (BDF273402DB.A8F3E c.exe)

where c.exe is the file name, BDF273402DB.A8F3E is the Postfix queue ID and Windows/DOS Executable is the reason.

**Comment by jcbenton** [comment]
he did not have docx in his filetypes. not an issue. closing.
