### ISSUE TITLE
passive MS in HA Cluster gets started (not by cluster manager!!)

### ISSUE THREAD

**Issue by mschiessl** [MailScanner/v5#210]
I have a pacemaker HA setup with MS installed on 2 boxes. One active (services started) one passive for failover.

No i found that MS gets startet once a day on the passive box and pacemake is not the reason.
It looks like that it gets fired up by the daily cron ( and yes, ms_cron_check=0 in my defaults on both boxes).

Seems to me like the all or one of the update jobs SA / PS / SN are firing up the service due to the reload.

I have debian 9 - using init scripts

**Comment by shawniverson** [comment]
Did you disable the other crons as well?  Each of them is capable of starting up MailScanner.  You may want to disable them entirely and perhaps call them only on the running node.

**Comment by mschiessl** [comment]
Well i tried to let the crons themselves active - but hoped that they will check for a running process prior to reload (start) a MS instance - gonna see if i can add a little contrib here - should be quite ease since we know where MS pids are saved ...

**Comment by shawniverson** [comment]
@mschiessl Should be an easy thing to implement.  If you have time, go for it. If not, I'll flag this for a fix.

**Comment by Skywalker-11** [comment]
Easiest workaround would be to use an if statement to check if the pid file exists or process is running and only then execute the normal cron tasks of MS

**Comment by mschiessl** [comment]
@Skywalker-11  - ill try to see if i can come up with something this week ... time is key ⌚️

**Comment by mschiessl** [comment]
@shawniverson  - just did - see my comment on the diff as well - works perfectly !

closing this bug ;)
