### ISSUE TITLE
DKIM Invalid Due to Mailscanner

### ISSUE THREAD

**Issue by bilal0631** [MailScanner/v5#212]
I am solving this problem from last week but no success at all. My DKIM signature works well if i stop mailscanner but when i enabale mailscanner my signatures become Invalid. I have studied that its due to watermark add by mailscanner and i disable watermark as well but no effect at all . Anyone please help me ??????

**Comment by shawniverson** [comment]
Do you have these enabled?

# Some people prefer that message headers are added in strict order with
# the newest headers at the top and the oldest headers at the bottom.
# This is also required if you receive a message which is authenticated by
# DKIM, and you are forwarding that message onto somewhere else, and want
# not to break the DKIM signature.
# **Note**: To avoid breaking DKIM signatures, you *must* also set
#   Multiple Headers = add
# So if some of your users forward mail from PayPal, Ebay or Yahoo! to
# accounts stored on Gmail or Googlemail, then you need to set this to "yes"
# and "Multiple Headers = add" to avoid breaking the DKIM signature.
# It may be worth using a ruleset to just apply this to messages sent by
# the companies mentioned above.
# This can also be the filename of a ruleset.
Place New Headers At Top Of Message = yes

# What to do when you get several MailScanner headers in one message,
# from multiple MailScanner servers. Values are
#      "append"  : Append the new data to the existing header
#      "add"     : Add a new header
#      "replace" : Replace the old data with the new data
# Default is "append"
# This can also be the filename of a ruleset.
Multiple Headers = add
