### ISSUE TITLE
Option "ClamAV Full Message Scan"

### ISSUE THREAD

**Issue by fabiodemartin** [MailScanner/v5#219]
Hi,

I would ask if the option "ClamAV Full Message Scan" is only available to to ClamavModule and not for CLAMD.
Looking into the code I found it only on InitClamAVModParser.
Is it possible to be available to CLAMD module also?

Regards.

**Comment by shawniverson** [comment]
This setting is not applicable to clamd.  Clamd functions differently than ClamavModule.  Clamd scans an entire directory tree, whereas clamavmodule scans one file at a time (with the help of a loop, which is why it is slower than clamd)

**Comment by fabiodemartin** [comment]
Thanks for the answer. I think would be great an option to have the full message available for scanning instead of decoded parts. Clamd and other scanners have the ability to scan the message in pristine format and "possibly" there would be a performance gain.
I tried to use the generic-wrapper to extend the virus scanner but its the same. The pristine message is not available.
Regards.

**Comment by shawniverson** [comment]
@fabiodemartin I am going to attempt to duplicate the code to clamd and see what happens...
