### ISSUE TITLE
MailServer Attack Issue

### ISSUE THREAD

**Issue by bilal0631** [MailScanner/v5#220]
Dear All: Please help !!! i have set a Mail server , my mail server is not an open relay . SPF , DKIM, DMARC tests are passed as well .  I have also set a Mailscanner, Smapassasiyzan and Mailwatcher . But everyday thousands of spam/attack emails stuck my mail queue and interseting thing is that the mail addresses not contain my domain in in From or To email address (Example noreply@pie.net,pk  to  xyz@gmail,com ) . Any solution to mitigate this problem

**Comment by shawniverson** [comment]
Why are you accepting mail with no From or To address?  You need to configure your MTA to reject this stuff before it reaches mailscanner.

**Comment by shawniverson** [comment]
Closing, this is an MTA level issue.
