### ISSUE TITLE
Fax link detected as possible fraud attempt

### ISSUE THREAD

**Issue by NoahJose** [MailScanner/v5#224]
Hello, is this a bug?

MailScanner has detected a possible fraud attempt from "fax:949.680.4724" claiming to be 949.680.4724
--

**Comment by shawniverson** [comment]
Could possibly be, do you have a sample email source, redacted?

**Comment by NoahJose** [comment]
Sure. Here’s an example of my signature block with fax number. I also attached a screenshot showing the error as it came in a reply from one of our customers.

 ​

Alex Williams

Marketing Communications Coordinator



[cid:image001.png@01D44AAF.2C5FE000]


949.783.7314<tel:949.783.7314>


[cid:image002.png@01D44AAF.2C5FE000]


949.680.4724<fax:949.680.4724>


[cid:image003.png@01D44AAF.2C5FE000]


awilliams@nexsuninc.com<mailto:awilliams@nexsuninc.com>




Nexsun Electronics, Inc.<https://www.nexsuninc.com/?utm_source=signature&utm_medium=email&utm_campaign=exclaimer>

Suntsu Frequency Control, Inc.<http://suntsuinc.com/?utm_source=signature&utm_medium=email&utm_campaign=exclaimer>

142 TECHNOLOGY DR., SUITE 150
IRVINE, CA 92618




[cid:image004.png@01D44AAF.2C5FE000]

From Ou<https://www.nexsuninc.com/blog/?utm_source=signature&utm_medium=email&utm_campaign=exclaimer>r Blog:<https://www.nexsuninc.com/blog/?utm_source=signature&utm_medium=email&utm_campaign=exclaimer>


[cid:image005.png@01D44AAF.2C5FE000]


Powering a Smart Grid Revolution<https://www.nexsuninc.com/2018/08/16/powering-a-smart-grid-revolution/?utm_source=signature&utm_medium=email&utm_campaign=exclaimer>


[cid:image006.png@01D44AAF.2C5FE000]


How to Match Antennas to Your Design<https://www.nexsuninc.com/2018/06/19/how-to-match-antennas-to-your-design/?utm_source=signature&utm_medium=email&utm_campaign=exclaimer>












[cid:image007.png@01D44AAF.2C5FE000]


 
Alex Williams
Marketing Communications Coordinator
Nexsun Electronics, Inc.
Suntsu Frequency Control, Inc.

**Comment by shawniverson** [comment]
Looks like we need an exception in the code for fax links :)

**Comment by NoahJose** [comment]
Thank you so much for your response.


 
Alex Williams
Marketing Communications Coordinator
949.783.7314
949.680.4724
awilliams@nexsuninc.com
Nexsun Electronics, Inc.
Suntsu Frequency Control, Inc.
142 TECHNOLOGY DR., SUITE 150
IRVINE, CA 92618
From Our Blog:
Powering a Smart Grid Revolution
How to Match Antennas to Your Design

**Comment by msapiro** [comment]
This is a bit too convoluted for me to actually figure out, but I think we need to update the code in `sub CleanLinkURL` in `MailScanner/Message.pm` to understand `tel:` and `fax:` URIs. I.e., I think we still want to flag them if the numbers are different, but not if the only difference is the presence of `tel:` or `fax:`.
