### ISSUE TITLE
Message with .dat don't want to cross mailscanner or to be released

### ISSUE THREAD

**Issue by stefaweb** [MailScanner/v5#232]
With Mailscanner 5.1.1-1

I tried to release the complete mail or only the body or only the body and the MSWord file. No successful.

I've a mail with this result:
MailScanner: No programs allowed (200000.dat)
MailScanner: No programs allowed (200000.dat)

![capture d ecran 2018-10-04 a 11 47 43](https://user-images.githubusercontent.com/12907102/46466403-8052d200-c7cb-11e8-832f-433759e23007.png)

I don't have a rule in Mailscanner to deny .dat (not found something referenced to that).

If someone have an idea.

**Comment by shawniverson** [comment]
It is being detected as an executable binary for some reason in the FileType ruleset.  This is either bad magic in the file command or the .dat file has an actual executable preamble.

Anyway, you should be able to release it regardless.  Do you have the whitelist defined for filetype.rules as described here?

**Comment by stefaweb** [comment]
Oops, this is my fault.

When I cloned my new MailScanner server with Postfix, I forgot to create `filename.rules` and others specifics files for MailWatch.

It works now.

Thanks a lot.

**Comment by stefaweb** [comment]
I close.
