### ISSUE TITLE
Unicode characters not handled properly in attachment names

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#233]
https://github.com/mailwatch/MailWatch/issues/1109

**Comment by shawniverson** [comment]
Filename not being written to queue with this character and bypassing scan.

```
temp象.cer
```

**Comment by shawniverson** [comment]
Appears to be an issue with the MIME Parser...

**Comment by shawniverson** [comment]
Filename is encoded and doesn't appear to be parsed...
```
Content-Type: application/x-x509-ca-cert; name="=?UTF-8?B?dGVtcOixoS5jZXI=?="
Content-Disposition: attachment; filename="=?UTF-8?B?dGVtcOixoS5jZXI=?="
```

**Comment by shawniverson** [comment]
Non unicode filename...
```
Content-Type: application/x-x509-ca-cert; name="temp.cer"
Content-Disposition: attachment; filename="temp.cer"
```

**Comment by shawniverson** [comment]
Appears to be a bug in MIME::Parser, reported bug, trying MIME::Fast instead.

**Comment by shawniverson** [comment]
Bump...MIME::Fast seems to be stale...

**Comment by shawniverson** [comment]
Stop gap measure:  set decode_headers to 1 for now until the bug in MIME::Parser is resolved.  Only option at the moment unless someone has a better idea.  At least it will attempt to decode the header and create a file.

**Comment by shawniverson** [comment]
Leaving issue open until permanent fix is found.

**Comment by shawniverson** [comment]
Revisiting, may be related to faulty handler in WordDecorder I just discovered...

**Comment by shawniverson** [comment]
Looks related, but is triggered internally in MIME::Parser and cannot intercept.  Will need to keep researching this.

**Comment by shawniverson** [comment]
Trying native Encode module...

**Comment by thctlo** [comment]
Yesterday me and my collega where solving simular problem. 
in the end we used  in our perl script to send mails. 
This is the script we used in the end.
We import a file and line 1 = to, 2= from, 3,= subject  .. aah you know this, just have a look at the script. 
it solve our ü in names and subject. mime conversions is no fun. 

on Debian 9 its : ```apt install libmime-lite-tt-perl``` 
source info : https://metacpan.org/pod/MIME::Lite::TT::HTML

```
#!/bin/perl
$mail_prog = "/usr/lib/sendmail";
use warnings;
use MIME::Lite::TT::HTML;

open (FILE,"/tmp/tmp-mail-To-Import") || die "Can't make /tmp/tmp-mail-To-Import\n";
@filecontent = <FILE>;
close(FILE);
$to = $filecontent[0];
$from = $filecontent[1];
$subject = $filecontent[2];
chomp($to);
chomp($from);
chomp($subject);
$filecontent[0] = "";
$filecontent[1] = "";
$filecontent[2] = "";
my $msg = MIME::Lite::TT::HTML->new(
                    From        =>  '$from',
                    To          =>  '$to',
                    Subject     =>  '$subject',
                    Template    =>   {'@filecontent'},
);
$msg->send;

exit;
```

**Comment by thctlo** [comment]
the other option we use is : 
```
use Encode qw(decode encode);
pen (FILE,"/tmp/tmp-mail-To-Import") || die "Can't make /tmp/tmp-mail-To-Import\n";
@filecontent = <FILE>;
close(FILE);
$to = $filecontent[0];
$from = $filecontent[1];
$subject = $filecontent[2];
chomp($to);
chomp($from);
chomp($subject);
$filecontent[0] = "";
$filecontent[1] = "";
$filecontent[2] = "";
my $subject_encoded = encode("MIME-Q", $subject);
```
this one is in my optinion the best, but im no coder..

**Comment by shawniverson** [comment]
Problem appears to be no longer present after commit https://github.com/MailScanner/v5/commit/481eed103674c0afcf3c4622f8fe6b883c975b8e using MIME::Tools version 5.509 with decode_headers turned off.

Should have checked this again before all the hassle 😆 

Preparing to disable workaround.
