### ISSUE TITLE
Virus Scanning do not care about configuration

### ISSUE THREAD

**Issue by m3morx** [MailScanner/v5#240]
Hi

I'm facing with a problem of virus and content scanning.
i'm trying to disable scanning by a rule with the content:

FromOrTo:  *@domin.tld no
FromOrTo: default yes

The Mailscanner do not care about this Rule. In my mail log every message get scanned.
Even if i switch Virus Scanning = no in MailScanner.conf

Virus scanner is clamAV

MailScanner 5.0.6
Postfix 3.2.6
ClamAV 0.100.1

Any idea ?

**Comment by shawniverson** [comment]
Try leaving off the wildcard.

**Comment by msapiro** [comment]
What do you get from
```
ms-peek scanmessages /etc/MailScanner/MailScanner.conf 
```
I.e., does it point to the file where you are placing those rules?

**Comment by m3morx** [comment]
ms-peek say yes
I could this verrify before by misstyping the rule, and it generated a Logmessage about that rule who not be found.

**Comment by msapiro** [comment]
If ms-peek says Yes, youy have not configured MailScanner to use your Scan Messages rule set. You need to figure out why
```
ms-peek scanmessages /etc/MailScanner/MailScanner.conf 
```
does not reply with the path to your rule set. Where did you put
```
Scan Messages = path/to/your/rules
```
If you put it in `/etc/MailScanner/MailScanner.conf`, perhaps it is overridden by a setting in some `/etc/MailScanner/conf.d/` file

**Comment by shawniverson** [comment]
Closing due to lack of response and inability to reproduce issue.

**Comment by m3morx** [comment]
sorry for the delay. I've troubleshooted it again and found a foult in my configuration. 
I've put the path for the ruleset behind the option "Virus Scanning" Instead of "Scan Messages"
Thank you
