### ISSUE TITLE
DKIM signature with mail scanner

### ISSUE THREAD

**Issue by amir0150** [MailScanner/v5#26]
I am using mailscanner with postfix since 6 months and its been working very well except for one problem which is DKIM signature.
We require every email to be with with a disclaimer message which is under our control and for that we are using the mailscanners signing.rules feature. 
the problem occuring is that when we enable the email signing with the disclaimer message the DKIM signature becomes invalid. 
I do understand the problem because the mail content is being modified after postfix signs the DKIM signature and it is becoming invalid further when the mailscanner is modifying the message with its disclaimer. I need help here.
Is there anyway that i can make mailscanner do the DKIM signing or rewrite the DKIM signature so that it remains valid through the mail transfer process.
I tried to use a package called altermime which enables postfix to do the disclaimer signing but somehow its giving problem with centos 6.5 and it doesnt seems as flexible as the mailscanner.

awaiting response. Thanks in advance. 

Regards,
Amir

**Comment by jcbenton** [comment]
Amir,

Yes, you will need to do it with your MTA somehow before DKIM. I have
not researched this yet, so I do not have any information for you.


-
Jerry Benton
www.mailborder.com
+1 - 844-436-6245


-----Original Message-----

**Comment by msapiro** [comment]
This is not a MailScanner issue. Your MTA is misconfigured. It needs to DKIM sign the mail on the way out after MailScanner, not upon receipt.

**Comment by msapiro** [comment]
On 10/27/2016 12:22 AM, amir0150 wrote:

> Is there anyway that i can make mailscanner do the DKIM signing or
> rewrite the DKIM signature so that it remains valid through the mail
> transfer process.


This is not a MailScanner issue. Your MTA is misconfigured. It needs to
DKIM sign the mail on the way out after MailScanner, not upon receipt.

-- 
Mark Sapiro <mark@msapiro.net>        The highway is for gamblers,
San Francisco Bay Area, California    better use your sense - B. Dylan

**Comment by amir0150** [comment]
Ok Thank you all. Ill just look into the MTA configuration again.
