### ISSUE TITLE
Directory-exist validation in ms-clean-quarantine fails, recursively deleting all files from / older than 7 days.

### ISSUE THREAD

**Issue by paul-williamson** [MailScanner/v5#28]
Hi,

From a disastrous experience, we have discovered that the validation that the quarantine directory exists does not work, and as a result caused the ms-clean-quarantine script to delete any files older than 7 days from the entire file-system, starting in /.

As we have stopped using MailScanner, we had just removed MailScanner.conf, however had not been aware this cron was still in place. The removal of MailScanner.conf triggered this bad behaviour.

```
QUICKPEEK=/usr/sbin/ms-peek
ms_conf=/etc/MailScanner/MailScanner.conf
QUARDIR=`${QUICKPEEK} QuarantineDir ${ms_conf}`
```

QUARDIR in this case (when MailScanner.conf is missing) returns a whitespace/blank value which actually passes "# die if does not exist” check which then cd’s into / and runs "find . -type f -mtime +7 -exec rm -f {} \; >/dev/null 2>&1”.

If $QUARDIR was double quoted in the if statement it would have been fine.

```
# die if does not exist
if [ ! -d $QUARDIR ]; then
	logger -i -p mail.notice "ERROR: ms-clean-quarantine - quarantine directory not found"
	echo "Aborted: cannot find quarantine directory. Check the /etc/MailScanner/MailScanner.conf file"
	echo "'Quarantine Dir' setting."
	exit 1
fi

# if not disabled
if [ $q_days -gt 0 ]; then
	if [ -d $QUARDIR ]; then
		cd $QUARDIR
		logger -i -p mail.notice "ms-clean-quarantine: cleaning quarantine older than $q_days days"	
		find . -type f -mtime +$q_days -exec rm -f {} \; >/dev/null 2>&1
		find . -type d -empty -delete >/dev/null 2>&1
	fi
	exit 0
else
	logger -i -p mail.notice "WARN: ms-clean-quarantine called but is disabled"
	echo "Aborted: quarantine cleaning is disabled"
    exit 1
fi

```

https://github.com/MailScanner/v5/blob/master/common/usr/sbin/ms-clean-quarantine#L26
https://github.com/MailScanner/v5/blob/master/common/usr/sbin/ms-clean-quarantine#L35

We would like to ensure that nobody else is affected by this bug in future!

Thanks.

**Comment by jcbenton** [comment]
implemented
