### ISSUE TITLE
Don't loose message on Disarm DoS attack #55

### ISSUE THREAD

**Issue by spec1re** [MailScanner/v5#292]
Please make this patch an option, I'm using this patch now over 1,5 years with different MS versions and without any hiccups or side effects. 

Last time I've updated MS and forgot to apply this patch, sadly lost few legitimate mails due the DoS bug.

https://github.com/MailScanner/v4/pull/55

Thanks.

**Comment by shawniverson** [comment]
Merged https://github.com/MailScanner/v5/pull/302
