### ISSUE TITLE
False positive when Dropbox link is in the message

### ISSUE THREAD

**Issue by jorisw** [MailScanner/v5#297]
I noticed some peers email eachother exports of web app's source code and database through a Dropbox link:

```
You can find all the exports I did in the following link: https://www.dropbox.com/s/oiereowirqhjwor/euhroiquhroiue.zip?dl=0
```

The resulting body of the message was:

- You can find all the exports I did in the following link: _**MailScanner has detected definite fraud in the website at "www.dropbox.com". Do not trust this website: MailScanner has detected definite fraud in the website at "www.dropbox.com". Do not trust this website:**_ https://www.dropbox.com/s/oiereowirqhjwor/euhroiquhroiue.zip?dl=0
 
A bit of a facepalm for me, as you're giving ordinary people really fierce and 'definite' warnings about nothing.

To give you as much info as I can, the file on Dropbox was a Zip file containing:
- PHP source code (Ghost CMS)
- A MySQL export (Ghost CMS)
- JavaScript source code (Ghost CMS)
- A Postgres export (Discourse forum)
- A Redis export (Discourse forum)

**Comment by shawniverson** [comment]
@jorisw Is "www.dropbox.com" or "dropbox.com" showing in your /etc/MailScanner/phishing.bad.sites.conf or /etc/MailScanner/phishing.bad.sites.custom ?

**Comment by shawniverson** [comment]
So far I cannot reproduce with the latest Phishtank rulesets....can anyone confirm this?

**Comment by jorisw** [comment]
I'm sorry to say I am not the owner of the server. I am quoting from a mail thread with my business peers.

**Comment by shawniverson** [comment]
@jorisw Please let who is in control of the server know that they can add dropbox.com to /etc/MailScanner/phishing.safe.sites.custom to permanently whitelist dropbox.com and then run /usr/sbin/ms-update-phishing as root.
