### ISSUE TITLE
ClamDScan incorrectly thinking whole message is infected

### ISSUE THREAD

**Issue by jcbenton** [MailScanner/v5#3]
_From @ShaneOfMacquarie on April 7, 2016 3:59_

I was receiving blank message bodies after enabling clamd's OLE2BlockMacros option and adding 'Heuristics.OLE2.ContainsMacros' to the 'Non-Forging Viruses' MailScanner option. I tracked it down to having the 'ClamAV Full Message Scan' option set to yes and noted that the logs showed 2 lots of infection for the single attachment. Expected behavior is similar to that of banned file-names - recipient receives a cleaned message, with body intact, along with an attachment removed notice.

Setting 'ClamAV Full Message Scan' to no fixes the problem, but I suspect this is not the intended behavior and may have a wider impact. Could there be a bug in SweepViruses.pm sub ClamdScan() - lines 2043-2050 that is incorrectly flagging an infection outside of message headers as afflicting the whole message and not just the infected attachment?

I'm hoping someone familiar with the code can comment. Without knowing where header and message come from, I'm thinking '|message' might be an issue?:

```
  if ($childname =~ /\.(?:header|message)$/ && $filename =~ /\sFOUND$/) {
    $rest = $filename;
    $filename = '';
    $childname =~ s/\.(?:header|message)$//;
```

_Copied from original issue: MailScanner/v4#62_

**Comment by jcbenton** [comment]
Shane,

Would you be kind enough to post (copy and paste) this on the new v5 branch? 

https://github.com/MailScanner/v5/issues

**Comment by jcbenton** [comment]
Never mind. I was able to move this using an online tool.

**Comment by jcbenton** [comment]
Note to self: review this :)

**Comment by Schroeffu** [comment]
Is this issue still pending? I just added ClamAV with `OLE2BlockMacros true` but did not add them to Non-Forging viruses, 'cause all Makros can be silently dropped so far.

**Comment by shawniverson** [comment]
@Schroeffu Are you seeing any evidence that this issue is occurring?

**Comment by shawniverson** [comment]
@Schroeffu Thank you for the feedback.  I'm going to close this issue, then.
