### ISSUE TITLE
MailScanner upgrade resets ownership on /var/spool/MailScanner/ subdirectories

### ISSUE THREAD

**Issue by msapiro** [MailScanner/v5#308]
This is related to #88 but affects Debian.

The underlying issue is MailScanner checks that the owner of the `Incoming Queue Dir` and `Outgoing Queue Dir` directories is the `Run As User` if the `Run As User` is not `root` and dies if the check fails even if the `Run As User` has permission via its group.

In my case, the `Run As User` is `postfix` and the queue directories are `/var/spool/MailScanner/milterin` and `/var/spool/MailScanner/milterout`.

The problem is the Debian postinst script contains
```
# lock down some directory permissions
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/archive
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/incoming
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/quarantine
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/milterin
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/milterout
```
which unconditionally sets the owner of these directories to `mail` so every time I run an upgrade, I have to remember to change the ownership of these directories back to `postfix`.

It should be ok to change this code to something like
```
# lock down some directory permissions
runasuser="mail"
if [ -x /usr/sbin/ms-peek ]; then
    runasuser=`/usr/sbin/ms-peek runasuser /etc/MailScanner/MailScanner.conf`
fi
if [ -z $runasuser ]; then
    runasuser="mail"
fi
install -d -o$runasuser -gmtagroup -m0775 /var/spool/MailScanner/archive
install -d -o$runasuser -gmtagroup -m0775 /var/spool/MailScanner/incoming
install -d -o$runasuser -gmtagroup -m0775 /var/spool/MailScanner/quarantine
install -d -o$runasuser -gmtagroup -m0775 /var/spool/MailScanner/milterin
install -d -o$runasuser -gmtagroup -m0775 /var/spool/MailScanner/milterout
```

**Comment by shawniverson** [comment]
Looks reasonable to me :)

**Comment by msapiro** [comment]
Thanks Shawn. I had intended to actually test this and submit a PR, but you beat me to it. And I have now tested and as expected, it works as intended.
