### ISSUE TITLE
Bug in mailto: disarming

### ISSUE THREAD

**Issue by msapiro** [MailScanner/v5#320]
HTML like `<a href="mailto:mark@msapiro.net">mark@msapiro.net</a>` is accepted by MailScanner without disarming, but `<a href="mailto:mark@msapiro.net">&lt;mark@msapiro.net&gt;</a>` is disarmed as `<a href="mailto:mark@msapiro.net"><font color="red"><b>MailScanner has detected a possible fraud attempt from "msapiro.net" claiming to be</b></font>&lt;mark@msapiro.net@gt;</a>`.

I think MailScanner should ignore the `&lt;` and `&gt;` in this case.

**Comment by shawniverson** [comment]
@msapiro Good catch.  I'll add this tonight and test some more.
