### ISSUE TITLE
MailScanner_found_Cyrus_boundary_substring_problem

### ISSUE THREAD

**Issue by CyberCr33p** [MailScanner/v5#324]
Today I upgrade MailScanner from 5.0.7 to  5.1.2 and I found that e-mails sent from an OpenCart e-shop show "__MailScanner_found_Cyrus_boundary_substring_problem__" and the e-mail format is broken.

I see this issue is described here:

http://lists.mailscanner.info/pipermail/mailscanner/2003-May/013001.html

Here are the e-mail headers:

https://pastebin.com/raw/WzkJeDmG

I comment out the FixSubstringBoundaries line which resolve this issue.

I don't see any changes to SweepContent.pm between version 5.0.7 and 5.1.2.

Any idea why it happens after I upgrade to 5.1.2?

Is the FixSubstringBoundaries code still needed?

**Comment by endokard** [comment]
I've got the same problem with MS v 5.1.2 on CentOS.
There is free e-mail server online.ee and I've received empty messages from clients who used this service.
Commenting out FixSubstringBoundaries in SweepContent.pm helped me to solve this problem.

**Comment by CyberCr33p** [comment]
Did you notice the issue with version 5.1.2 or previous versions too?
