### ISSUE TITLE
error sending document file

### ISSUE THREAD

**Issue by isnaws** [MailScanner/v5#332]
Hi, I get a mailscanner issue, if we send a document file with a lot of content it is always considered a virus, but if we send an attachment document with a little content it works
For errors, a notification always appears as below
Quarantine: /var/spool/MailScanner/quarantine/20181215/7DA3310E555.A45B8
     Report: MailScanner: No programs allowed (oOle10Native_tmp)
     Report: MailScanner: No programs allowed (oOle10Native_tmp)

message message / rfc822; charset = us-ascii 20181215 / 7DA3310E555.A45B8 / message Y
oOle10Native_tmp application / octet-stream; charset = binary 20181215 / 7DA3310E555.A45B8 / oOle10Native_tmp Y
87oleObject2.bin Composite Document V2 Document file, No summary info; charset = binary 20181215 / 7DA3310E555.A45B8 / 87oleObject2.bin

can anyone help this problem

regards

**Comment by shawniverson** [comment]
@isnaws That is not a virus alert but rather a file type alert.  oOle10Native_tmp  appears to MailScanner to be an executable based on its content.

This rule is what is triggering the alert...
 /etc/MailScanner/filetype.rules.conf

```
deny    executable      No executables          No programs allowed
```

I have seen in some rare cases where outdated file packages (that provides /usr/bin/file and /usr/share/file/magic ) can cause false positives.
