### ISSUE TITLE
Long queue IDs in Postfix

### ISSUE THREAD

**Issue by alvarosplit** [MailScanner/v5#34]
Hi,

"Long queue IDs in Postfix #15" issue is closed but I've seen that Postfix can generate queue IDs longer than 15 chars (due the inode), so 2 regular expressions need to be changed:

Postfix.pm (line 280):

if ($file =~ /-[A-Za-z0-9]{15}.[A-Za-z0-9]{5}$/) {
if ($file =~ /-[A-Za-z0-9]{15,20}.[A-Za-z0-9]{5}$/) {
PFDiskStore.pm (line 90):

if ($this->{hdname} =~ /[A-Za-z0-9]{15}$/) {
if ($this->{hdname} =~ /[A-Za-z0-9]{15,20}$/) {
to support longer queue IDs.
I attach these 2 files modified.
[ms-patch3.tar.gz](https://github.com/MailScanner/v5/files/673133/ms-patch3.tar.gz)

**Comment by alvarosplit** [comment]
Hello,

I've seen two situations, that happen sometimes:
- microseconds variable is "0" (value get from gettimeofday function) 
- inode value is too small

I've one patch for these issues, but I'll test it for some days before upload it.

**Comment by jcbenton** [comment]
Please include the whole file when you do. I appreciate you doing all of this. 

-
Jerry Benton
www.mailborder.com
+1 - 844-436-6245

**Comment by alvarosplit** [comment]
Hi again,

I attach whole files with patches that I've been using for more than 2 weeks without problems.
[ms-patch4.tar.gz](https://github.com/MailScanner/v5/files/803287/ms-patch4.tar.gz)

**Comment by jcbenton** [comment]
Thank you. I have added it for the next version.
