### ISSUE TITLE
Mails are corrupted if attached file with non-Latin chars

### ISSUE THREAD

**Issue by endokard** [MailScanner/v5#340]
I'm using CentoOS 7 and MailScanner 5.1.2.
Recent fount one problem. If mails are sent with attachment which name contains non-latin chars e-mail content, after scanning, is broken and file name displays incorrectly in mail client (tested with outlook and zimbra).

1. Send mail with attachment named "проверка ошибки.pdf" .
2. In e-mail client I'v got  "Ð¿Ñ€Ð¾Ð²ÐµÑ€ÐºÐ° Ð¾ÑˆÐ¸Ð±ÐºÐ¸.pdf".

Analyzing e-mails I found following:

1.1. Part of mail before scanning:
`----ALT--DTlQVUQENGFlQCQ3hSbd7Y5Te2B6zZZJ1545568192--`
`------DTlQVUQENGFlQCQ3hSbd7Y5Te2B6zZZJ-FZT0IGsVCKP1gvKm-1545568192`
`Content-Type: application/pdf; name="=?UTF-8?B?0L/RgNC+0LLQtdGA0LrQsCDQvtGI0LjQsdC60LgucGRm?="`
`Content-Disposition: attachment; filename="=?UTF-8?B?0L/RgNC+0LLQtdGA0LrQsCDQvtGI0LjQsdC60LgucGRm?="`
`Content-Transfer-Encoding:base64`

`JVBERi0xLjQNCiXi48/TDQoxIDAgb2JqDQo8PA0KL0YwMTAxIDIgMCBSDQov`

2.1. Part of mail after scanning:
`----ALT--DTlQVUQENGFlQCQ3hSbd7Y5Te2B6zZZJ1545568192--`
`------DTlQVUQENGFlQCQ3hSbd7Y5Te2B6zZZJ-FZT0IGsVCKP1gvKm-1545568192`
`Content-Type: application/pdf; name="ذ؟ر€ذ¾ذ²ذµر€ذ؛ذ° ذ¾رˆذ¸ذ±ذ؛ذ¸.pdf"`
`Content-Disposition: attachment; filename="ذ؟ر€ذ¾ذ²ذµر€ذ؛ذ° ذ¾رˆذ¸ذ±ذ؛ذ¸.pdf"`
`Content-Transfer-Encoding: base64`

`JVBERi0xLjQNCiXi48/TDQoxIDAgb2JqDQo8PA0KL0YwMTAxIDIgMCBSDQov`

I've checked with and without spaces in different languages with same result.

**Comment by shawniverson** [comment]
Previously resolved in commit https://github.com/MailScanner/v5/commit/72c137861a55421129f08c4e42b9983b394120ba

**Comment by endokard** [comment]
Thank you, after changes all attachment displays correctly.
