### ISSUE TITLE
ConfigDefs.pl not being parsed when using ms-peek

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#346]
https://github.com/mailwatch/MailWatch/issues/1121

**Comment by msapiro** [comment]
@shawniverson I've looked at mailwatch/MailWatch#1121, and I don't completely follow it, but I don't understand why ms-peek should look at the defaults in ConfigDefs.pl. Every setting should be in MailScanner.conf for documentation if nothing else, and I believe they all are.

The thread in mailwatch/MailWatch#1121 talks about doing
```
/usr/sbin/ms-peek quarantinesilent ~/MailScanner.conf
```
but `quarantinesilent` is not a configuration setting. It is just an internal name for the `Quarantine Silent Viruses` setting.

**Comment by shawniverson** [comment]
@msapiro Thank you for clarifying, then that means I was not using ms-peek properly and will close this issue.
