### ISSUE TITLE
sophos scanner found virus, mailscanner not

### ISSUE THREAD

**Issue by Oppilif** [MailScanner/v5#358]
Mailscanner looses the pointer of Sophos messages and cannot see if a message contains a virus.
MailScanner 5.1.2-2 - Centos 6.9
Clamav don't find viruses. Sophos does but cannot stop infected messages.

Jan 24 16:10:36 server MailScanner[22335]: >>> Virus 'Mal/DrodAce-A' found in file /var/pool/MailScanner/incoming/22335/x0OFAQRd022738/nFedEx EXPRESS ONLINE DELIVERY REPORT.ace
Jan 24 16:10:36 server MailScanner[22335]: Virus Scanning: Sophos found 1 infections
Jan 24 16:10:36 server MailScanner[22335]: Infected message var came from 
Jan 24 16:10:36 server MailScanner[22335]: Virus Scanning: Found 1 viruses

as you can see MailScanner wrote "Infected message var came from " instead of "message 1 from a.b.c.d" and the variable virusinfected remain with value 0.

Anyone has the same problem?

The error is in SweepViruses.pm but I have no idea how to stop it.

Filippo

**Comment by shawniverson** [comment]
See PR https://github.com/MailScanner/v5/pull/353

**Comment by Oppilif** [comment]
cannot find the change to made... can you wrap up it here? )
