### ISSUE TITLE
possible fraud attempt from "bugzilla.gnome.org"

### ISSUE THREAD

**Issue by nerijus** [MailScanner/v5#366]
I got email from gnome bugzilla, where a link
```
https://bugzilla.gnome.org/page.cgi?id=describeuser.html&login=1d28ed33%40opayq.com
```
is detected as
```
MailScanner has detected a possible fraud attempt from "bugzilla.gnome.org" claiming to be 1d28ed33@opayq.com
```
Some time later I got another email with a link
```
https://bugzilla.gnome.org/page.cgi?id=describeuser.html&login=chpe%40gnome.org
```
but this time link was not detected as fraud. I can provide raw message bodies if needed.

**Comment by nerijus** [comment]
Ah, 2nd time it was not fraud because domain (gnome.org) is the same. But the 1st case should be fixed.

**Comment by msapiro** [comment]
@nerijus What MailScanner version is this?
What did the actual HTML look like?

I have tested with MailScanner-5.1.3-2 and both
```
<a href="https://bugzilla.gnome.org/page.cgi?id=describeuser.html&login=1d28ed33%40opayq.com">hi</a>
```
and
```
<a href="https://bugzilla.gnome.org/page.cgi?id=describeuser.html&login=1d28ed33@opayq.com">hi</a>
```
and neither of these is detected as possible fraud.

**Comment by nerijus** [comment]
5.1.3-1. I have not yet updated to 5.1.3-2. HTML is:
```
              from <span class=3D"vcard"><a href=3D"page.cgi?id=3Ddescribeu=
ser.html&login=3D1d28ed33%40opayq.com" title=3D"1d28ed33&#64;opayq.com"><fo=
nt color=3D"red"><b>MailScanner has detected a possible fraud attempt from =
"bugzilla.gnome.org" claiming to be</b></font> 1d28ed33&#64;opayq.com</a>
</span></b>
        <pre><span class=3D"quote">&gt; Have you enabled bracketed paste mo=
de in bash?</span >
```

**Comment by nerijus** [comment]
2nd:
```
              from <span class=3D"vcard"><a href=3D"page.cgi?id=3Ddescribeu=
ser.html&login=3Dchpe%40gnome.org" title=3D"Christian Persch &lt;chpe&#64;g=
nome.org&gt;"> <span class=3D"fn">Christian Persch</span></a>
</span></b>
```

**Comment by msapiro** [comment]
The HTML at https://github.com/MailScanner/v5/issues/366#issuecomment-462634828 appears to be correctly flagged by MailScanner. It looks like the original anchor tag before MailScanner (decoded and made absolute) is
```
 <a href="https://bugzilla.gnome.org/page.cgi?id=describeuser.html&login=1d28ed33@opayq.com" title="1d28ed33@opayq.com">1d28ed33@opayq.com</a>
```
It is not flagged because of the `login=1d28ed33@opayq.com` fragment. It is flagged because the display text is `1d28ed33@opayq.com`.

Likewise, the HTML at https://github.com/MailScanner/v5/issues/366#issuecomment-462638333 passes not because the domain in the `login=chpe@gnome.org` fragment is `gnome.org`, but rather because the display text is `Christian Persch` which does not look like a domain.

**Comment by nerijus** [comment]
In 2nd case roundcube displays as:
```
Christian Persch <chpe@gnome.org>
```
But yes, you are correct about the 1st case. Will the warning be disabled if I set "Highlight Mailto Phishing = no" in 5.1.3-2?

**Comment by shawniverson** [comment]
@nerijus No, because it is a reference to a web url but is being displayed as an email address, neither of which are using mailto: .

**Comment by nerijus** [comment]
I updated to 5.1.3-2 and set "Highlight Mailto Phishing = no", got another email and it was not flagged:
```
              from <span class=3D"vcard"><a href=3D"page.cgi?id=3Ddescribeu=
ser.html&login=3D1d28ed33%40opayq.com" title=3D"1d28ed33&#64;opayq.com">1d2=
8ed33&#64;opayq.com</a>
</span></b>
```

**Comment by msapiro** [comment]
The link in https://github.com/MailScanner/v5/issues/366#issuecomment-462867120 was disarmed in my tests regardless of the setting of "Highlight Mailto Phishing"
