### ISSUE TITLE
Default SMTP HELO value hardcoded

### ISSUE THREAD

**Issue by primerpop** [MailScanner/v5#37]
When releasing a quarantined message, a message indicating that the email could not be queue is shown, rejected on the fact that "localhost" is not an FQDN.

Within /lib/pear/Mail/smtp.php there are a number of hard-coded "localhost" values.  

Ideally, these values should be populated from the actual host configuration, perhaps even trying to resolve them via gethostbyname() or via configuration.

**Comment by msapiro** [comment]
Why is this a MailScanner issue? It appears to be an issue with the pear Mail package https://pear.php.net/package/Mail or possibly MailWatch?

**Comment by primerpop** [comment]
If mailscanner pushed in a Mail_smtp->localhost value ahead of using the library, it would work.  Pear Mail really wouldn't give two craps how you use it, but give you an option to configure it.  

Your call, just trying to improve your product, but if you're going to be contrarian, I can't help that either.  Close if you want, I have no dog in this hunt.

**Comment by msapiro** [comment]
I'm not trying to be contrarian. I'm just trying to understand where, if anywhere, in MailScanner this issue arises. I think MailScanner itself has no facility for releasing quarantined messages. This is a function of something else like MailWatch or MailBorder or??

**Comment by jcbenton** [comment]
MailScanner does not use PHP. This is a MailWatch issue.
