### ISSUE TITLE
"External" notification at top of message

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#375]
Opening for discussion.  Good idea/bad idea?  It is doable, interested in feedback.

**Comment by msapiro** [comment]
I would not me interested in this. It is just one more way that MailScanner can break DKIM signatures, and if I understand, it might be interesting to organizations that do a lot of internal communication by email, but that's not me.

I suppose there would be a setting to control it, in which case if it defaulted to No, I wouldn't object, but I can't see a situation where I would turn it on.

**Comment by shawniverson** [comment]
@msapiro Agreed.  It would have to be a setting/ruleset, similar to the appending of message signatures, and I would concur on making it defaulted to No.

**Comment by shawniverson** [comment]
I'll keep this open for few more days for feedback, but unless someone else chimes in, I'm not going to put forth effort to implement this, at least not right now.

**Comment by spec1re** [comment]
I like the idea a lot, but where and how would you define a mail as external? Maybe a list of domains and IPs in a ruleset?

**Comment by shawniverson** [comment]
@spec1re yes it would need to be a ruleset
