### ISSUE TITLE
Always Looked Up Last triggers even though message batch was abandoned

### ISSUE THREAD

**Issue by DaSpawn** [MailScanner/v5#377]
I utilize "Always Looked Up Last" for MailWatchLogging and recently noticed a problem with messages being logged multiple times to the DB even though they were not actually delivered

Come to find out the virus scanner (clamav) happens to be loading/restarting and during that time causes MailScanner to thrown an error (as expected and as it should):

```Cannot find Socket (/var/run/clamav/clamd.ctl) Exiting!```
```Virus Scanning: No virus scanners worked, so message batch was abandoned and retried!```

Unfortunately every time it tries to process the pending messages it logs all of the pending messages to the database since even the failures trigger "Always Looked Up Last"  (I had a sudden increase of 15K emails today and had a heart attack..  it was 14,995 duplicate logged messages)

How can I prevent the "Always Looked Up Last" from triggering?  Is it possible to can catch the errors in the perl module so I can skip logging there?

**Comment by shawniverson** [comment]
@DaSpawn What version of MailScanner are you using?

**Comment by DaSpawn** [comment]
MailScanner version 5.0.3 (I did not realize it was not being updated via apt, I will update now and test again)

**Comment by DaSpawn** [comment]
I am now running 5.1.3 and still see the same problem

**Comment by shawniverson** [comment]
@DaSpawn Interesting.  You should see MailScanner going into a holding pattern (with that retry message repeating every second or two in the mail log while virus scanning is down) instead of the repeat logging to the database.  Here's the commit that should have changed the behavior.

https://github.com/MailScanner/v5/commit/4aeacbb529e25eb5e6a81d486cb07fe14ddb209c

**Comment by DaSpawn** [comment]
Looks like https://github.com/MailScanner/v5/blob/05e1a6d0a3d64b38fe9c2037b68cc54e92bdd1c7/common/usr/sbin/MailScanner#L1314 is able to have access to the original messages even though DropBatch empties the messages hash...  I am not following the magic happening there...

**Comment by shawniverson** [comment]
@DaSpawn I will run some tests and see if I can get some more insight...

**Comment by shawniverson** [comment]
Having trouble triggering logging with the following...

MailScanner 5.1.3-2
Clamd

```
md.sock) Exiting!
Jun 16 20:01:14 scanner MailScanner[3410]: Virus Scanning: No virus scanners worked, so message batch will be tried again
Jun 16 20:01:16 scanner MailScanner[13832]: Cannot find Socket (/var/run/clamd.socket/clamd.sock) Exiting!
Jun 16 20:01:16 scanner MailScanner[31188]: Virus Scanning: No virus scanners worked, so message batch will be tried again
Jun 16 20:01:19 scanner MailScanner[13833]: Cannot find Socket (/var/run/clamd.socket/clamd.sock) Exiting!
Jun 16 20:01:19 scanner MailScanner[13834]: Cannot find Socket (/var/run/clamd.socket/clamd.sock) Exiting!
Jun 16 20:01:19 scanner MailScanner[3572]: Virus Scanning: No virus scanners worked, so message batch will be tried again
Jun 16 20:01:19 scanner MailScanner[641]: Virus Scanning: No virus scanners worked, so message batch will be tried again
```

Nothing is being logged on my instance when clamd is down, it is looping as expected.  Anyone who can shed some light on this and is having the issue would be much appreciated.

```
Always Looked Up Last = &MailWatchLogging
Virus Scanners = clamd
```

**Comment by shawniverson** [comment]
Still having trouble reproducing, if still having issues, please let me know.

**Comment by janarzz** [comment]
Hey, same problem here.
Mailscanner 5.3.3
