### ISSUE TITLE
scanning virus messages also for SPAM

### ISSUE THREAD

**Issue by funtomko** [MailScanner/v5#384]
Hello,

I would like to ask if is possible to configure mailscanner that emails containing the viruses would be also checked by spamassasin to get some score.
We have set  in mailscanner.conf:  `Still Deliver Silent Viruses = yes` because we have turned on in clamd.conf `OLE2BlockMacros yes` so each mail with macro attachment should be delivered. But some of these are only SPAM or real viruses and we need to scan them by spamassain too.

Thank you.

MailWatch Version: 1.2.8, Operating System Version: CentOS Linux 7 (Core), Postfix Version: 2.10.1,PHP Version: 5.4.16, MySQL Version: 5.5.56-MariaDB.

BR,
Tomas

**Comment by shawniverson** [comment]
This was one of my old problems with MailScanner myself quite a while back.

**Comment by funtomko** [comment]
@shawniverson Did you solve it somehow?

**Comment by shawniverson** [comment]
@funtomko No, but I'm thinking we need a code change to allow for a rule.

**Comment by shawniverson** [comment]
Tracing code...PR pending...
