### ISSUE TITLE
Latest WHM upgrade not compatible

### ISSUE THREAD

**Issue by dmb1416** [MailScanner/v5#39]
Latest WHM/Cpanel upgrade has caused all outbound emails to show "Unknown" recipients and not send. After disabling MailScanner, emails can once again be sent.

**Comment by msapiro** [comment]
Have you contacted cPanel about this?

What happens to the messages? Do they just sit in some Exim outbound queue with no recipients? What are the Exim and MailScanner log messages? In an Exim configuration with MailScanner, there are normally two Exim processes one receives mail and queues it for MailScanner. MailScanner then picks up the message, scans it and requeues it for the other Exim which sends it. See https://www.mailscanner.info/exim/.

It's hard to know what might have changed without more information.

**Comment by dmb1416** [comment]
I have opened tickets with Cpanel and Configserver Mail Manager (the MailScanner interface we use). Cpanel had 200 tickets ahead of mine and hasnt responded yet, and ConfigServer says it's a PERL upgrade cpanel performed and a simple restart would fix, but it didn't fix.

Get Outlook for Android<https://aka.ms/ghei36>




On Tue, Jan 31, 2017 at 5:29 PM -0600, "Mark Sapiro" <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you contacted cPanel about this?

What happens to the messages? Do they just sit in some Exim outbound queue with no recipients? What are the Exim and MailScanner log messages? In an Exim configuration with MailScanner, there are normally two Exim processes one receives mail and queues it for MailScanner. MailScanner then picks up the message, scans it and requeues it for the other Exim which sends it. See https://www.mailscanner.info/exim/.

It's hard to know what might have changed without more information.

**Comment by dmb1416** [comment]
Jan 31 10:01:39 a243 MailScanner: MailScanner Email Processor version 5.0.2 starting...
Jan 31 10:01:39 a243 MailScanner: MailScanner Email Processor version 5.0.2 starting...
Jan 31 10:01:39 a243 MailScanner: Could not use Custom Function code /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Can't locate Storable.pm in @INC (you may need to install the Storable module) (@INC contains: /usr/mailscanner/usr/sbin /usr/mailscanner/usr/sbin/MailScanner /usr/mailscanner/usr/share/MailScanner/perl  /usr/mailscanner/usr/share/MailScanner/perl /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1 /opt/cpanel/perl5/522/site_lib/x86_64-linux-64int /opt/cpanel/perl5/522/site_lib) at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:39 a243 MailScanner: Could not use Custom Function code /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Can't locate Storable.pm in @INC (you may need to install the Storable module) (@INC contains: /usr/mailscanner/usr/sbin /usr/mailscanner/usr/sbin/MailScanner /usr/mailscanner/usr/share/MailScanner/perl  /usr/mailscanner/usr/share/MailScanner/perl /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1 /opt/cpanel/perl5/522/site_lib/x86_64-linux-64int /opt/cpanel/perl5/522/site_lib) at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:39 a243 MailScanner: BEGIN failed--compilation aborted at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:39 a243 MailScanner: BEGIN failed--compilation aborted at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:39 a243 MailScanner: Compilation failed in require at /usr/mailscanner/usr/share/MailScanner/perl/MailScanner/Config.pm line 761.
Jan 31 10:01:39 a243 MailScanner: Compilation failed in require at /usr/mailscanner/usr/share/MailScanner/perl/MailScanner/Config.pm line 761.
Jan 31 10:01:39 a243 MailScanner: )
Jan 31 10:01:39 a243 MailScanner: )
Jan 31 10:01:39 a243 MailScanner: Reading configuration file /usr/mailscanner/etc/MailScanner.conf
Jan 31 10:01:39 a243 MailScanner: Reading configuration file /usr/mailscanner/etc/MailScanner.conf
Jan 31 10:01:39 a243 MailScanner: Reading configuration file /usr/mailscanner/etc/conf.d/README
Jan 31 10:01:39 a243 MailScanner: Reading configuration file /usr/mailscanner/etc/conf.d/README
Jan 31 10:01:39 a243 MailScanner: Config: calling custom init function MailControlLogging
Jan 31 10:01:39 a243 MailScanner: Config: calling custom init function MailControlLogging
Jan 31 10:01:39 a243 MailScanner: You want to use SpamAssassin but have not installed it.
Jan 31 10:01:39 a243 MailScanner: You want to use SpamAssassin but have not installed it.
Jan 31 10:01:39 a243 MailScanner: I will run without SpamAssassin for now, you will not detect much spam until you install SpamAssassin.
Jan 31 10:01:39 a243 MailScanner: I will run without SpamAssassin for now, you will not detect much spam until you install SpamAssassin.
Jan 31 10:01:39 a243 MailScanner: Started MailControl MySQL process
Jan 31 10:01:39 a243 MailScanner: Started MailControl MySQL process
Jan 31 10:01:40 a243 MailScanner: Started MailControl MySQL process
Jan 31 10:01:40 a243 MailScanner: Started MailControl MySQL process
Jan 31 10:01:41 a243 MailScanner: MailScanner Email Processor version 5.0.2 starting...
Jan 31 10:01:41 a243 MailScanner: MailScanner Email Processor version 5.0.2 starting...
Jan 31 10:01:41 a243 MailScanner: Could not use Custom Function code /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Can't locate Storable.pm in @INC (you may need to install the Storable module) (@INC contains: /usr/mailscanner/usr/sbin /usr/mailscanner/usr/sbin/MailScanner /usr/mailscanner/usr/share/MailScanner/perl  /usr/mailscanner/usr/share/MailScanner/perl /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1 /opt/cpanel/perl5/522/site_lib/x86_64-linux-64int /opt/cpanel/perl5/522/site_lib) at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:41 a243 MailScanner: Could not use Custom Function code /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Can't locate Storable.pm in @INC (you may need to install the Storable module) (@INC contains: /usr/mailscanner/usr/sbin /usr/mailscanner/usr/sbin/MailScanner /usr/mailscanner/usr/share/MailScanner/perl  /usr/mailscanner/usr/share/MailScanner/perl /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1 /opt/cpanel/perl5/522/site_lib/x86_64-linux-64int /opt/cpanel/perl5/522/site_lib) at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:41 a243 MailScanner: BEGIN failed--compilation aborted at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:41 a243 MailScanner: BEGIN failed--compilation aborted at /usr/mailscanner/usr/share/MailScanner/perl/custom/MailControl.pm line 5.
Jan 31 10:01:41 a243 MailScanner: Compilation failed in require at /usr/mailscanner/usr/share/MailScanner/perl/MailScanner/Config.pm line 761.
Jan 31 10:01:41 a243 MailScanner: Compilation failed in require at /usr/mailscanner/usr/share/MailScanner/perl/MailScanner/Config.pm line 761.
Jan 31 10:01:41 a243 MailScanner: )
Jan 31 10:01:41 a243 MailScanner: )

**Comment by msapiro** [comment]
So the issue appears to be with the MailControl.pm custom function installed in MailScanner (something from Configserver Mail Manager which you mention above?). It looks like it requires something named Storable which is not available. You might try installing it from cpan, e.g. 'cpan -i Storable'.

**Comment by dmb1416** [comment]
that worked. thanks
