### ISSUE TITLE
Malicious ISO/UDF Containers

### ISSUE THREAD

**Issue by rickyboone** [MailScanner/v5#395]
MailScanner doesn't appear to extract the contents of ISO/UDF image files (at least the one I'm testing against).

The mail log shows the following events in this example:

Jul 10 00:56:02 mailscanner1 MailScanner[557]: Filename Checks: Allowing A205E20E8651.AE858 PO#LP907_pdf.img (no rule matched)
Jul 10 00:56:02 mailscanner1 MailScanner[557]: Filetype Checks: Allowing A205E20E8651.AE858 PO#LP907_pdf.img (no match found)
Jul 10 00:56:02 mailscanner1 MailScanner[557]: Filetype Mime Checks: Allowing A205E20E8651.AE858 PO#LP907_pdf.img (no match found)

The file in question has the "application/x-iso9660-image" mimetype (file -i).  Extracting the file with 7z is successful if I run it manually.

I'm not sure about the logic of when MailScanner or otherwise chooses to extract the contents of a file.  For the time being, I'm using filetype rules to get around the issue, but I think this may need attention.

The system I'm running this on is running MailScanner 5.1.2 (not current, but haven't had time to update to the latest yet).

I can't submit the file I'm testing with to this issue, as it actually contains malware, but here's a link to the sandbox I ran to analyze it.

https://app.any.run/tasks/94e1942d-a8a8-4deb-adfb-f27cf6a6b0c8

**Comment by shawniverson** [comment]
Most iso files are too large to extract and will be bypassed, but I suspect that malicious ones may be fairly small, so it should be trivial to inform 7zip to examine small iso files for malicious contents.

**Comment by rickyboone** [comment]
Yep, in this case, the ISO file was only about 1400 KB, so I'm not sure what practical limits should be imposed.  

More details on the ISO file can be found here:

https://www.virustotal.com/gui/file/d2817380e54db88e9fc6af3ca663733a27ef5e8508fa9417c4b30ab7ecc2de21/details

Additionally, here's an article from SANS regarding this trend of malware distribution:

https://isc.sans.edu/diary/Malware+Sample+Delivered+Through+UDF+Image/24854
