### ISSUE TITLE
Highlight Hidden URLs - documentation

### ISSUE THREAD

**Issue by asuweb** [MailScanner/v5#398]
Some welcome new features and refactoring with mailscanner - good work!

Can you explain the purpose of this function?

Highlight Hidden URLs

It doens't appear to work as I assume it should.

I assume it is supposed to highlight links of the from `click here to view` however on test emails, it's not working in that fashion.  So maybe I misunderstood the purpose of it. 

Clarification appreciated.

Many thanks,

**Comment by shawniverson** [comment]
I'm having trouble as well.  Appears to be wrong logic in Message.pm for this feature.

**Comment by shawniverson** [comment]
Flag for disarming not being set when nothing else besides the hidden url is also disarmed.

**Comment by asuweb** [comment]
Excellent, I'll test it out now

**Comment by asuweb** [comment]
It does now highlight hidden links, but I think there is some logic not quite right.

Here's the output I get now on a test mail

![image](https://user-images.githubusercontent.com/13250955/61380584-8967e800-a8a1-11e9-9d6e-b4277019d85a.png)

It looks to me like it's printing the hidden link twice, and also detecting the fraud(phishing) link as a hidden link.

**Comment by shawniverson** [comment]
@asuweb Yeah, I'm refactoring right at the moment.  It needs reworked.

**Comment by asuweb** [comment]
@shawniverson - there's another issue here as well.  It's not adhering to rulesets.  

I enabled it only for my domain for testing but it's affecting all user and all domains...

**Comment by shawniverson** [comment]
Heavily refactored, please test PR.

**Comment by asuweb** [comment]
@shawniverson - I'll test this soon.

Have you also noticed the issue with rules not being applied in this instance?  It may be the way I've configured it but I think it should work

**Comment by shawniverson** [comment]
@asuweb I fixed that too.

**Comment by asuweb** [comment]
@shawniverson - I can confirm the rules bug is fixed. 

The phishing detection is much better but not quite right.

It now correctly prints only one line for a url which is disguised, but for the case of a hidden url, it just deletes the line, rather than highlighting it.

**Comment by shawniverson** [comment]
Getting closer...I'll run some more tests.

**Comment by asuweb** [comment]
It also seems to print a newline after every line whether it modifies it or not.  But getting closer

**Comment by shawniverson** [comment]
Still working on this...just really busy time of year...

**Comment by shawniverson** [comment]
Give it another try, I made some updates to the PR.

**Comment by shawniverson** [comment]
Found a couple issues, going to refactor some more.  Multiple passes altering message...

**Comment by shawniverson** [comment]
@asuweb Ready to try again.  My tests appear to be working.

**Comment by asuweb** [comment]
@shawniverson - I'll check it out this week :)
