### ISSUE TITLE
Denial Of Service Attack Messages

### ISSUE THREAD

**Issue by jcbenton** [MailScanner/v5#4]
_From @sjardine on March 7, 2016 16:19_

I upgraded MailScanner several months ago to v4.85.2-3 and now v4.86.1-1.  Often I am getting the error message:

> MailScanner was attacked by a Denial Of Service attack, and has therefore deleted this part of the message. Please contact your e-mail providers for more information if you need it, giving them the whole of this report. Attack in: /var/spool/MailScanner/incoming/20499/u27Em5eK000564/nmsg-20499-47.html

The file reported in the attack is not there so I am unable to to any troubleshooting.

I am using a OpenVZ container with Ubuntu 6 CPUs and 12GB RAM.  The messages are causing problems with valid mail messages both incoming and outgoing.

Is there a way to disable this feature?

_Copied from original issue: MailScanner/v4#54_

**Comment by jcbenton** [comment]
Send this issue to the mailing list. At first look it seems to be a configuration issue. 

http://lists.mailscanner.info/listinfo/mailscanner

**Comment by jcbenton** [comment]
_From @sjardine on April 19, 2016 16:2_

Yeah.  I already did.

http://lists.mailscanner.info/pipermail/mailscanner/2016-March/103186.html

Is there a settings that need to be changed?  I have disabled Dangerous Content Scanning for now but would like to re-enable it as soon as possible.

Thanks!

**Comment by jcbenton** [comment]
Would you be kind enaough to post this to the v5 branch? We are not ignoring you. We have been focusing on v5. I want to address this issue in v5. 

https://github.com/MailScanner/v5/issues

**Comment by jcbenton** [comment]
Never mind. I was able to move it using an online tool.

**Comment by giosh94mhz** [comment]
Duplicate of https://github.com/MailScanner/v4/pull/55 ?

**Comment by jcbenton** [comment]
No. I moved the issues from v4 to v5. 

-
Jerry Benton
www.mailborder.com

**Comment by mmgomess** [comment]
Hi Jerry.

I am getting the same error message. Any news?

I´m using 5.0.3.7 version.

Marcelo Gomes

**Comment by branko77** [comment]
I am getting same thing over here... I´m using 5.0.3.7 version as well

**Comment by branko77** [comment]
For everyone that have this problem check this https://github.com/mailwatch/1.2.0/issues/430

**Comment by jcbenton** [comment]
This has been open for a year, but I do still plan on testing this in v5.0.5. I have seen it before, but I cannot manually duplicate it. :(

**Comment by sjardine** [comment]
I can confirm this is still an issue.  It is definitely a permissions problem but why it works sometimes and not others is a mystery to me.  I have disabled Dangerous Content Scanning.

**Comment by jcbenton** [comment]
Ok, I will do testing with the new build.

**Comment by giosh94mhz** [comment]
@jcbenton I'm using my patch for a while now, and I can confirm that I haven't loose any mail content since then. But the patch is just for "not loosing" content, not for "fixing" the DOS.

AFAIK, the permission issue happens because mailscanner is filled with "reset umask" commands, and I've managed to fix the whole problem (for postfix at least), in a not so smart way: setting the umask before/after every command which could write something and resetting permissions when needed.

I'll try to open a PR ASAP, but in the meanwhile I think you could easily test https://github.com/MailScanner/v4/pull/55 as a prerequisite :)

**Comment by gordoncolyn** [comment]
Hi,

I am getting the same errors.  I picked up the errors were really bad when my VM started using the swap file.  Maybe a memory problem.  Is there any fix for this?  I ahve disabled Dangerous Content scanning but that is obviously not ideal.

Server
Centos 6.9
MailScanner 5.0.3
Clamd 0.99.2
Spamassassin 3.3.1
Postfix 2.2.3

**Comment by shawniverson** [comment]
@gordoncolyn How much or little memory are we talking about here?  OOM is a definite cause.  If you don't have enough memory and are saturating the swap file, that would cause this.

**Comment by gordoncolyn** [comment]
I have 6gb of physical memory allocated with mailscanner setup to use 4gb alloacted to tempfs for /var/spool/MailScanner/incoming

**Comment by branko77** [comment]
I am having this on my server for a month or so... I don't think it is memory issue since my server is PowerEdge R720 with 32GB of RAM... I was forced to shut down MailWatch since it crashed several times with that Denial of Service attack and it is not secure for me to use it...

**Comment by shawniverson** [comment]
@gordoncolyn Then you only have 2gb of usable memory, which would be an issue.  Why such a large incoming ramdisk?

**Comment by shawniverson** [comment]
@branko77 Your issue is probably MailWatch related.  There are multiple reasons why this message appears.  See https://github.com/mailwatch/MailWatch/issues/430

**Comment by branko77** [comment]
Last post on that thread that you are referring to, is my post in which I
say that there is no resolution what so ever, or I was unable to find one
despite of help from other members...

**Comment by shawniverson** [comment]
@branko77 "I was forced to shut down MailWatch since it crashed several times with that Denial of Service attack and it is not secure for me to use it..."

So the problem went away after doing this?  Or is the problem still present with just MailScanner running?

**Comment by branko77** [comment]
Problem is still present so I am using MailScanner without MailWatch. Still having anti spam protection but sadly no MailWatch interface...

**Comment by shawniverson** [comment]
@branko77 So are you saying that problem is still happening, even without MailWatch?  I'm still not clear on that.  If MailScanner is not throwing the DOS error without MailWatch present, this is not a MailScanner issue.  It is clearly a MailWatch issue causing the forked process to die in that case.

**Comment by branko77** [comment]
No, maybe I wasn't clear enough. Problem is not happening without MailWatch. it is definitely not an MailScanner issue. When I turn of MailWatch everything works fine.
