### ISSUE TITLE
Check for available disk space is way too strict

### ISSUE THREAD

**Issue by giosh94mhz** [MailScanner/v5#40]
I recently found issue with MailScanner filling the whole incoming ramdisk and then failing because some other plugin/service died miserably.

I noticed that at [line 2518 of Message.pm](https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Message.pm#L2518) I found this:
```perl
  # Check we haven't filled the disk. Remove this message if we have, so
  # that we can continue processing the other messages.
  my $dir = MailScanner::Config::Value("incomingworkdir");
  my $df  = df($dir, 1024);
  if ($df) {
    my $freek = $df->{bavail};
    if (defined($freek) && $freek<100 && $freek>=0) {
      MailScanner::Log::WarnLog("Message %s is too big for available disk space in %s, skipping it", $this->{id}, $dir);
      my @toclear = ( $this->{id} );
      $workarea->ClearIds(\@toclear); # Delete attachments we might have made
      $this->DropFromBatch();
      return;
    }
}
```

Note that is tests for ` $freek<100`... well, 100k are not enough for almost every system out there. This to `tmpfs` ram disk or high reallocation of SSD.

This should be something like 10% of the disk, or at least something like 100m, not 100k.

What do you think?

**Comment by jcbenton** [comment]
This says if there is less than 100k left on the working directory, stop what you are doing. This is for your incoming work directory, not the whole drive. I can make it bigger, but what's the difference? If you are going to run out of space at 100k, 1024k, 10m, or 100m?  Most email is under 100k, so there is room left to process it.

**Comment by giosh94mhz** [comment]
Well, yes and no. It is true that many emails are small, but not really below 100k. I'm plenty of users which have (awful) inline signatures far above 100k

The problem here this: why fill up all the memory leaving only as small as 100k free, only to probably die the first time you do pretty much everything else on disk?

Think  about other mailscanner processes running. You are in the middle of "something" you, or a library on your behalf, write a very small file on disk and it fails, only because another process filled all the space on disk only to know it didn't have space. This check is for memory _below_ 100k, but if you are writing in small block of 64k to disk from two process, this is a disaster.

In my experience, when a process filled up the memory, all the other one were dying for out of memory one way or another.

I used 100m, but this may be something big that's ok for me. IMO 10m is the minimal: absolutely nothing for RAM or Disk, but huge for normal program usage and email analysis, since email are usually below 1M. More reliability, for just 10m.

If we feel uncomfortable with an hardcoded value, we can think about a configuration option, but... another one? :)

**Comment by jcbenton** [comment]
I have set this:

`if (defined($freek) && $freek<10000 && $freek>=0) {`
