### ISSUE TITLE
Analytics short-links are false-triggering the fraud attempt

### ISSUE THREAD

**Issue by LarryNewoldstamp** [MailScanner/v5#407]
Hi there. My name is Larry and I work for Newoldstamp.

We are providing analytics feature for our clients that is using regular short-links to track clicks. Some of our clients report the issue that their recipients see the message stating: "MailScanner has detected a possible fraud attempt from "img.newoldstamp.com" claiming to be example.com". Where example.com is the destination link to which the short-link redirects the clicker.

Is there something Newoldstamp can do to avoid that? Can Newoldstamp be white-listed or something? Or is there something wrong with our domain settings?

Thank you

**Comment by asuweb** [comment]
If you add the domain to `/etc/MailScanner/phishing.safe.sites.custom` file that should hopefully prevent it from triggering

**Comment by Skywalker-11** [comment]
It is triggered because the text displayed for the link contains some sort of URI (here example.com) that does not match the actual target of the link. If you adjust the link itself or the text to match each other it would also remove that warning.

**Comment by LarryNewoldstamp** [comment]
> It is triggered because the text displayed for the link contains some sort of URI (here example.com) that does not match the actual target of the link. If you adjust the link itself or the text to match each other it would also remove that warning.

Thanks, however, it is not possible to match the short link URL and destination URL. Our analytics works like bit.ly and any other link shorteners. Where the link says bit.ly/blah-blah and then redirects to the other website.

**Comment by LarryNewoldstamp** [comment]
> If you add the shortlink domain to `/etc/MailScanner/phishing.safe.sites.custom` file that should hopefully prevent it from triggering

Thanks for your answer. Is this a path to a local folder of the MailScanner user?

**Comment by Skywalker-11** [comment]
> 
> 
> > If you add the shortlink domain to `/etc/MailScanner/phishing.safe.sites.custom` file that should hopefully prevent it from triggering
> 
> Thanks for your answer. Is this a path to a local folder of the MailScanner user?

Yes. It is a config file on the mail gateway running MailScanner.

**Comment by LarryNewoldstamp** [comment]
> > > If you add the shortlink domain to `/etc/MailScanner/phishing.safe.sites.custom` file that should hopefully prevent it from triggering
> > 
> > 
> > Thanks for your answer. Is this a path to a local folder of the MailScanner user?
> 
> Yes. It is a config file on the mail gateway running MailScanner.

Thanks a lot. I am afraid, that doesn't resolve the issue for us. I was ultimately looking for a way to make Mailscanner ignore our short-links in all the emails regardless of which person opens an email with it. 

I was hoping that Mailscanner has some kind of a global white list which we could apply for.

**Comment by Skywalker-11** [comment]
Also notice
https://github.com/MailScanner/v5/blob/7b5b6443feb74ac274b41fb9f573ec428baf6710/common/etc/MailScanner/phishing.safe.sites.conf#L29-L30

**Comment by LarryNewoldstamp** [comment]
> Also notice
> https://github.com/MailScanner/v5/blob/7b5b6443feb74ac274b41fb9f573ec428baf6710/common/etc/MailScanner/phishing.safe.sites.conf#L29-L30

Awesome! I'll try that. Thank you!
