### ISSUE TITLE
Wrong labeling for 5.1.3-2

### ISSUE THREAD

**Issue by hluaces** [MailScanner/v5#412]
Hello,

I've noticed that recently you've released 5.2.1-1, congratulations on that.

This made some of our automated systems fail (this is our fault), but while I was trying to find the previous 5.1.3-2 binary packages I've found that either the git tag `5.1.3.2-2` is pointing to a wrong commit **\[1\]**. You can check this by visiting the 5.1.3.2-2-tagged `builds/` directory **\[2\]**  which is not showing the old, `.tar.gz` packages, as those were the ones for that version. It's showing the 5.2.x ones.

I suspect that **\[3\]** (or some close commit) is the one that should be tagged with `5.1.3.2-2`.

---

\[1\]: https://github.com/MailScanner/v5/commit/0a87daf349a638443edd9e3c80f7f33332f703d2
\[2\]: https://github.com/MailScanner/v5/tree/v5.1.3-2/builds
\[3\]: https://github.com/MailScanner/v5/commit/0a363e7809db63b220e1ed9295b328d0b390a519#diff-cd255022df04facc108ae4d30a05e7bb

**Comment by shawniverson** [comment]
That was my blunder.  Attempting to correct...

**Comment by hluaces** [comment]
That was fast. 

So far it seems to be working now, thank you for your work!

**Comment by shawniverson** [comment]
Fixed.
