### ISSUE TITLE
Could not read directory /var/spool/postfix/incoming

### ISSUE THREAD

**Issue by wkeeler** [MailScanner/v5#414]
Trying to implement MailScanner on RHEL 7.7 Postfix mail server with SELinux set to `enforcing`.

`MailScanner --lint` returns...
```
Tue Nov 12, 17:49:33 [root@mail /var/spool]# MailScanner --lint
Trying to setlogsock(unix)

Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 1500 hostnames from the phishing whitelist
Read 5996 hostnames from the phishing blacklists

Checking version numbers...
Version number in MailScanner.conf (5.2.1) is correct.

Your envelope_sender_header in spamassassin.conf is correct.
MailScanner setting GID to  (1004)
MailScanner setting UID to  (89)

Checking for SpamAssassin errors (if you use it)...
Using SpamAssassin results cache
Connected to SpamAssassin cache database
pyzor: check failed: internal error, python traceback seen in response
SpamAssassin reported no errors.
Auto: Found virus scanners: clamav
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There are 0 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = auto"
Found these virus scanners installed: clamav
===========================================================================
Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
1.message: Eicar-Test-Signature FOUND

./1/eicar.com: Eicar-Test-Signature FOUND

Virus Scanning: ClamAV found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses
===========================================================================
Virus Scanner test reports:
ClamAV said "eicar.com contains Eicar-Test-Signature"

If any of your virus scanners (clamav)
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
```
...and when I startup the MailScanner service the `/var/log/maillog` fills up with the following...
```
Nov 12 16:55:43 mail MailScanner[3525]: MailScanner Email Processor version 5.2.1 starting...
Nov 12 16:55:43 mail MailScanner[3525]: Reading configuration file /etc/MailScanner/MailScanner.conf
Nov 12 16:55:43 mail MailScanner[3525]: Reading configuration file /etc/MailScanner/conf.d/README
Nov 12 16:55:43 mail MailScanner[3525]: Could not read directory /var/spool/postfix/incoming
Nov 12 16:55:43 mail MailScanner[3525]: Error in configuration file line 212, directory /var/spool/postfix/incoming  for outqueuedir does not exist (or is not readable)
Nov 12 16:55:43 mail MailScanner[3525]: File containing list of incoming queue dirs (/var/spool/postfix/hold) does  not exist
Nov 12 16:55:43 mail MailScanner[3525]: Read 1500 hostnames from the phishing whitelist
Nov 12 16:55:43 mail MailScanner[3525]: Read 5996 hostnames from the phishing blacklists
Nov 12 16:55:43 mail MailScanner[3525]: Using SpamAssassin results cache
Nov 12 16:55:43 mail MailScanner[3525]: Connected to SpamAssassin cache database
Nov 12 16:55:43 mail MailScanner[3525]: Enabling SpamAssassin auto-whitelist functionality...
```
I verified that `/etc/MailScanner/MailScanner.conf` line 212 reads...

```
Outgoing Queue Dir = /var/spool/postfix/incoming
```

...and the rest of my MailScanner configuration edits are as follows...

```
Run As User = postfix
Run As Group = mtagroup
Incoming Queue Dir = /var/spool/postfix/hold
MTA = posfix
Incoming Work User = postfix
Incoming Work Group = mtagroup
Incoming Work Permissions = 0640
SpamAssassin User State Dir = /var/spool/MailScanner/spamassassin
```

The `/var/spool/postfix/hold/` directory gets populated with 13 Hex-char filenames, with the owner:group set to postfix:postfix, but the `/var/spool/postfix/incoming/` directory appears to remain empty.

Their permissions are set as follows...
```
drwxrwx---.  2 postfix mtagroup 4096 Nov 12 17:03 hold
drwxrwx---.  2 postfix mtagroup    6 Nov 12 18:03 incoming
```

It may be worth noting that when I `setenforce 0` while MailScanner is running, all logs to `/var/log/maillog` cease and no mail appears to get delivered.  At one point when I `setenforce 1` again, the `/var/log/maillog` filled with the following...

```
Nov 12 17:10:41 mail MailScanner[4505]: Cannot cd to dir /var/spool/postfix/hold to read messages, Permission denied
Nov 12 17:10:42 mail MailScanner[4470]: Cannot cd to dir /var/spool/postfix/hold to read messages, Permission denied
Nov 12 17:10:43 mail MailScanner[4434]: Cannot cd to dir /var/spool/postfix/hold to read messages, Permission denied
Nov 12 17:10:44 mail MailScanner[4387]: Cannot cd to dir /var/spool/postfix/hold to read messages, Permission denied
Nov 12 17:10:46 mail MailScanner[4540]: Cannot cd to dir /var/spool/postfix/hold to read messages, Permission denied
```
I know that MailScanner is known to have issues with Postfix, but I've been using MailScanner for years with my last Sendmail mail server and it worked great!  Plus, I saw the "footnote" at the bottom of the [Postfix support page](https://www.mailscanner.info/postfix/), and thought I'd give it a go.  I was just hoping that I was missing something simple, and that you guys might be able to set me straight.

Any thoughts?

**Comment by msapiro** [comment]
On 11/12/19 3:08 PM, wkeeler wrote:
> Trying to implement MailScanner on RHEL 7.7 Postfix mail server with
> SELinux set to |enforcing|.
...
> The |/var/spool/postfix/hold/| directory gets populated with 13 Hex-char
> filenames, with the owner:group set to postfix:postfix, but the
> |/var/spool/postfix/incoming/| directory appears to remain empty.
> 
> Their permissions are set as follows...
> 
> |drwxrwx---. 2 postfix mtagroup 4096 Nov 12 17:03 hold drwxrwx---. 2
> postfix mtagroup 6 Nov 12 18:03 incoming |
> 
> It may be worth noting that when I |setenforce 0| while MailScanner is
> running, all logs to |/var/log/maillog| cease and no mail appears to get
> delivered. At one point when I |setenforce 1| again, the
> |/var/log/maillog| filled with the following...
> 
> |Nov 12 17:10:41 mail MailScanner[4505]: Cannot cd to dir
> /var/spool/postfix/hold to read messages, Permission denied Nov 12
> 17:10:42 mail MailScanner[4470]: Cannot cd to dir
> /var/spool/postfix/hold to read messages, Permission denied Nov 12
> 17:10:43 mail MailScanner[4434]: Cannot cd to dir
> /var/spool/postfix/hold to read messages, Permission denied Nov 12
> 17:10:44 mail MailScanner[4387]: Cannot cd to dir
> /var/spool/postfix/hold to read messages, Permission denied Nov 12
> 17:10:46 mail MailScanner[4540]: Cannot cd to dir
> /var/spool/postfix/hold to read messages, Permission denied |


So you definitely have a SELinux issue preventing MailScanner from
accessing Postfix queues, but...


> I know that MailScanner is known to have issues with Postfix, but I've
> been using MailScanner for years with my last Sendmail mail server and
> it worked great! Plus, I saw the "footnote" at the bottom of the Postfix
> support page <https://www.mailscanner.info/postfix/>, and thought I'd
> give it a go. I was just hoping that I was missing something simple, and
> that you guys might be able to set me straight.


Does this mean you are actually trying to use The MailScanner Milter option.

If so, in addition to other changes, you must remove

/^Received:/ HOLD

from the file configured for header_checks in Postfix main.cf.

Also, for reference, here's what I have in my MailScanner configuration
for the milter option.

Incoming Queue Dir = /var/spool/MailScanner/milterin
Outgoing Queue Dir = /var/spool/MailScanner/milterout
MTA = msmail
MSMail Queue Type = short
Milter Scanner = yes
Milter Dispatcher = postfork

# For QMQP delivery

MSMail Delivery Method = QMQP
MSMail Socket Type = inet
MSMail Relay Port = 628
Milter Ignore Loopback = no

-- 
Mark Sapiro <mark@msapiro.net>        The highway is for gamblers,
San Francisco Bay Area, California    better use your sense - B. Dylan

**Comment by shawniverson** [comment]
@wkeeler Is this resolved?
