### ISSUE TITLE
Syntax Error - Installation Script

### ISSUE THREAD

**Issue by roshanjonah** [MailScanner/v5#42]
Getting a syntax error when trying to install on Ubuntu server using "sh install.sh". The second step asks whether MTA needs to be installed. When I hit "N" for no. It just comes up with the following:

install.sh: 82: install.sh: Syntax error: "(" unexpected (expecting "then"). 

The downloaded package is from https://s3.amazonaws.com/msv5/release/MailScanner-5.0.3-7.deb.tar.gz

**Comment by msapiro** [comment]
It requires bash. It doesn't run with sh. It has a shebang

#!/usr/bin/env bash

What if you just run './install.sh' instead of 'sh install.sh'?

and BTW, the current release is https://s3.amazonaws.com/msv5/release/MailScanner-5.0.4-3.deb.tar.gz

**Comment by roshanjonah** [comment]
Mark,

Thanks for that. Yea I realised that. It works now :) 

What are the general upgrade instructions?

Cheers!

**Comment by msapiro** [comment]
Upgrade is the same as a fresh install. Just download and run the install.sh script. Heed the

WARNING - Make a backup of any custom configuration files if upgrading - WARNING

The installation should create ms_upgrade/saved.pppp/ in your home directory and backup some things there, but don't rely on that to get it all.

Then after installing, just make sure any local stuff is there.
