### ISSUE TITLE
Spoofed double From header detection

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#420]
```
From: "Someone <someone@example.org>" <drevil@example.net>

**Comment by Skywalker-11** [comment]
I am using this in spamassassin to flag it. 

It also matches valid `From: ` headers with multiple senders separated by `,`. Most mail clients aren't able to display them correctly and it is rarely used (never encountered a non-spam mail with this). So they are also flagged.

```
header local_MULTI_FROM_ADDRESS From =~ /^[^<]*<[^>]*>[^<]*<[^>]*>$/i
```

**Comment by shawniverson** [comment]
@Skywalker-11 May I implement your regex in mailscanner?  I think I will add the same option in MailScanner as well, for folks that just want to toggle a setting.

**Comment by spec1re** [comment]
There is also a SA Plugin for this

https://spamassassin.apache.org/full/3.4.x/doc/Mail_SpamAssassin_Plugin_FromNameSpoof.txt

**Comment by gh0stwizard** [comment]
Hello,
FYI, I have resolved this issue months ago like this:

/etc/mail/spamassassin/local.cf
```
# Malformed From header attack
# From: Name <valid@addr.com> <envelop@addr.com>
header    __FROM_MULTI_ADDR1 exists:From
header    __FROM_MULTI_ADDR2 From =~ /<.*>[^<>,]*<.*>/
meta      FROM_MULTI_ADDR __FROM_MULTI_ADDR1 && __FROM_MULTI_ADDR2
describe  FROM_MULTI_ADDR Malformed From header
score     FROM_MULTI_ADDR 100.00
```

/etc/postfix/smtp_header_checks
```
/^From:\s+(.*?)\s*<(.*?)>(\s*<.*?>)+\s*$/ REPLACE From: "$1 <$2>" $3
```

```
$ postconf | grep smtp_header_checks
smtp_header_checks = regexp:/etc/postfix/smtp_header_checks
```

**Comment by shawniverson** [comment]
You guys!  Does it make sense to have a simple option in MailScanner for everyone, or am I just being redundantly redundant?

**Comment by gh0stwizard** [comment]
IMHO, this could be done as separate .cf file for SpamAssassin. It would be good if it will be included out of box. So, I could see such messages (later, block it by IP, write abuses, etc), and second, I could adjust a score value for it (in case if it is low in my setup).

**Comment by spec1re** [comment]
> 
> 
> You guys! Does it make sense to have a simple option in MailScanner for everyone, or am I just being redundantly redundant?

There so many half baked solutions all over the place, imo a solid option in MailScanner would be very nice!

**Comment by cepheid666** [comment]
IMHO I would not handle the first regex (in https://github.com/MailScanner/v5/issues/420#issue-525674001) in MailScanner.  It is RFC-compliant because the first bracketed address is inside the quoted part.  It may be spammy, but that's what spamassassin or rspamd are for.

The version shown in https://github.com/MailScanner/v5/issues/420#issuecomment-557051680 appears to be non-RFC-compliant because it has two bracketed parts, so that could potentially be a MailScanner option... although anyone malforming the From in this way won't be able to receive a bounce message with the MS error...

**Comment by msapiro** [comment]
On 12/18/19 12:21 AM, Amir Caspi wrote:
> 
> The version shown in #420 (comment)
> <https://github.com/MailScanner/v5/issues/420#issuecomment-557051680>
> appears to be non-RFC-compliant because it has two bracketed parts, so
> that could potentially be a MailScanner option... although anyone
> malforming the From in this way won't be able to receive a bounce
> message with the MS error...


Actually, it is only non-compliant in that it is missing a comma. The
From: header is defined,
<https://www.rfc-editor.org/rfc/rfc5322.html#section-3.6.2>, to contain
`mailbox-list` which is,
<https://www.rfc-editor.org/rfc/rfc5322.html#section-3.4>, a comma
separated list of mailboxes.

I.e.,
```
From: Name <valid@addr.com> <envelop@addr.com>
```
is non-compliant, but
```
From: Name <valid@addr.com>, <envelop@addr.com>
```
is compliant.

-- 
Mark Sapiro <mark@msapiro.net>        The highway is for gamblers,
San Francisco Bay Area, California    better use your sense - B. Dylan

**Comment by cepheid666** [comment]
In that case, I might recommend leaving this out of MailScanner entirely and letting either the MTA or SpamAssassin/rspamd handle this kind of thing.  If it does become an option in MailScanner, I'm not sure what the best option would be for handling it -- maybe just "disarming" the From the same way phishing links are disarmed...

**Comment by shawniverson** [comment]
Leaving out of MailScanner since SA has a module for this purpose now.
