### ISSUE TITLE
Can your mailscanner catch and forward all serverwide mails by a regex match?

### ISSUE THREAD

**Issue by aprokopyev** [MailScanner/v5#421]
Hello,
 
I need to catch mails for the whole mail server, matching a specific regex in some of its fields and then forward copies of these e-mail to a specific predefined single e-mail address.
 
Please let me know, does your MailScanner software have such a functionality?
How is it named and mentioned in your documentation? Which edition required?
 
I am always very glad to tell other people good words about your antispam product and spread a link to your website over the world.
 
Thank you very much,
Alex

**Comment by shawniverson** [comment]
No, not without some custom scripting.

**Comment by aprokopyev** [comment]
Shawn, 

I was told it is "Custom Actions" feature of your MailScanner, can you please confirm?

/usr/share/MailScanner/perl/custom/CustomAction.pm

Can you please suggest an appliance the most suitable for the task?
Like EFA, MailMan, MailWatch, etc.

Thanks for your help.

**Comment by Skywalker-11** [comment]
@aprokopyev with the "Custom Actions" feature you can implement your own extensions to the MailScanner functionality. 
In your case you would have to implement the regex search and the transfer of the mail to your specified mail address.
For an example on how to interact with the `$message` object you can take a look at 
https://github.com/mailwatch/MailWatch/blob/1.2/MailScanner_perl_scripts/MailWatch.pm#L252
