### ISSUE TITLE
exim 4.93 spool file format change

### ISSUE THREAD

**Issue by derringer** [MailScanner/v5#431]
This commit and change to the exim code requires a change to Mailscanner possibly in Exim.pm
https://github.com/Exim/exim/commit/f3ebb786e451da973560f1c9d8cdb151d25108b5

New spool file format as of exim 4.93, tainted values (here helo_name) now have two -- in front of them.

This causes Mailscanner to print: `New Batch: Found invalid queue files: 10HmbC-0005vi-00`

Example header file (truncated)
```
10HmbC-0005vi-00-H
EXIMUSER EXIM_UID EXIM_GID
<a@y>
ddddddddd 0
-received_time_usec .uuuuuu
--helo_name rhu.barb
-host_address 127.0.0.1.9999
-interface_address 127.0.0.1.1225
-received_protocol esmtp
-body_linecount 0
-max_received_linelength 25
-deliver_firsttime
```

**Comment by waytotheweb** [comment]
If anyone needs a quick fix for this, modify Exim.pm:

```
281c281
<     $line =~ s/^-(\w+) ?// or last;
---
>     $line =~ s/^--?(\w+) ?// or last;

```

**Comment by shawniverson** [comment]
This fix is actually acceptable, preparing PR.
