### ISSUE TITLE
Unitd mailscanner

### ISSUE THREAD

**Issue by yoorshop** [MailScanner/v5#434]
Hello,

As discussed with cPanel support, your integration cpanel is broken at unit file level, we raised issue at saving settings in service manager, at bottom, 'unknown service' eappear

See diag :

Seth Daughenbaugh (cPanel)

Dec 24, 13:43 CST

 Hello,

Thank you for getting back to us. The issue can be seen here in the output of the strace:

20:38:11 execve("/usr/bin/systemctl", ["/usr/bin/systemctl", "show", "-p", "LoadState", "-p", "FragmentPath", "-p", "ActiveState", "-p", "MainPID", "-p", "SubState", "-p", "PIDFile", "-p", "UnitFileState", "-p", "Type", "-p", "CanStart", "-p", "ExecMainCode", "-p", "ExecMainStatus", "mailscanner.service"], ["LANG=C", "HOME=/root", "RESTARTSRV=1", "OPENSSL_NO_DEFAULT_ZLIB=1", "PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin", "SERVER_SOFTWARE=cpsrvd 11.84.0.18", "TZ=UTC", "DOCUMENT_ROOT=/usr/local/cpanel/base", "USER=root"]) = 0 <0.000100>

You can see that systemctl is attempting to load mailscanner.service, but your server does not have that. Instead, it has MailScanner.service. I copied the MailScanner.service to mailscanner.service and no longer receive errors in Service Manager. In fact, the output shows mailscanner is able to restart properly:

Saving Changes to tailwatchd (enabled)...

...Done
Waiting for “mailscanner” to start ……waiting for “mailscanner” to initialize ………finished.

Service Status
mailscanner (MailScanner: starting children) is running as mailnull with PID 201775 (systemd+/proc check method).
mailscanner (MailScanner: starting children) is running as mailnull with PID 201776 (systemd+/proc check method).

Startup Log
Dec 24 20:40:34 web1.hosting1976.fr systemd[1]: Starting MailScanner AntiSpam and AntiVirus...
Dec 24 20:40:35 web1.hosting1976.fr MailScanner[201736]: MailScanner setting GID to mail (12)
Dec 24 20:40:35 web1.hosting1976.fr MailScanner[201736]: MailScanner setting UID to mailnull (47)
Dec 24 20:40:36 web1.hosting1976.fr systemd[1]: Started MailScanner AntiSpam and AntiVirus.
Dec 24 20:40:36 web1.hosting1976.fr MailScanner[201776]: MailScanner Email Processor version 5.0.2 starting...

Log Messages
Dec 24 20:40:36 web1 MailScanner: MailScanner Email Processor version 5.0.2 starting...

mailscanner started successfully.

Service Changes Complete

If you are having this issue on other servers, you may want to copy MailScanner.service to mailscanner.service, run systemctl daemon-reload, and then you should be ok. You may also want to reach out to MailScanner directly and let them know that their integration with cPanel is broken based on the systemd unit file name.

Seth Daughenbaugh
cPanel L.L.C.
Technical Analyst II

**Comment by shawniverson** [comment]
https://github.com/MailScanner/v5/blob/master/rhel/mailscanner.spec#L501

The systemd unit filename is lowercase in current versions of MailScanner, please upgrade.

**Comment by Skywalker-11** [comment]
Also be aware that if the .service file is missing on the system systemd may falls back to the sysvinit script which may result in the service name beeing MailScanner.service
