### ISSUE TITLE
RBL check is wrong

### ISSUE THREAD

**Issue by yoorshop** [MailScanner/v5#435]
Hi,

First case :

We use until now RBL spamlist in mailscanner with BARRACUDA SPAMCOP.

A client reported an issue where he was sending email being well authenticated with auth imap, and using the proper smtp host configuration in his client mail, and is causing that his ISP IP was checked against RBL BARRACUDA for which this ISP IP is listed, then causing that email sent to itself or another email account of this same domain, is being blocked by MSFE. This make no sense in mdefault mailscanner config, and issue don't appear when mail is sent from website, or webmail.

Issue has been verified on many servers.

We contacted cPanel, but they were not able to diag since it is too complicated. The point was to find out if exim or mailscanner was doing this. We were not convinced by cpanel investigation, we had to find a way to send email test from an IP listed at BARRACUDA.

We found an IP listed at barracuda in our infrastructure IP reserve for VPS :
https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a164.132.62.116&run=toolpage#

We have setup a VPS with it so that to send from our local client mail software with an IP blacklisted as such

To perform test with exim only, we used a server client where no mailscanner is installed at all to asess properly the behavior of exim with RBL checks when auth imap is done

We enabled RBL barracuda in exim, and results is that IP sender is not being checked, then email is not blocked as when using mailscanner + barracuda RBL check :

Delivery Event Details
Event:    success success
Sender User:    user123
Sender Domain:    xxxxxx.com
From Address:    test@xxxxxx.com
Sender:    test@xxxxxx.com
Sent Time:    Dec 25, 2019, 10:44:10 AM
Sender Host:    10.8.0.2
Sender IP:    164.132.62.116
Authentication:    dovecot_plain
Spam Score:   
Recipient:    test@xxxxxx.com
Delivered To:    test@xxxxxx.com
Delivery User:    user123
Delivery Domain:    xxxxxx.com
Router:    virtual_user
Transport:    dovecot_virtual_delivery
Out Time:    Dec 25, 2019, 10:44:10 AM
ID:    1ik3Dh-00B1dr-Sj
Delivery Host:    localhost
Delivery IP:    127.0.0.1
Size:    3.81 KB
Result:    Accepted

Conclusion is then clear, exim is doing the proper job

Now back on server iusing mailscanner, I have tested to combine to use RBL check via Exim, and disable RBL check BARRACUDA SPAMCOP in mailscanner.

No more issues, however, we were wondering if this RBL check was still truly working, we found that no, indeed, we check recent blocked emails with new config

////////////////////////////////
High Scoring Spam
Message ID    1ik3jl-001NIk-1Z
Date Received    11:17:58
From       
To   
Subject    Anche un piccolo pisello sarà enorme: aumenta rapidamente il tuo pene di 3-4 cm
Size    4179 Bytes
Client IP   
Spam Report   
spam, SpamAssassin (not cached, score=18.793, required 5, autolearn=spam, BAYES_50 0.80, DCC_REPUT_13_19 -0.10, DKIM_SIGNED 0.10, HK_RANDOM_FROM 1.00, HTML_IMAGE_ONLY_16 1.09, HTML_MESSAGE 0.00, HTML_SHORT_LINK_IMG_2 0.00, KAM_VERY_BLACK_DBL 5.00, RCVD_IN_SBL 0.14, SPF_PASS -0.00, T_REMOTE_IMAGE 0.01, URIBL_ABUSE_SURBL 1.25, URIBL_BLACK 5.00, URIBL_DBL_SPAM 4.50)
Spam Report (components)   
Rule    Score    Rule Description
BAYES_50    0.80    Bayes spam probability is 40 to 60%
DCC_REPUT_13_19    -0.10    DCC reputation between 13 and 19 %
DKIM_SIGNED    0.10    Message has a DKIM or DK signature, not necessarily valid
HK_RANDOM_FROM    1.00    From username looks random
HTML_IMAGE_ONLY_16    1.09    HTML: images with 1200-1600 bytes of words
HTML_MESSAGE    0.00    HTML included in message
HTML_SHORT_LINK_IMG_2    0.00    HTML is very short with a linked image
KAM_VERY_BLACK_DBL    5.00   
RCVD_IN_SBL    0.14    Received via a relay in Spamhaus SBL
SPF_PASS    -0.00    SPF: sender matches SPF record
T_REMOTE_IMAGE    0.01   
URIBL_ABUSE_SURBL    1.25    Contains an URL listed in the ABUSE SURBL blocklist
URIBL_BLACK    5.00    Contains an URL listed in the URIBL blacklist
URIBL_DBL_SPAM    4.50    Contains a spam URL listed in the Spamhaus DBL blocklist
SpamAssassin Score    18.79   
SpamAssassin Auto Learn    spam
Header IPs   
IP    Hostname    City    Region    Country    Organisation
45.95.32.114     skinny.conquerclash.com    Vilnius    Vilnius    LT    AS42549 UAB "Baltnetos komunikacijos"

/////////////////////////////////////////////////////

After verification of sender IP, we found that it is also blacklisted in BARRACUDA, and that exim check is not done properly when using Mailscanner :
https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a45.95.32.114&run=toolpage#

So the issue remain entire, the RBL check done by mailscanner is not working properly, or a custom setting should be done ? We think that by default, proper behavior should be handled

We checked file :
spam.whitelist.rules and spam.scanning.rules

Solution is either to let exim do RBL check since it has proper ACL to not check IP of authenticated senders : !authenticated = *
OR
create new whitelist rule. 
Only a such rule hereafter can make this exception being validated, and don't prevent spam scan to work for other domain sending to this domain ie :
To: *@* and From: *@xxxxxxxwine.com    yes
This is what we get when using UI MSFE, and this is what we did for client who reported the issue.

Which means we need this added automatically for any whost of server in a sort of whitelist file in mailscanner, and this would fix the issue.

Nothing in UI either custom or default permit to fix this issue.

Many people face this issue :
http://lists.mailscanner.info/pipermail/mailscanner/2015-September/102606.html
https://forums.cpanel.net/threads/can-rbl-ignore-authenticate-users.54877/
https://github.com/MailScanner/v5/issues/128

Now the second case, even without RBL block, problem is that local domains send-receive are well being scanned for spam, whereas I don't find that outgoing spam is enabled. Outgoing means to external domain, a local domain sending to himself whatever method is used should not be scanned except SPF check which prevent 'mail forge' attack

Proof :
Scan Status    High Scoring Spam
Message ID    1ilERq-004S0t-9l
Date Received    16:56:19
From       
To   
Subject    Nouveau Message De Pierr'O feu
Size    1565 Bytes
Client IP   
Spam Report   
spam, SpamAssassin (not cached, score=10.703, required 5, ALL_TRUSTED -1.00, BAYES_99 5.00, BAYES_999 1.00, DKIM_ADSP_ALL 0.80, FREEMAIL_FORGED_REPLYTO 2.10, RAZOR2_CF_RANGE_51_100 1.89, RAZOR2_CHECK 0.92)
Spam Report (components)   
Rule    Score    Rule Description
ALL_TRUSTED    -1.00    Passed through trusted hosts only via SMTP
BAYES_99    5.00    Bayes spam probability is 99 to 100%
BAYES_999    1.00    Bayes spam probability is 99.9 to 100%
DKIM_ADSP_ALL    0.80    No valid author signature, domain signs all mail
FREEMAIL_FORGED_REPLYTO    2.10    Freemail in Reply-To, but not From
RAZOR2_CF_RANGE_51_100    1.89    Razor2 gives confidence level above 50%
RAZOR2_CHECK    0.92    Listed in Razor2 (http://razor.sf.net/)
SpamAssassin Score    10.70   
SpamAssassin Auto Learn    no
Header IPs   
IP    Hostname    City    Region    Country    Organisation
127.0.0.1    Local IP

**Comment by shawniverson** [comment]
Postfix/MailScanner supports this.

https://github.com/MailScanner/v5/commit/1e7ea3382db833d8362f2f894482efddc65e208b

In order to support this for exim, exim would need to inform MailScanner via queue metadata or a header entry.  I'll be happy to implement this if exim has a way to pass along this information to MailScanner.

**Comment by akissa** [comment]
Exim passes this information, you can use the following check to determine that
`exists $message->{metadata}->{dv_auth_id} ? 1 : 0`

**Comment by shawniverson** [comment]
@akissa Thanks for this tidbit, looks like we can implement this with Exim as well then.  There are some pressing things, of course, but I will plan on revisiting this soon.
