### ISSUE TITLE
Integrating SPF, DKIM, DMARC and ARC into MailScanner

### ISSUE THREAD

**Issue by leeyc0** [MailScanner/v5#444]
Email service providers starts using SPF, DKIM, DMARC and ARC now. MailScanner obviously break DMARC, and this problem is intended be solved by ARC.

I am currently using external milter for SPF, DKIM and DMARC check, However for ARC to work properly, this must be done in MailScanner, since the RFC states all mail modifications must be done before ARC seal and sign emails, and ARC requires verifying DKIM and ARC signatures BEFORE modifying the email. (Otherwise the signature breaks.)

Due to these constraints, I believe supporting SPF, DKIM, DMARC and ARC have to done in MailScanner.

**Comment by msapiro** [comment]
I still haven't completely worked out my openarc configuration, but I use Postfix and the MailScanner milter option with delivery from MailScanner back to Postfix via QMQP. With this configuration you can put milters ahead of MailScanner by putting them before MailScanner in smtpd_milters and put milters after MailScanner by putting them in non_smtpd_milters. So. for example to do dkim verification on incoming mail before MailScanner and signing of mail after MailScanner, I use
```
# Milters are
# 8891 opendkim sign
# 8892 opendkim verify
# 33333 MailScanner
# Until we figure out openarc just dkim verify incoming and sign outgoing.
smtpd_milters = inet:127.0.0.1:8892 inet:127.0.0.1:33333
non_smtpd_milters       = inet:127.0.0.1:8891
```

**Comment by leeyc0** [comment]
The problem is, you need to dkim sign your email AFTER MailScanner, while verifying DKIM BEFORE MailScanner. You would need to run two opendkim instances.

**Comment by shawniverson** [comment]
I don't see a problem with that.

Also, MailScanner does not break the message if it is set up not to do so (no signing or message modifications, append new headers to the top of header).

Regardless, I disagree with this idea that MailScanner should be performing these functions.

**Comment by msapiro** [comment]
@leeyc0 Yes, you need two instances. I actually run six, three each of opendkim and openarc to sign only, verify only or sign and verify. I don't need them all, but the cost is minimal. And I agree with @shawniverson that these functions are better handled in the MTA. MailScanner's job is detecting and dealing with spam, malware, phishing and the like, and it should stick to that.
