### ISSUE TITLE
f-prot is missing from the virus configuration

### ISSUE THREAD

**Issue by ediazrod** [MailScanner/v5#445]
Hi the old Mailscanner has f-prot as antivirus, But I don't see in this new v5 version..

Still free, as you can download the install, and use as free.
http://www.f-prot.com/support/unix/

there is reason for this? or I can use the old wrapper or a generic one to make run.?

I can try to upgrade the old one. :-P

**Comment by shawniverson** [comment]
@ediazrod Just need an updated wrapper :) I will be happy to include it.
