### ISSUE TITLE
noreply@mailscanner.info email saying my account has been deleted

### ISSUE THREAD

**Issue by vahost** [MailScanner/v5#447]
I received an email yesterday from noreply@mailscanner.info saying the following:

"MailScanner
Your account has been deleted.All your personal details and any uploads have been permanently removed.
If your account has been deleted by accident please contact us.
Thank you!
The MailScanner Team:

It provided no way for me to contact anyone, so I'm posting here about it.

**Comment by shawniverson** [comment]
Do you have the original message?

**Comment by msapiro** [comment]
It is almost certainly a scam of some kind. Had there been a way to contact anyone, it would probably have been a bad idea. There are no "accounts" at mailscanner.info, only a few mailing lists, and the mailing list software would not send that message.

If you have the original mail with all it's headers, you can post that and we can investigate further, but it's almost certainly not from us.

**Comment by vahost** [comment]
Makes sense. Here's the original message source. I've masked my email address and my server name with xxxx@xxxxxx.xxx and yyyyyy.yyyyyyyyyy.yyy, but otherwise it's intact.

Return-Path: <01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000@amazonses.com>
Delivered-To: xxxx@xxxxxx.xxx
Received: from yyyyyy.yyyyyyyyyy.yyy
	by yyyyyy.yyyyyyyyyy.yyy with LMTP
	id Z6P4BHgeOl6XTwAAv5qG0A
	(envelope-from <01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000@amazonses.com>)
	for <xxxx@xxxxxx.xxx>; Tue, 04 Feb 2020 20:46:32 -0500
Return-path: <01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000@amazonses.com>
Envelope-to: xxxx@xxxxxx.xxx
Delivery-date: Tue, 04 Feb 2020 20:46:32 -0500
Received: from a8-84.smtp-out.amazonses.com ([54.240.8.84]:35468)
	by yyyyyy.yyyyyyyyyy.yyy with esmtps  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
	(Exim 4.93)
	(envelope-from <01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000@amazonses.com>)
	id 1iz9lu-0005H4-22
	for xxxx@xxxxxx.xxx; Tue, 04 Feb 2020 20:46:30 -0500
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=6gbrjpgwjskckoa6a5zn6fwqkn67xbtw; d=amazonses.com; t=1580867148;
	h=Date:To:From:Subject:Message-ID:MIME-Version:Content-Type:Feedback-ID;
	bh=T2So05Y+uZA3ycNxxaoAChlFrvXjzz3B3g8R0G0k4V4=;
	b=c3vq2ACGwAIrsq9PheuXhGANA7FjmpCx6pBv1PAQ9wFVf2zZCdSrxRQc+advhtvF
	HIOiDrYuLPFmHpSnSw721C5GvP6Id2vbUCQONBrhLb2cFc4gNYcJWyxDNOQ+r1h1QOZ
	u18+FeBMp/dXugqvaYwWlGnSHeoAv+xavLUrI75Q=
Date: Wed, 5 Feb 2020 01:45:48 +0000
To: xxxx@xxxxxx.xxx
From: MailScanner <noreply@mailscanner.info>
Subject: Your account has been deleted
Message-ID: <01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000@email.amazonses.com>
X-Mailer: WPMailSMTP/Mailer/smtp 1.8.1
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
X-SES-Outgoing: 2020.02.05-54.240.8.84
Feedback-ID: 1.us-east-1.+9lDZ+dh9ctXBR4ieH8fusNy/CBGcHdiALgBreZX2NQ=:AmazonSES
X-Spamless-MailScanner-Information: Please contact the ISP for more information
X-Spamless-MailScanner-ID: 1iz9lu-0005H4-22
X-Spamless-MailScanner: Found to be clean
X-Spamless-MailScanner-SpamCheck: not spam, SpamAssassin (not cached,
	score=3.649, required 5, BAYES_50 0.80, BOTNET_IPINHOSTNAME 1.00,
	DCC_CHECK 1.10, DKIM_SIGNED 0.10, DKIM_VALID -0.10,
	KAM_INFOUSMEBIZ 0.75, SPF_PASS -0.00)
X-Spamless-MailScanner-SpamScore: sss
X-Spamless-MailScanner-From: 01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000@amazonses.com
X-Spam-Status: No

MailScanner
Your account has been deleted.All your personal details and any uploads have been permanently removed.
If your account has been deleted by accident please contact us.
Thank you!
The MailScanner Team

**Comment by msapiro** [comment]
Thank you for the message. It originated from amazonses.com (Amazon Simple Email Service) <https://aws.amazon.com/ses/>. It appears that spammers and other bad actors are using that service to send phony email. If you report it to Amazonses, they might be able to identify the responsible account from the string '01000170130658e0-88ef62e2-c51e-4c71-8136-e576ae6f9ea7-000000' which appears the local part of both the Message-ID and envelope sender, and do something about it.

In any case, you and your use of MailScanner have nothing to worry about from this.
