### ISSUE TITLE
Warnings after latest upgrade

### ISSUE THREAD

**Issue by fesarlis** [MailScanner/v5#449]
I get the following warnings after upgrading to 5.2 (MS seems to work) (I use clamd; clamavmodule was never installed):

MailScanner starting ... 

Syntax error(s) in configuration file: at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2205.
Unrecognised keyword "clamavmodulemaximumcompressionratio" at line 922 at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2208.
Unrecognised keyword "clamavmodulemaximumfiles" at line 920 at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2208.
Unrecognised keyword "clamavmodulemaximumfilesize" at line 921 at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2208.
Unrecognised keyword "clamavmodulemaximumrecursionlevel" at line 919 at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2208.
Unrecognised keyword "monitorsforclamavupdates" at line 910 at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2208.
Warning: syntax errors in /etc/MailScanner/MailScanner.conf. at /usr/share/MailScanner/perl/MailScanner/Config.pm line 2213.

**Comment by msapiro** [comment]
Did you upgrade MailScanner.conf? See <https://github.com/MailScanner/v5/blob/master/common/etc/MailScanner/MailScanner.conf> and #437.

**Comment by fesarlis** [comment]
Yes I did.

**Comment by shawniverson** [comment]
@fesarlis 

You can remove or comment out the offending lines in MailScanner.conf.  However, the upgrade should have removed them for you automatically.

Please answer the following so that we can look into this deeper:

1.  Exact steps you took to upgrade MailScanner
2.  Your distribution and version

**Comment by fesarlis** [comment]
1. Run the tool as always (/usr/sbin/ms-upgrade-conf)

cd /etc/MailScanner
ms-upgrade-conf MailScanner.conf MailScanner.conf.rpmnew > MailScanner.new
mv -f MailScanner.conf MailScanner.old
mv -f MailScanner.new  MailScanner.conf

2. CentOS 6.10. Latest MailScanner 5.2.2-1

**Comment by shawniverson** [comment]
@fesarlis I suspect your issue is that you inadvertently ran ms-upgrade-conf twice.  The rpm executes it automatically during upgrade.  I believe the MailScanner.conf.rpmnew file you targeted wasn't really the latest one and may have actually pulled those values back in.

**Comment by fesarlis** [comment]
I do not use the RPM to install mailscanner. I use the install script.

**Comment by shawniverson** [comment]
@fesarlis "I do not use the RPM to install mailscanner"

Then how are you getting a MailScanner.conf.rpmnew file?  This supports the idea that the rpmnew file you are targeting is not the latest version of the config.

**Comment by Skywalker-11** [comment]
@fesarlis do you refer to the `install.sh` from the .nix.tar.gz archive as `install script` or some other? 
If you refer to mailwatch-install-script that uses the RPM in the background and as such already does a config upgrade

**Comment by fesarlis** [comment]
Indeed. I did not know it uses the RPM in the background.
The thing is that when the install.sh is executed for some reason my configuration is overwritten. I did not want to believe that so I triple checked. It definitely gets overwritten with the default configuration (before running ms-upgrade-conf).

**Comment by shawniverson** [comment]
@fesarlis Just to confirm, you are using the tarball install with install.sh?  If so did you have a MailScanner.conf.original file?  It looks like install.sh moves your config to this file.
