### ISSUE TITLE
drive.google.com blocked by phishing.bad.sites.conf

### ISSUE THREAD

**Issue by p1r473** [MailScanner/v5#451]
drive.google.com blocked by phishing.bad.sites.conf
It is not a phishing domain.
Let me know if I posted this in the wrong project

**Comment by shawniverson** [comment]
https://www.phishtank.com/

**Comment by p1r473** [comment]
![image](https://user-images.githubusercontent.com/9235633/75085514-29e94f00-54f8-11ea-9e0a-01efacbe6723.png)
Either way.. just because its in someone else's database doesnt mean it needs to be in yours

**Comment by shawniverson** [comment]
@p1r473 We pull directly from phishtank, we don't have our own.

**Comment by shawniverson** [comment]
@p1r473 and your query is wrong anyway, put https://drive.google.com

**Comment by shawniverson** [comment]
Anyway...Phishtank isn't going to budge on that one...

Create and place drive.google.com into /etc/MailScanner/phishing.safe.sites.conf.local to override it and run ms-update-phishing.
