### ISSUE TITLE
sa-update runs with wrong user in debian

### ISSUE THREAD

**Issue by thctlo** [MailScanner/v5#452]
Hai, 
on Debian i noticed v5/common/usr/sbin/ms-update-sa handles the updates. 
Only, this is run as root, where debian uses this part. 

'#Update
umask 022
env -i LANG="$LANG" PATH="$PATH" http_proxy="$http_proxy" \
    start-stop-daemon --chuid debian-spamd:debian-spamd --start \
    --exec /usr/bin/sa-update -- \
    --gpghomedir /var/lib/spamassassin/sa-update-keys 2>&1

Where user:group is debian-spamd 
Now this updates fine as shown: 
 root[58504]: ms-update-sa: spamassassin signatures updated

but, in debian cron.daily : /etc/cron.daily/spamassassin isnt disabled. 
resulting in log error which triggers logwatch for example. 

Adding a section per OS for sa-compile, in ms-update-sa  should fix it.

**Comment by shawniverson** [comment]
It is up to you are system operator to decide in /etc/MailScanner/defaults whether to use ms-update-sa (the ms_cron_sa option) or to use the one provided in the debian. From what I am guessing is a debian-specific spamassassin package.  You should not use both to avoid this issue and settle on one or the other.
