### ISSUE TITLE
Phishing campaign getting around filename hiding rule

### ISSUE THREAD

**Issue by rickyboone** [MailScanner/v5#453]
Something I've noticed with some of the reported emails I get.  A phishing campaign using an HTML attachment was getting around the filename hiding (double-extension) rule in the default filename.rules.conf.  I'm testing a slight modification, but thought it was worth sharing in case anyone else might be able to use it.

Relevant logs:
Mar 10 12:56:40 mailscanner1 MailScanner[13157]: Filename Checks: Allowing 8567B20542C1.A6236 Payment.PDF.html (no rule matched)
Mar 10 12:56:40 mailscanner1 MailScanner[13157]: Filetype Checks: Allowing 8567B20542C1.A6236 Payment.PDF.html
Mar 10 13:23:13 mailscanner1 MailScanner[3868]: Filename Checks: Allowing 5F3892014E3D.A5852 Payment.PDF.html (no rule matched)
Mar 10 13:23:13 mailscanner1 MailScanner[3868]: Filetype Checks: Allowing 5F3892014E3D.A5852 Payment.PDF.html

Previous entry in filename.rules.conf:
`deny    \.[a-z][a-z0-9]{2,3}\s*\.[a-z0-9]{3}$ Found possible filename hiding                          Attempt to hide real filename extension`

Current entry in filename.rules.conf:
`deny    \.[a-z][a-z0-9]{2,3}\s*\.[a-z0-9]{3,4}$ Found possible filename hiding                          Attempt to hide real filename extension`

**Comment by rickyboone** [comment]
Additionally, if anyone wants to see what this specific phishing campaign looks like, here it is in a sandbox:  https://app.any.run/tasks/6557cc9f-5816-48c9-b230-cf84fa5ed716

**Comment by shawniverson** [comment]
Sounds worth including in an update to catch those.
