### ISSUE TITLE
Feature request: IMAP authentication

### ISSUE THREAD

**Issue by oktayaa** [MailScanner/v5#455]
LDAP authentication is great however it would be nice to have mailwatch authenticate against IMAP & SMTP. 

IMAP is a little bit better because at least Dovecot supports a masteruser configuration where you can log in as username@domain.com*masteruser and access their inbox. It would make testing *as* other users very easy.

It would also be easier to set up than LDAP (if they even have LDAP) as well if I am not mistaken.

**Comment by Skywalker-11** [comment]
MailScanner is only the mail scanning part. 
The Gui is MailWatch [https://github.com/mailwatch/MailWatch](https://github.com/mailwatch/MailWatch)

**Comment by oktayaa** [comment]
Sorry about that. I mixed up the names there.
