### ISSUE TITLE
MailScanner not sending notice for SPAM.

### ISSUE THREAD

**Issue by Lungape** [MailScanner/v5#469]
Hi guys, I deployed the MailScanner but I am not receiving any notice for spam, only for virus and files with the bad format.
In the past, I always received notices for each spam on the postmaster's inbox account.
Notice is enabled on the MailScanner conf file.
![Screen Shot 2020-04-27 at 18 21 52](https://user-images.githubusercontent.com/64315842/80401436-3ac98e80-88b4-11ea-91fe-49812d178025.jpg)

In the example below, i received the notice emails for the status other, but not for the spam's

![Screen Shot 2020-04-27 at 18 20 27](https://user-images.githubusercontent.com/64315842/80401472-4ae16e00-88b4-11ea-8e1a-e2e5f348d2e6.jpg)

Here is the info about my setup.

![Screen Shot 2020-04-27 at 18 21 06](https://user-images.githubusercontent.com/64315842/80401568-73696800-88b4-11ea-8468-825af3052578.jpg)

**Comment by shawniverson** [comment]
What is your Spam Actions setting?  I don't think the Send Notices is applicable for spam, but I will need to check the code to verify that.

**Comment by msapiro** [comment]
Possibly this is a MailWatch issue.

**Comment by shawniverson** [comment]
I know you can do this in MailScanner...

Spam Actions = store forward postmaster@example.com

**Comment by shawniverson** [comment]
In MailWatch, you can have a daily report sent to the postmaster, just depends on whether you want a summary or each one as they happen I think.

**Comment by Lungape** [comment]
Hi,
My spam action is to store, so I can release or not using the MailWatch Web interface.
The option you suggested as store + forward works fine, I already tested, but I receive a full copy of the user email and I do not want to see the user email.
The MailWatch daily report is working perfectly too.

What I need is to receive a notice or report every time spam occurs so I can check and do not need to wait for the daily report.

Another possibility is to have a report every X hours, is this a feature in the MailScanner or MailWatch?
Maybe with some cron job to get only the last X hours?


If I can do this with MailWatch is fine too, but I have a vague idea that in the past MailScanner does this, but maybe I am wrong.

**Comment by msapiro** [comment]
I think the notices you want that you have seen in the past must come from MailWatch. The MailWatch issue tracker is at https://github.com/mailwatch/MailWatch/issues and the mailing list is at http://lists.sourceforge.net/lists/listinfo/mailwatch-users

**Comment by Lungape** [comment]
I know where is the MailWatch issues tracker and I searched there for an issue regarding what I have and I did not found, do you know if there is?

**Comment by msapiro** [comment]
I didn't say I knew this was an issue in the MailWatch tracker. What I was trying to say is I think yours is a MailWatch issue and you will probably have more success in solving it by using MailWatch resources rather than MailScanner resources.

It might be related to MailScanner in that something that MailWatch is looking for in MailScanner has changed, but there again, only MailWatch people would be equiped to understand that.

**Comment by shawniverson** [comment]
So, I perused the code just to make sure.  Definitely not sent for spam using just MailScanner, unless you wrote you own custom function.

```
      $reasons{virusinfected}     = 1 if $message->{virusinfected};
      $reasons{filenameinfected}  = 1 if $message->{nameinfected};
      $reasons{otherinfected}     = 1 if $message->{otherinfected};
      $reasons{sizeinfected}      = 1 if $message->{sizeinfected};
      $reasons{passwordprotected} = 1 if $message->{passwordprotected};
      $reasons{nonpasswordprotected} = 1 if $message->{nonpasswordprotected};
```
