### ISSUE TITLE
Build does not complete on Ubuntu 18

### ISSUE THREAD

**Issue by hennaboy** [MailScanner/v5#471]
Running ./install.sh from the nix build I am selecting Yes for install of cpan modules.

After 30mins I return to the build looks good where the prompt entries start with 84 entry prompts where it proceeds to reinstall the cpan modules and returns back to the same prompt section.

The install never actually completes. There is no /etc/MailScanner or any other directories.

**Comment by hennaboy** [comment]
If I select no for installation of cpan modules it lists how many didn't get installed even though selecting Y takes 30mins installing the modules!

Selecting n then installs to /etc/MailScanner but /var/spool/MailScanner is missing.

**Comment by shawniverson** [comment]
On Ubuntu 18, use the Debian package, not the generic one.

**Comment by hennaboy** [comment]
Yes. Works. Thanks
