### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by lifzgreat** [MailScanner/v5#479]
I added a few lines to do this locally but it'd be awesome if it was included by default. When the from field is too long, it cuts it off, which is great for visual continuity. But if you have the config set to do that, it'd be nice if there was a tooltip so you can still see the full from field without going into the email itself. Oftentimes the domain part of the from field can really help determine if it's spam or not.

I added this where it sets up the rows (in the 'from_address' case):
`if (strlen($row[$f]) > FROMTO_MAXLEN) $tooltips[$f] = $row[$f];`

I edited this where it outputs the rows:
`echo ' <td' . ($tooltips[$f] ? " title='$tooltips[$f]' " : "") . '>' . $row[$f] . '</td>' . "\n";`

**Comment by shawniverson** [comment]
I think you may want to post this to the MailWatch instead, a front-end using MailScanner.

**Comment by lifzgreat** [comment]
Oops, sorry, I will go do that.
