### ISSUE TITLE
Very long filenames are good signs of attacks against Microsoft ... mistakenly triggered?

### ISSUE THREAD

**Issue by ovizii** [MailScanner/v5#48]
Mailscanner blocked an attachment with: 

> MailScanner: Very long filenames are good signs of attacks against Microsoft e-mail packages (Reg No -2016%2.png)

so I checked: /etc/MailScanner/filename.rules.conf and the rule triggered is:

> #Due to a bug in Outlook Express, you can make the 2nd from last extension
> #be what is used to run the file. So very long filenames must be denied,
> #regardless of the final extension.
> deny .{150,} Very long filename, possible OE attack Very long filenames are good signs of attacks against Microsoft e-mail packages

not sure how a file name of Reg No -2016%2.png triggers that, is it the % character maybe?

**Comment by msapiro** [comment]
The name in the attachment warning message is not the whole name. Look in the mail log for a message like

...  MailScanner[9318]: Filename Checks: Very long filename, possible OE attack (...

Which will give the actual file name, or look at the original message in MailScanner's quarantine.

**Comment by ovizii** [comment]
ah, found it, sorry you are right this was only a short part of the total file name.
