### ISSUE TITLE
Mailscanner 5.3.2 installation

### ISSUE THREAD

**Issue by janarzz** [MailScanner/v5#488]
Hey, i have problem Mailscanner 5.3.2 install on ubuntu server 20.04
Everything seems like ok, but after install i see this error:
cp: stat './var' failed No such file or directory.
When i tryng to enable mailscanner, then i get error message:
Failed to start mailscanner.service: Unit mailscanner.service not found.
I use php7.4, MariaDB version 10.3.22

I need help :) Thanks..

**Comment by shawniverson** [comment]
Which MailScanner package did you install?

Also, MailScanner doesn't use php.

**Comment by shawniverson** [comment]
For Ubuntu, use the MailScanner-5.3.3-1.noarch.deb instead and run /usr/sbin/ms-configure after installing.

**Comment by janarzz** [comment]
Many thans...seems like works ;)
