### ISSUE TITLE
mailscanner filerules 

### ISSUE THREAD

**Issue by janarzz** [MailScanner/v5#493]
Hey,
i have problem with mailscanner filerules.
Mailscanner block .dat file. When i add exception to file filename.rules.conf, then nothing happend - still block.
I dont know, when i send .cdr file, then i see there .dat file...?
I send pic to:
https://pilv.addit.ee/index.php/s/nwLyqpKAjKF2yg7

Please help.

**Comment by msapiro** [comment]
The files in your screenshot `No DOS programs allowed` are being blocked by filetype rules, not filename rules.  I.e., byt the file type as reported by the `file` command.

**Comment by janarzz** [comment]
What i can do ?

**Comment by shawniverson** [comment]
Allow "DOS programs" in your archive filetype rules from trusted sources with a ruleset.

**Comment by janarzz** [comment]
I want allow only .dat file. No all DOS programs files.

**Comment by shawniverson** [comment]
Well, since this particular .dat file looks like a DOS program, that isn't exactly easy to overcome.

**Comment by msapiro** [comment]
To elaborate on Shawn's comment, the `file` command does not identify this file as a DOS program because of the .dat extension, but rather because of the file content. What's in this file? What happens if you mail an ordinary text file with a .dat extension?

**Comment by janarzz** [comment]
Wierd..i cannot open .dat file.
I want open only Corel .cdr file.
https://pilv.addit.ee/index.php/s/PPSM9YoPz65amtJ

**Comment by janarzz** [comment]
Wierd..i look two different corel file content - they are exactly the same
1 file send correct, but anothernot send.

**Comment by shawniverson** [comment]
@janarzz Do you have samples we can examine?

**Comment by janarzz** [comment]
Hi,
this is a corel file that cannot be sent.
https://pilv.addit.ee/index.php/s/EQaqHZxsrcqenpc

**Comment by shawniverson** [comment]
Going to add an option to MailScanner to exclude .dat files in archives from this specific detection.  This is a common problem with .dat files inside of Office documents as well.  These are false positives yet are completely indistinguishable from an executable with regard to file magic.

**Comment by janarzz** [comment]
No solution this problem ?

**Comment by shawniverson** [comment]
The only solution at this time is to disable the DOS Executable rule as previously suggested, wait for me or someone to add an enhancement.

**Comment by janarzz** [comment]
Ok, thanks.
