### ISSUE TITLE
MailScanner PID file should be placed in /run/ instead of /var/run/

### ISSUE THREAD

**Issue by Skywalker-11** [MailScanner/v5#494]
[FHS 3.0](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf) deprecated `/var/run`. Instead the PID files should be placed/referenced from `/run/`.

Systemd also complains about this in kernel log (Debian Buster):
`systemd[1]: /lib/systemd/system/mailscanner.service:18: PIDFile= references path below legacy directory /var/run/, updating /var/run/MailScanner.pid → /run/MailScanner.pid; please update the unit file accordingly.`

**Comment by shawniverson** [comment]
Updating the unit file, leaving init and codebase on /var/run for compatibility with older FHS standard for now.
