### ISSUE TITLE
Scan Messages

### ISSUE THREAD

**Issue by jcbenton** [MailScanner/v5#5]
_From @alvarosplit on December 28, 2015 9:29_

Hi,

I'm writing a CustomFunction to check the "Scan Messages" value in a
database:

Scan Messages = &ScanMsgs

but  the function is executed two times for each message:

Sep 23 17:15:05 MailScanner[22554]: 4694D2180A7.AC573: ScanMsgs checking.
Sep 23 17:15:05 MailScanner[22554]: 4694D2180A7.AC573: ScanMsgs checking.

Debugging the code, I've found 2 calls to that "Scan Messages" function:

[+] Message.pm, new (constructor, called by Postfix.pm's CreateBatch
function):

  # Decide if we want to scan this message at all
  $this->{scanmail} = MailScanner::Config::Value('scanmail', $this);
  if ($this->{scanmail} =~ /[12]/) {
    $this->{scanmail} = 1;
  } else {
    # Make sure it is set to something, and not left as undef.
    $this->{scanmail} = 0;
  }
  if ($this->{scanmail} !~ /1/) {
    $this->{scanvirusonly} = 1;
  } else {
    $this->{scanvirusonly} = 0;
  }

[+] Postfix.pm, in CreateBatch function:

```
    if (MailScanner::Config::Value("scanmail", $newmessage) =~ /[12]/ ||
        MailScanner::Config::Value("virusscan", $newmessage) =~ /1/ ||
        MailScanner::Config::Value("dangerscan", $newmessage) =~ /1/) {
      $newmessage->NeedsScanning(1);
```

So in that Postfix.pm's code, insted of read the value of $newmessage's
variable "scanmail", that was created in Message.pm code that I've
pasted before, it calls again to MailScanner::Config::Value function
that searchs again for that value (if is a ruleset it will look for the
rule in the rules file or if it's a function, like in my configuration,
it will execute it one more time).
Changing that code by:

```
if ($newmessage->{"scanmail"} =~ /[12]/ ||
  $newmessage->{"virusscan"} =~ /1/ ||
  $newmessage->{"dangerscan"} =~ /1/) {
$newmessage->NeedsScanning(1);
```

it reads the value from the variable filled by Message.pm, and doesn't
call again to the function.

_Copied from original issue: MailScanner/v4#43_

**Comment by jcbenton** [comment]
Sorry for the slow reply. Have you posted this to the mailing list? I can implement the changes, but they would have to be thoroughly tested.

**Comment by jcbenton** [comment]
_From @alvarosplit on January 13, 2016 8:54_

Yes, I've posted it in the mailing list some months ago:

http://lists.mailscanner.info/pipermail/mailscanner/2015-September/102613.html

**Comment by jcbenton** [comment]
Would you be kind enough to post this issue in the v5 branch? We are not ignoring you. We have been busy packaging v5. I want to address this in the v5 branch.

https://github.com/MailScanner/v5/issues

**Comment by jcbenton** [comment]
Never mind. I was able to move it with an online tool.

**Comment by alvarosplit** [comment]
Hi,
I've ~30 servers running MailScanner with the patch that I proposed some monts ago, and I can confirm that is working fine.

**Comment by jcbenton** [comment]
implemented
