### ISSUE TITLE
Can MSMilter/MailScanner run in foreground with no syslog?

### ISSUE THREAD

**Issue by pidydx** [MailScanner/v5#501]
It appears that MailScanner can run in the foreground, but MSMilter does not appear to have a similar option and both appear to force syslog logging.   Is it possible to run both of these in the foreground with logging only to stdout?  I am working on a Docker/Kubernetes install and this would allow for a much cleaner container/pod setup.

**Comment by shawniverson** [comment]
I think this would take a bit of work to accomplish. I might be able to add a foreground option and modify the logger in MailScanner to use stdout. I'll continue looking at this.

**Comment by pidydx** [comment]
Thanks!  The way I am approaching this is to have a single container that has all the necessary components for Mailscanner/Mailwatch/clamav/cron/nginx, but entry points configured so that each container adheres to running one process with stdout/stderr outputs and combine them in a k8s pod.

**Comment by shawniverson** [comment]
@pidydx PR merged in master.  Please test using ```Run in Foreground = yes``` for both MSMilter and MailScanner

**Comment by shawniverson** [comment]
@pidydx Please see PR #513

**Comment by pidydx** [comment]
Hey! Finally getting around to trying this again.  The changes seem to appear in the source code for 5.3.4-3, but not in the deb or nix packages.

**Comment by msapiro** [comment]
They're in the files which I installed from MailScanner-5.3.4-3.noarch.deb

**Comment by pidydx** [comment]
wget https://github.com/MailScanner/v5/releases/download/5.3.4-3/MailScanner-5.3.4-3.noarch.deb
mkdir temp
dpkg-deb -R MailScanner-5.3.4-3.noarch.deb temp/
grep foreground temp/usr/sbin/MSMilter

I extracted the nix, and rpms as well and the MSMilter in those packages doesn't match the one in the source download for 5.4.3-3, but if I run the build myself it produces packages with the correct MSMilter. 

Is there another source for the MailScanner-5.3.4-3.noarch.deb?

**Comment by msapiro** [comment]
I can't explain what's going on. It's possible that I built the .deb from my clone of the GitHub branch, but I just downloaded https://github.com/MailScanner/v5/releases/download/5.3.4-3/MailScanner-5.3.4-3.noarch.deb and `cmp`d it to my MailScanner-5.3.4-3.noarch.deb and they are identical, yet I get the same result as you from
```
mkdir temp
dpkg-deb -R MailScanner-5.3.4-3.noarch.deb temp/
grep foreground temp/usr/sbin/MSMilter
```
but on my installation, I get
```
grep foreground /usr/sbin/MSMilter 
    my($filename, $foreground) = @_;
    if ($foreground) {
        MailScanner::Log::Configure($logbanner, 'foreground');
    my $RunInForeground = MailScanner::Config::QuickPeek($ConfFile, 'runinforeground');
```

**Comment by pidydx** [comment]
I extracted the github hosted deb and built another deb from the source tar and diffed the extracted directories and the only differences are the 3 files from PR513.  Something strange happened with whatever process built the deb/rpm/*nix packages for that one set of changes to be missing. 🤷🏻‍♂️

**Comment by pidydx** [comment]
"Well, what did I do I wonder?"

Whether it is something that did work or something that didn't work it always alarms me just how much technology operates on this question. 🤣
