### ISSUE TITLE
Generic AV detects malware, but infected messages are still delivered

### ISSUE THREAD

**Issue by claudioquincy** [MailScanner/v5#503]
Hi and thanks for the good work.
I made a generic AV that basically pipes attachments though a sandbox and wait for result.
When a malware is found mailscanner does not block it, while if I switch to Clamd infected messages are normally quarantined.

I can read these lines in logs, without errors.

```
Sandy::INFECTED::SBX::./226A6008B.A7D6D/neicar-standard-antivirus-test-file-microsoft-excel-macro-cmd-echo.xls
Virus Scanning: Sandy found 1 infections
```

So everything looks fine, except that malware is still delivered!

**Comment by shawniverson** [comment]
Take a look at this setting...

```Non-Forging Viruses = Joke/ OF97/ WM97/ W97M/ eicar Zip-Password```
