### ISSUE TITLE
Mailscanner How to check bad Hyperlinks behind Clickbutton

### ISSUE THREAD

**Issue by FiFFiTheLucky** [MailScanner/v5#509]
Hey there

We have the  problem that our mailscanner does not mark a hyperlink as a phishing link, when it is covered with another "CONFIRM Button".
The link behind the "Confirm button" ist listed in the bad.phishing.sites.conf.
The link is: firebasestorage.googleapis.com

Thanks 4 helping

![4GithubMailscanner](https://user-images.githubusercontent.com/73994827/98232394-e5a2bf80-1f5d-11eb-81b3-dcecb593dcda.JPG)

**Comment by FiFFiTheLucky** [comment]
Hello out there
Today we received another email in which the link was not recognized as malicious again. How can you set up the mail scanner so that it also recognizes such links?
Thank you very much for your help
![ggithub2](https://user-images.githubusercontent.com/73994827/99804369-322ff280-2b3b-11eb-8402-dfa5b7d93716.JPG)

**Comment by msapiro** [comment]
In the case of the links in the message at https://github.com/MailScanner/v5/issues/509#issuecomment-731165154, you'd have to add  user-images.githubusercontent.com to your /etc/MailScanner/phishing.bad.sites.custom file, but that would result in all links from that site being flagged.

**Comment by shawniverson** [comment]
I'm taking a closer look at this and running some tests.

**Comment by shawniverson** [comment]
I haven't decided if this is a bug or just a something that MailScanner hasn't handled.  I am tagging it as confirmed and am continuing to look into it.  Buttons, images, generic words like Confirm, and so forth hide phishing just like any other link and I believe that Find Phishing Fraud should be analyzing the href regardless and running it against PhishTank.  The first sample above is definitely in the phishing.bad.sites.conf.  An explicit link to the same domain gets flagged, but the "Confirm" button does not.

**Comment by shawniverson** [comment]
This is a regression after comparing to older MailScanner code.  I am preparing a fix.

**Comment by FiFFiTheLucky** [comment]
Thank you 👍
