### ISSUE TITLE
MailScanner: Suspected QP DOS checks failed could not read file

### ISSUE THREAD

**Issue by lifzgreat** [MailScanner/v5#517]
The issue I'm reporting appears to be the same issue as this issue from the mailscanner mailing list: http://lists.mailscanner.info/pipermail/mailscanner/2020-July/106228.html

On some read receipts, MailScanner marks them with:

> Other Infection: Y
> Report: MailScanner: Suspected QP DOS checks failed could not read file

We sent an email out today with a receipt request and 44 came back. Of those, 42 were fine but MailScanner blocked 2 with the above information. On both of those, the attachment is partialMessage.bin. Let me know what else is needed to help figure this out!

![2020-12-23 14_10_29-MailWatch for MailScanner - Message Detail AABB5120343 AB52D](https://user-images.githubusercontent.com/5751658/103029995-e6e97500-4528-11eb-8645-1ffc80fe64c3.png)
![2020-12-23 14_10_23-MailWatch for MailScanner - Message Viewer](https://user-images.githubusercontent.com/5751658/103029994-e650de80-4528-11eb-9d72-4ef222407367.png)

**Comment by shawniverson** [comment]
This should already be fixed in version 5.3.4-3

**Comment by lifzgreat** [comment]
Is it just by turning it off? I was thinking that's not the best work
around because what if it's really a DOS?

**Comment by shawniverson** [comment]
No it includes a fix so you shouldn't have to turn it off.

**Comment by lifzgreat** [comment]
Ok I'll have to check that out. It's not released yet for the standard
debian so I'll have to manually install that, thanks for letting me know.

**Comment by lifzgreat** [comment]
Looks like it's working! Thanks for your help.
