### ISSUE TITLE
ClamAV clamd does not run after installing MailScanner on Ubuntu 20.04

### ISSUE THREAD

**Issue by dbworth** [MailScanner/v5#529]
**Issue:** 
ClamAV does not run after MailScanner installs it, using Ubuntu + Postfix. 

I check the log file: 
`/var/log/mail.log`
there is an error message: 
`Clamd::ERROR:: UNKNOWN CLAMD RETURN ./lstat() failed: Permission denied. ERROR :: /var/spool/MailScanner/incoming/43989`

**Software:** 
Ubuntu 20.04.2 LTS
Postfix 3.4.13
MailScanner-5.3.4-3.noarch.deb

**More details:** 

ClamAV `clamd` runs as user `clamav` 
SpamAssassin `spamd` runs as user `root` 
`MailScanner` and `MSMilter` run as user `postfix` 

They are in a group called `mtagroup` 

After rebooting the server, permissions on the incoming directory are: 
`drwxrwx--- root mtagroup /var/spool/MailScanner/incoming/`

You can test this issue from the terminal by doing this: 
```
cd /var/spool/MailScanner/incoming
clamdscan   <-- Permission denied
```

**Comment by dbworth** [comment]
**My solution:** 
I had to edit the AppArmor file for ClamAV. 

`nano /etc/apparmor.d/usr.sbin.clamd`

Add these 2 lines: 
```
/var/spool/MailScanner/** rw,
/var/spool/MailScanner/incoming/** rw,
```

Reload the config: 
`/etc/init.d/apparmor reload`

`service clamav-daemon restart`

Test it from the terminal: 
```
cd /var/spool/MailScanner/incoming
clamdscan   <-- Prints "OK" 
```

**Question:** 
If the MailScanner installer is going to install ClamAV on Ubuntu, should it check for an AppArmor config? 

For example, Amavis automatically edits the `usr.sbin.clamd` file.

**Comment by msapiro** [comment]
How did you install MailScanner? The normal install of the .deb adds /etc/apparmor.d/local/usr.sbin.clamd with content
```
/var/spool/MailScanner/incoming/** krw,
/var/spool/MailScanner/incoming/** ix,
```

**Comment by msapiro** [comment]
I seem to recall an issue here. I have in  /etc/apparmor.d/usr.sbin.clamd 
```
  # Site-specific additions and overrides. See local/README for details.
   #include <local/usr.sbin.clamd>
```
and I think I had to edit that as the original contained a syntactically invalid `include`, but if that's the case, it's a Debian/Ubuntu issue, not MailScanner.

**Comment by dbworth** [comment]
Thanks @msapiro I couldn't find that before. 

I see the code for MailScanner to modify the AppArmor configuration is here: 
https://github.com/MailScanner/v5/blob/576d70217984fcf3f171050c827396a1fce81c50/debian/usr/sbin/ms-configure#L693
The script will add 2 lines to this file: 
`/etc/apparmor.d/local/usr.sbin.clamd`
which is included by: 
`/etc/apparmor.d/usr.sbin.clamd`

I did some more tests and couldn't re-produce my problem with a remove+install or a fresh install of Ubuntu, therefore closing my ticket  :-)
