### ISSUE TITLE
phishing.bad.sites not updated

### ISSUE THREAD

**Issue by Ressy66** [MailScanner/v5#537]
It seems even on a fresh install phishing.bad.sites no longer gets updated, the rules seem very ancient
update fails even a manual run fails:

wget http://phishing.mailscanner.info/phishing.bad.sites.conf.gz
--2021-03-26 16:19:37--  http://phishing.mailscanner.info/phishing.bad.sites.conf.gz
Resolving phishing.mailscanner.info (phishing.mailscanner.info)... 188.166.22.71
Connecting to phishing.mailscanner.info (phishing.mailscanner.info)|188.166.22.71|:80... connected.
HTTP request sent, awaiting response... 405 Not Allowed
2021-03-26 16:19:37 ERROR 405: Not Allowed.

and for the hell of it tried https

 wget https://phishing.mailscanner.info/phishing.bad.sites.conf.gz
--2021-03-26 16:20:03--  https://phishing.mailscanner.info/phishing.bad.sites.conf.gz
Resolving phishing.mailscanner.info (phishing.mailscanner.info)... 188.166.22.71
Connecting to phishing.mailscanner.info (phishing.mailscanner.info)|188.166.22.71|:443... failed: Connection refused.

**Comment by shawniverson** [comment]
I'm having trouble reproducing this issue.

**Comment by Ressy66** [comment]
well then its  time for us to find alternatives because it dont work for me, still.
wget https://phishing.mailscanner.info/phishing.bad.sites.conf.gz
--2021-05-08 23:02:53--  https://phishing.mailscanner.info/phishing.bad.sites.conf.gz
Resolving phishing.mailscanner.info (phishing.mailscanner.info)... 188.166.22.71
Connecting to phishing.mailscanner.info (phishing.mailscanner.info)|188.166.22.71|:443... failed: Connection refused.

**Comment by Ressy66** [comment]
https://www.zonemaster.fr/result/641acb5805edbfed    

perhaps this is why.... your DNS is screwed

**Comment by msapiro** [comment]
It is not a DNS issue. Your wget command properly resolved the host to IP 188.166.22.71. There are two issues.

You can't get https://phishing.mailscanner.info/phishing.bad.sites.conf.gz - it has to be http, not https. phishing.mailscanner.info doesn't listen on port 443.

Also, it appears that with wget, you need `--user-agent="msv5 Update Script v0.2.0"` or you get a `405 Not Allowed` response, although this doesn't seem to be the case with curl.

Are you using the  /usr/sbin/ms-update-phishing script which provides all the correct options and does work?
