### ISSUE TITLE
False positive in http://phishing.mailscanner.info/phishing.bad.sites.conf

### ISSUE THREAD

**Issue by herrbischoff** [MailScanner/v5#538]
I don't know if this is the proper way to flag this. Due to a lack of other mean of contact, I'm filing this issue here.

The list http://phishing.mailscanner.info/phishing.bad.sites.conf currently contains an entry for `cdn.shopify.com`. This is a false positive and breaks all Shopify shops completely if used as a blocklist. It is exactly what the subdomain name implies: the Shopify CDN.

**Comment by shawniverson** [comment]
This list is provided by Phishtank and should be addressed with them.  It can be addressed individually by placing an entry in phishing.safe.sites.custom and running ms-update-phishing.
