### ISSUE TITLE
Eset not working in newer version

### ISSUE THREAD

**Issue by flagmonkey** [MailScanner/v5#540]
Current versions of Eset don't work with the current MailScanner anymore, because the binary "odscan" in v8.0.375.0 does not output "threat" when a virus is found. Instead, the "Threat" itself is written to a line with the word "result="

`name="/tmp/eicar.txt", result="Eicar test file", action="retained", info=""
`

Can you update your SweepViruses.pm for newer versions of Eset?

We changed this line in our installation to:

`return 0 if $line !~ m/result/i;
`

**Comment by markovp** [comment]
Hi flagmonkey,

could you be so kind and show all the changes you made  that new ESET odscan work with MailScanner. Thanks.

probably we have to change:

/etc/MailScanner/virus.scanners.conf
------------------------------------------------------------------------------------
esets                   /usr/lib/MailScanner/wrapper/esets-wrapper                      /opt/eset/efs/bin


/usr/lib/MailScanner/wrapper/esets-wrapper (firs create new profile "EFA" in ESET web GUI)
------------------------------------------------------------------------------------
ScanOptions="-s --profile=EFA"
PackageDir=$1
shift
Prog=odscan

if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x ${PackageDir}/$Prog ] && exit 0
  exit 1
fi

exec sudo ${PackageDir}/$Prog $ScanOptions "$@"


/usr/share/MailScanner/perl/MailScanner/SweepViruses.pm (line 2057)
------------------------------------------------------------------------------------
return 0 if $line !~ m/result/i;    


or maybe something else ...

**Comment by markovp** [comment]
After all this changed I still have problem when I start MailScanner lint (test)

Cannot lock /var/spool/MailScanner/incoming/Locks/esetsBusy.lock, No such file or directory at /usr/share/MailScanner/perl/MailScanner/SweepViruses.pm line 844

What I have to change here ?

**Comment by markovp** [comment]
Hi

I'm very interested in this to work. I can test or debug this if someone put me in right direction. What and where to look, How to debug ...
