### ISSUE TITLE
False Positive on forms.gle

### ISSUE THREAD

**Issue by bjc112** [MailScanner/v5#542]
Quote: "MailScanner has detected definite fraud in the website at "forms.gle". Do not trust this website: https://forms.gle/[redacted]"

**Comment by msapiro** [comment]
In the update as of  Wed, 26 May 21 08:15:01 -0400, `forms.gle` is not in phishing.bad.sites.conf and `*.forms.gle` is in phishing.safe.sites.conf.

**Comment by bjc112** [comment]
YEAH...but it still says it's definite fraud
![image](https://user-images.githubusercontent.com/84854186/119683459-aa8cae80-be11-11eb-9003-d83ebc422a1a.png)

**Comment by msapiro** [comment]
What is the `Build Time:` entry around line 7 in /etc/MailScanner/phishing.bad.sites.conf?

**Comment by bjc112** [comment]
no idea wut ur talking about, 
I got the email (from some I know well) and mail scanner said it was fraud (the link)

**Comment by msapiro** [comment]
The data in the MailScanner that inserted that fraud warning is not up to date.
