### ISSUE TITLE
MailScanner crashing and quarantining emails.

### ISSUE THREAD

**Issue by pidydx** [MailScanner/v5#546]
I am getting seemingly random errors of "HTML disarming died, status = 13 at /usr/share/MailScanner/perl/MailScanner/Message.pm line 7517."

The only thing they seem to have in common is a "Content Checks: Detected and have disarmed denialofservice" (Some also include other things like web bug or script) before the "Quarantined message <MSG_ID> as it caused MailScanner to crash several times at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8400.
" logs.

This leads to emails being quarantined and deleted from processing.  However, these emails do not show up in MailWatch quarantines for release and have to be manually retrieved.

Since none of these messages have actually been a problem and it is a bigger problem to keep losing them like this is there a way to fail open/ignore this?  I found the following settings, but the documentation suggests that not quarantining will just be a silent failure, and ignoring denial of service isn't clear if it will skip the check and deliver the mail or if it will also silently drop the messages.

Quarantine Denial Of Service = yes
Ignore Denial Of Service = no

**Comment by shawniverson** [comment]
Ignore Denial Of Service will deliver the mail if disarming the HTML causes the forked MailScanner worker to crash.

**Comment by pidydx** [comment]
Thanks!

From what little I could find it sounds like a few others have experienced this and status = 13 deaths are related to some kind of permissions issue when reading from the pipe, but it seems to be a pretty rare and intermittent thing.

**Comment by shawniverson** [comment]
I have a new theory as to why this is happening, I think it is a possible race between the parent and child. I'm going to study this an see if I can come up with a fix to prevent the child from immediately closing the pipe before the parent has a chance to read the pipe.

**Comment by Fonant** [comment]
I'm afraid to say this fix doesn't seem to resolve the problem. I've manually patched MailScanner/Message.pm and restarted MailScanner, but still seeing `HTML disarming died, status = 13`

**Comment by shawniverson** [comment]
Reopening.  The child is exiting and automatically closing the pipe, then the parent is attempting to close the pipe again (race condition).  I will add a condition not to attempt to close the pipe upon normal exit of the child.

**Comment by Fonant** [comment]
That new fix seems to work fine for me on the one server that was getting a lot of "Quarantined message xxxx as it caused MailScanner to crash several times" errors.  I patched my existing installation, rather than trying the complete v5.4.2-3beta release.
