### ISSUE TITLE
Can't locate strict.pm

### ISSUE THREAD

**Issue by surdet** [MailScanner/v5#55]
I have this error message while I start MailScanner but it still working.

" Can't locate strict.pm:    /usr/share/MailScanner/perl/strict.pm: Permission denied at /usr/sbin/MailScanner line 27.
BEGIN failed--compilation aborted at /usr/sbin/MailScanner line 27.
MailScanner restarted with process id 2209 "

There are no /usr/share/MailScanner/perl/strict.pm  file in MailScanner-5.0.3-7.deb.tar.gz  package file.
 
# MailScanner -V
Running on
Linux ip-172-31-10-115 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
This is Perl version 5.022001 (5.22.1)

This is MailScanner version 5.0.3
Module versions are:
1.01    AnyDBM_File
1.56    Archive::Zip
0.39    bignum
1.36    Carp
2.068   Compress::Zlib
1.125   Convert::BinHex
0.18    Convert::TNEF
2.158   Data::Dumper
2.30    Date::Parse
1.04    DirHandle
1.13    Fcntl
2.85    File::Basename
2.30    File::Copy
2.02    FileHandle
2.09    File::Path
0.2304  File::Temp
0.92    Filesys::Df
3.69    HTML::Entities
3.72    HTML::Parser
3.69    HTML::TokeParser
1.35    IO
1.16    IO::File
1.15    IO::Pipe
2.13    Mail::Header
1.9997  Math::BigInt
0.2608  Math::BigRat
3.15    MIME::Base64
5.507   MIME::Decoder
5.507   MIME::Decoder::UU
5.507   MIME::Head
5.507   MIME::Parser
3.13    MIME::QuotedPrint
5.507   MIME::Tools
0.17    Net::CIDR
1.26    Net::IP
0.19    OLE::Storage_Lite
1.07    Pod::Escapes
3.29    Pod::Simple
1.53_01 POSIX
1.41    Scalar::Util
2.018   Socket
2.53_01 Storable
1.5     Sys::Hostname::Long
0.33    Sys::Syslog
1.51    Test::Pod
1.001014        Test::Simple
1.9726  Time::HiRes
1.02    Time::localtime

Optional module versions are:
2.04    Archive::Tar
0.39    bignum
2.010   Business::ISBN
20140910.003    Business::ISBN::Data
1.23    Data::Dump
1.835   DB_File
1.50    DBD::SQLite
1.634   DBI
1.17    Digest
1.03    Digest::HMAC
2.54    Digest::MD5
2.13    Digest::SHA1
1.01    Encode::Detect
0.17010 Error
0.280221        ExtUtils::CBuilder
3.28    ExtUtils::ParseXS
2.45    Getopt::Long
0.80    Inline
1.08    IO::String
1.10    IO::Zlib
2.28    IP::Country
missing Mail::ClamAV
3.004001        Mail::SpamAssassin
v2.009  Mail::SPF
1.999001        Mail::SPF::Query
0.422   Module::Build
0.21    Net::CIDR::Lite
0.81    Net::DNS
v0.003  Net::DNS::Resolver::Programmable
0.65    Net::LDAP
 4.078  NetAddr::IP
1.967013        Parse::RecDescent
missing SAVI
3.35    Test::Harness
2.02    Test::Manifest
2.03    Text::Balanced
1.71    URI
0.9909  version
1.15    YAML
Thank you.

**Comment by msapiro** [comment]
There is something amiss with your perl installation. The error stems from
```
use strict;
no strict 'subs';
```
in /usr/sbin/MailScanner. These pragmas invoke strict.pm which should be found at /usr/share/perl/5.xx.x/share.pm or wherever your perl installation is. This should be included in any perl installation. It is not an "extra" module and is not installed by MailScanner. See http://perldoc.perl.org/perlmodlib.html#Pragmatic-Modules.

**Comment by surdet** [comment]
Thank you for your suggestion. I have tried to find a solution on the internet but I have no luck.  I can run a perl -e 'use strict; print "ok"' command without issue and I run, 
```
$ perl -wle'print for @INC'
/etc/perl
/usr/local/lib/x86_64-linux-gnu/perl/5.22.1
/usr/local/share/perl/5.22.1
/usr/lib/x86_64-linux-gnu/perl5/5.22
/usr/share/perl5
/usr/lib/x86_64-linux-gnu/perl/5.22
/usr/share/perl/5.22
/usr/local/lib/site_perl
/usr/lib/x86_64-linux-gnu/perl-base
.
```
And I find a strict.pm with
```
~$ find / -name "strict.pm"
/usr/share/perl/5.22.1/strict.pm
/usr/lib/x86_64-linux-gnu/perl-base/strict.pm
```
So I think the path is wrong.  I add
```
#       Updated:        Jerry Benton <mailscanner@mailborder.com>
#                               26 APR 2016
use lib "/usr/share/perl/5.22.1";
use strict;
no strict 'subs';
use POSIX;
require 5.005;
```
 in /usr/sbin/MailScanner and run, I got a new Error,
```
# /etc/init.d/mailscanner restart
Restarting MailScanner ...

Currently you are using no virus scanners.
This is probably not what you want.

In your /etc/MailScanner/MailScanner.conf file, set
    Virus Scanners = clamav
Then install it with your package manager or download it directly from
http://www.clamav.net

Can't locate lib.pm:    /usr/share/MailScanner/perl/lib.pm: Permission denied at /usr/sbin/MailScanner line 26.
BEGIN failed--compilation aborted at /usr/sbin/MailScanner line 26.
MailScanner restarted with process id 19135
```
So I find a lib.pm
```
~# find / -name "lib.pm"
/usr/lib/x86_64-linux-gnu/perl-base/lib.pm
/usr/lib/x86_64-linux-gnu/perl/5.22.1/lib.pm
```
I add
```
#       Updated:        Jerry Benton <mailscanner@mailborder.com>
#                               26 APR 2016
use lib "/usr/share/perl/5.22.1";
use lib "/usr/lib/x86_64-linux-gnu/perl/5.22.1";
use strict;
no strict 'subs';
use POSIX;
require 5.005;

```
in  /usr/sbin/MailScanner and run, I got the same Error,
```
Can't locate lib.pm:    /usr/share/MailScanner/perl/lib.pm: Permission denied at /usr/sbin/MailScanner line 26.
BEGIN failed--compilation aborted at /usr/sbin/MailScanner line 26.
MailScanner restarted with process id 24888
```
Can you give me a suggestion to fix the problem?

**Comment by msapiro** [comment]
First remove your added 'use lib ...' lines.

Then run 'which perl' and compare that path to the path in the shebang line in /usr/sbin/MailScanner.

It seems you may have more than one perl installation. It looks like the perl you invoke with 'perl' which is what 'which perl' will show is good, but /usr/sbin/MailScanner may be invoking a different one.

**Comment by surdet** [comment]
Thank you for your advice. I have compared but It is the same path.

```
# which perl
/usr/bin/perl
# exit
logout
$ which perl
/usr/bin/perl
$ head /usr/sbin/MailScanner
#!/usr/bin/perl -U -I /usr/share/MailScanner/perl
#
#   MailScanner - SMTP Email Processor
#   Copyright (C) 2002  Julian Field
```

**Comment by msapiro** [comment]
It seems when you manually invoke /usr/bin/perl, there is no problem with 'use strict', but when /usr/sbin/MailScanner invokes it, there is a problem. The only difference is the '-I /usr/share/MailScanner/perl'. Perhaps there is something there that shouldn't be there. What does 'ls -F /usr/share/MailScanner/perl' show?
```
$ ls -F /usr/share/MailScanner/perl
custom/  MailScanner/  MailScanner.pm
```

**Comment by surdet** [comment]
Thank you for your advice. I got the same output.
```
# ls -F /usr/share/MailScanner/perl
custom/  MailScanner/  MailScanner.pm
# 
# ls -l /usr/share/MailScanner/perl
total 12
drwxr-xr-x 2 root root 4096 Dec 20 15:59 custom
drwxr-xr-x 2 root root 4096 Dec 18 21:36 MailScanner
-rw-r--r-- 1 root root 1850 Aug 14  2016 MailScanner.pm
```

**Comment by msapiro** [comment]
I'm really grasping at straws, but try this. Create a file test_perl with contents
```
#!/usr/bin/perl -U -I /usr/share/MailScanner/perl
use strict;
```
Make it executable
```
chmod +x test_perl
```
and run
```
./test_perl
```
If that fails, try removing `-I /usr/share/MailScanner/perl` from the first line and run it again.

If it fails with `-I /usr/share/MailScanner/perl` and not without, there must be something in `/usr/share/MailScanner/perl` that's causing it. If it doesn't fail either way then the question becomes why does it fail only when `/usr/sbin/MailScanner` does the same thing.

**Comment by surdet** [comment]
Thank you for your help. I can run the script without any error.
```
# pwd
/root
# vi test_perl
# chmod +x test_perl
# ./test_perl
# cat test_perl
#!/usr/bin/perl -U -I /usr/share/MailScanner/perl
use strict;
#
```
I think my system has something wrong. In the past I can restart mailscanner without any error and it working fine But now if I restart mailscanner, Sometimes it working fine  and Sometimes  I found  this error,
```
May 16 06:47:55 localhost ubuntu[27057]: MailScanner restarted
May 16 06:47:55 localhost MailScanner[27054]: MailScanner Email Processor version 5.0.3 starting...
May 16 06:47:55 localhost MailScanner[27054]: Could not use Custom Function code /usr/share/MailScanner/perl/custom/MailWatch.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Can't locate Storable.pm:    /usr/share/MailScanner/perl/Storable.pm: Permission denied at /usr/share/MailScanner/perl/custom/MailWatch.pm line 25.
May 16 06:47:55 localhost MailScanner[27054]: BEGIN failed--compilation aborted at /usr/share/MailScanner/perl/custom/MailWatch.pm line 25.
May 16 06:47:55 localhost MailScanner[27054]: Compilation failed in require at /usr/share/MailScanner/perl/MailScanner/Config.pm line 752.
May 16 06:47:55 localhost MailScanner[27054]: )
```
So I reboot the system and it can run without any error.  I do not know what happened.

Thank you again for help.
