### ISSUE TITLE
Mailscanner block .cdr file.

### ISSUE THREAD

**Issue by janarzz** [MailScanner/v5#554]
Hi,
i get this error, when i send .cdr file:
MailScanner: No DOS programs allowed (5page1.dat)
How can i  allow sending .cdr files in Mailscanner ?

**Comment by msapiro** [comment]
@janarzz did you add
```
Archives: Ignore DAT File Executable = yes
```
to your configuration?

**Comment by janarzz** [comment]
Yes, but sill block.

**Comment by shawniverson** [comment]
Taking a look at the code...

**Comment by shawniverson** [comment]
Running some tests

**Comment by janarzz** [comment]
Hi,
the fix will take effect when a new version of mailscanner is released ?

**Comment by janarzz** [comment]
Hi,
i changed my Mailscanner perl conf, but still same error:
MailScanner: No DOS programs allowed (5page1.dat)

**Comment by shawniverson** [comment]
Okay, I was able to reproduce.  Event though the .dat file is skipped, the encompassing .cdr file is not skipped, it appears, and triggers the same file magic.

**Comment by janarzz** [comment]
Hi,
can i add row or change my row ?
For now i change my row to /\.(?:dat|cdr)$/), but still block.

**Comment by BlagoCuljak** [comment]
Hello, can we somehow add this fix to our version 5.4.2? We tried to change .pm file as in your PR, but we still have same problem. Restarted mailscanner.

_**MailScanner: No programs allowed (110005.dat)**_ 

https://github.com/MailScanner/v5/pull/556/files

**Comment by shawniverson** [comment]
Hello @BlagoCuljak I have held back PR #556 because I'm not convinced it is working properly. I need more testing. If you applied the PR diff yourself and am still having problems, that further enforces my concern. I need a sample of a file that is affected to isolate the problem in the PR. I am having trouble triggering it with my current samples.

**Comment by BlagoCuljak** [comment]
We revert your PR on our installation, changed:
etc/mailscanner/mailscanner.conf     changed        "Archives: Ignore DAT File Executable = "no"" to "yes"

Works now.

**Comment by shawniverson** [comment]
So when you say revert, you mean without this PR, correct?

**Comment by BlagoCuljak** [comment]
> So when you say revert, you mean without this PR, correct?

That's right. This problem was not due to cdr files, sender attached Excel, and these .dat files showed up.

**Comment by shawniverson** [comment]
That is good info and help me fix the PR for cdr and keep the dat detection working

**Comment by janarzz** [comment]
i just tried to send this file and now it works. Thanks.

**Comment by shawniverson** [comment]
Going to refactor to support user-defined extensions. Having others pop up in the wild that the executable file type fires on.
