### ISSUE TITLE
rules not being processed

### ISSUE THREAD

**Issue by Toppertje** [MailScanner/v5#57]
Hi,
I included below in the scan.messages.rules. Can the 'and' keyword be used in this ruleset as well? It doesn't seem so, but I wonder if this is by design. Same goes for MailScanner v4.
Grtz,
Ronald

From: safedomain.com and To: trusted_recipient@* no

**Comment by shawniverson** [comment]
Yeah, I think this is a limitation in the syntax.

**Comment by msapiro** [comment]
I don't know why 'and' can't be used in any ruleset. Are you using tabs to delimit the fields?

**Comment by shawniverson** [comment]
Disregard my comment, @msapiro is right.  I just reviewed the comments in EXAMPLES and it should work.
