### ISSUE TITLE
Phishing disarming is case sensitive.

### ISSUE THREAD

**Issue by msapiro** [MailScanner/v5#577]
Links are disarmed if the domain in the URL is the same as the domain in the displayed text except for case. This should not be done.

example:

You can provide your updated contact information by visiting <a href="https://www.ZoomClassAction.com/AddressUpdate"><font color="red"><b>MailScanner has detected a possible fraud attempt from "www.zoomclassaction.com" claiming to be</b></font> /www.ZoomClassAction.com/AddressUpdate</a>

MailScanner 5.4.3-1

**Comment by shawniverson** [comment]
@msapiro Feel free to test #579 and see if this resolves this issue.

**Comment by msapiro** [comment]
@shawniverson Actually, it turns out this issue is not due to mixed case. The issue I reported is spurious. The disarming is not because the display text differs in case. It is because the display text has a leading slash, i.e. `/www.ZoomClassAction.com/AddressUpdate`. If the display text is `www.ZoomClassAction.com/AddressUpdate` without the leading slash, it is not disarmed with or without #579. Thus I think #579 is unnecessary although it probably doesn't break anything, and I'm closing this issue, as I think the current behavior is acceptable. Sorry for the noise.

**Comment by shawniverson** [comment]
@msapiro Good to know. I'm going to cancel the PR. I ran some tests with the unaltered code and and seems that case sensitivity is not an issue after all.
