### ISSUE TITLE
%org-name% not overridden when using conf.d

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#578]
**Describe the bug**
%org-name% is not overridden in MailScanner.conf when a conf.d file is in use.

**Expected behavior**
%org-name% should override the default definition in MailScanner.conf without having to comment out.

**Comment by thctlo** [comment]
(TP : Peter)   MailScanner 5.4.3 on RHEl 8 with Sendmail. 

( i replied in list. )   im not seeing this problem with these versions. 
MailWatch Version: 1.2.15
Operating System Version: Debian GNU/Linux 10 (buster)
Postfix Version: 3.4.14
MailScanner Version: 5.3.4
ClamAV Version: 0.103.3
SpamAssassin Version: 3.4.2
PHP Version: 7.3.31-1~deb10u1
MySQL Version: 10.3.31-MariaDB-0+deb10u1

**Comment by thctlo** [comment]
Maybe Peter should try MailScanner Version: 5.3.4 first.

**Comment by Skywalker-11** [comment]
I think it depends if you also overwrites the config options that use the `%org-name%` inside conf.d/*. I remember that at some time it was only applied for config settings that were set after it.

**Comment by shawniverson** [comment]
That makes sense, I'm still going to investigate the issue and observe the behavior in the latest version, just in case.

**Comment by msapiro** [comment]
%org-name% is used in other settings in MailScanner.conf. You can change it in a conf.d file, but that doesn't affect the other settings from MailScanner.conf that were based on its version of %org-name%. This is documented at the beginning of MailScanner.conf
```
# However, if you are changing some variable definition which is used
# in other definitions in this file such as %org-name% in the first
# example below, you must also either change it in this file or copy
# all the definitions that use that variable into your own file.
```

**Comment by msapiro** [comment]
See http://lists.mailscanner.info/pipermail/mailscanner/2021-December/106576.html for more of my opinion on this. It may be possible to change configuration processing to defer %xxx% expansions until after all the conf.d included files are processed, but I don't think it's worth any significant effort.

**Comment by shawniverson** [comment]
Confirmed correct behavior in latest version
