### ISSUE TITLE
Please tag: v5.0.5-1

### ISSUE THREAD

**Issue by greenaar** [MailScanner/v5#58]
Can you tag v5.0.5-1 please?  (And any further changelog-worthy versions?)

**Comment by shawniverson** [comment]
Going to tag 5.0.6-1 shortly.....but not 5.0.5-1...long story...moving on...

**Comment by Skywalker-11** [comment]
Are you also going to pack 5.0.6-1 as deb/rhel package?

**Comment by shawniverson** [comment]
@Skywalker-11 In progress.  Should be posted by this coming morning :)

**Comment by Skywalker-11** [comment]
@shawniverson Any progress on packaging?

**Comment by shawniverson** [comment]
@Skywalker-11 Almost there, I found an issue that must be fixed in the debian packaging.
