### ISSUE TITLE
False positive being reported for ContactMonkey.com URLs

### ISSUE THREAD

**Issue by liamtim** [MailScanner/v5#584]
I'm unsure where else I can report this bug due to the lack of communication channels. Please let me know if I should report this elsewhere. 

**Describe the bug**

MailScanner is reporting our website as being definite fraud incorrectly:
<img width="628" alt="Screen Shot 2022-01-13 at 10 22 23 AM" src="https://user-images.githubusercontent.com/44294661/149358116-755c826e-412e-4791-b846-afd62455f450.png">

## Task
- [ ] Please add contactmonkey.com to your allowed list of URLs.

**Comment by msapiro** [comment]
The MailScanner list is built from the https://www.phishtank.com/ list. Ideally you can get them to remove any urls in the contactmonkey.com domain. Otherwise, perhaps @jcbenton can arrange for contactmonkey.com to be added to the dynamically generated http://phishing.mailscanner.info/phishing.safe.sites.conf.gz file.

**Comment by jcbenton** [comment]
It is not a bug. Some asshat scammer used your service for nefarious activity in the past, which lands that activity on phishtank.com, which then lands you on this list. Yeah, I know, not your fault ... ad hominem. 

Examples: 
http://www.phishtank.com/phish_detail.php?phish_id=7117628
http://www.phishtank.com/phish_detail.php?phish_id=7117607

I have added your domain to the safe sender list for now. Keep an eye out for abuse of your services or you will end up right back on the list.

**Comment by liamtim** [comment]
Thanks @jcbenton! Any advice on the best method to keep an eye out for abuse reports? We use AWS monitoring currently, but it's completely separate to a recipient reporting us to the likes of Phishtank

**Comment by liamtim** [comment]
@jcbenton How long does your safe sender list take to propagate to users of your software? We're still seeing our domain being flagged (as of yesterday) from recipients who are using mailscanner.

**Comment by jcbenton** [comment]
@liamtim The current list does not contain your domain. I have no control over administrators around the world using MailScanner. If they do not run the update script, then they are not going to get the updates. You need to take it up with them.
