### ISSUE TITLE
sa-update dependency `HTTP::Date` not installed by installer

### ISSUE THREAD

**Issue by RobinR1** [MailScanner/v5#588]
**Describe the bug**
After completing installation using RPM and then the `/usr/sbin/ms-configure` script I found out that `sa-update` would fail to run due to a missing dependency `HTTP::Date`. (At least on Suse) 
Possibly this library is used in other spamassassin processes, but this is the one I bumped onto.

**To Reproduce**
1. Install RPM and run configuration script `/usr/sbin/ms-configure` on a clean system
2. Configure MailScanner / spamassassin up to where spamassassin would correctly run
3. run `sa-update`
```
Can't locate HTTP/Date.pm in @INC (you may need to install the HTTP::Date module) (@INC contains: /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at /usr/bin/sa-update line 88.
BEGIN failed--compilation aborted at /usr/bin/sa-update line 88.
```

**Expected behavior**
`HTTP::Date` automatically installed by `/usr/sbin/ms-configure` and sa-update working out-of-the-box.

**Server :**
 - OS: openSuse Leap 15.3
 - Mandatory Access Control Enforcement: Apparmor
 - MailScanner Version: 5.4.3
 - OS Version: 15.3 - kernel 5.3.18-59.37-default
 - Installation method: Package
 - Installation: New
 - Containerized: No

**Additional context**
After installing it by manually running `zypper install perl-HTTP-Date`, `sa-update` runs without problem.

**Comment by msapiro** [comment]
How did you install spamassassin? Isn't this a spamassassin issue as opposed to a MailScanner issue?

**Comment by RobinR1** [comment]
Spamassassin was installed by MailScanner during the ms-configure script. At first I didn't even know it was already installed :-) (I have been using an ancient version of MailScanner set up more than 10 years ago, so I know it needed spamassassin, and was about to install it myself.. but then noticed it was pulled in by the ms-configure script.)

**Comment by msapiro** [comment]
ms-configure doesn't install Spamassassin per se. It installs the perl module `Mail::SpamAssassin` and some additional plugins. It is apparently [Mail::Spamassassin](https://metacpan.org/pod/Mail::SpamAssassin) that fails to install the dependency although I don't suppose it would hurt to have ms-configure add `HTTP::Date` to the things installed with Spamassassin, e.g. add after https://github.com/MailScanner/v5/blob/dbe2d17eef42d66ffe916a7b5cddc4821ffa1ff0/suse/usr/sbin/ms-configure#L429
```
SAMOD+=('HTTP::Date');
```

**Comment by shawniverson** [comment]
Classifying as a "bug" because we need to handle this properly when ms-configure is involved.
