### ISSUE TITLE
No programs allowed (Type is excutable) (Am Bahnhof 5.dbf)

### ISSUE THREAD

**Issue by rightvision** [MailScanner/v5#592]
Does anybody understand, why a DBF file (dBase) is marked as executable. I've already tried to enhance the filerules (application/octet-stream which should work), but no success.

allow text - -
allow \bscript - -
allow archive - -
allow postscript - -
allow application/octet-stream - -
allow application/zip - -
allow application/x-zip - -
allow application/x-gzip - -
deny self-extract No self-extracting archives No self-extracting archives allowed
deny executable No executables No programs allowed (Type is excutable)

**Comment by shawniverson** [comment]
Related to active PR WIP https://github.com/MailScanner/v5/pull/556
