### ISSUE TITLE
minor glitch concerning logging of archive unpacking

### ISSUE THREAD

**Issue by dneuhaeuser** [MailScanner/v5#615]
while investigating Mailscanner logs I observed this when an archive is unpacked:

there is always some garbage logged (1-2 characters) before the real filename.
examples:

MailScanner[596780]: Unpacked Zip archive: **n**TEST.docx

MailScanner[52058]: Unpacking 7zip archive: **n**7z1900-extra.7z
MailScanner[52058]: Unpacking RAR archive: **r**7za.dll

MailScanner[2152799]: Unpacked Zip archive: **n**ADASU AKU-GIB2022.zip
MailScanner[2152799]: Unpacking RAR archive: **z1**ADASUAKU-GIB2022.exe

**Comment by shawniverson** [comment]
This is normal. That is the Type Indicator.
