### ISSUE TITLE
Upgrade from MailScanner-5.4.5-1 to MailScanner-5.4.5-2 messages not deliverd

### ISSUE THREAD

**Issue by Hydranet** [MailScanner/v5#622]
**Describe the bug**
I upgraded from MailScanner-5.4.5-1 to MailScanner-5.4.5-2. Now when I either send a mail from my domain or receive a mail from my domain it doesn't seem to get fully processed.

**To Reproduce**
1.  Update from MailScanner-5.4.5-1 to MailScanner-5.4.5-2 
2.  Send a mail from another domain to my domain or from my domain to an another domain.

**Expected behavior**
When sending to another domain: I expect postfix to connect to mx host of another domain and deliver the mail.
When receiving from another domain: I see it being transferred to my mailserver but than postfix doesn't seem to process the mail and deliver it to the local mailbox. 

**Examples**
[example.log](https://github.com/MailScanner/v5/files/9891553/example.log)
(I attached a file with an example file with log lines from when sending to an external domain and from receiving mail from an external domain. 

**Server (please complete the following information):**
 - OS: Rocky LInux
 - Mandatory Access Control Enforcement: SELinux(I set also tried changing it to permissive mode but that didn't change anything)
 - MailScanner Version: 5.4.5-2 
 - MTA: postfix-3.5.8
 - OS Version: 8.6
 - Installation method: https://github.com/MailScanner/v5/releases (rhel rpm)
 - Installation: Upgraded 
 - Containerized: No

**Additional context**
I tried downgrading back to MailScanner-5.4.5-1 and restoring my old MailScanner.conf file but the problem even persists after downgrading. I did run " /usr/sbin/ms-configure --update" after updating and restarted mailscanner and msmilter. Before I attempted to upgrade from 5.4.5-1 to 5.4.5-2. I didn't have any issues and my setup/configuration was working as expected.  I enabled debug mode and then ran "/usr/sbin/MailScanner" as root, then it just hangs there while creating some bulk mail so I cancelled that. I also don't see any permissions problems or other errors come across in /var/log/mailllog when I restart postfix, mailscanner and msmilter.

This is my personal
 mailserver so I am currently not able to post to the mailscanner mailinglist, that's why I am posting it here

[mailscanner-configuration.log](https://github.com/MailScanner/v5/files/9891788/mailscanner-configuration.log)

**Comment by Hydranet** [comment]
The problem seems to be with the msmilter, when I remove the line "inet:localhost:33333" from my Postfix configuration and restart Postfix sendmail to an external domain from my domain and then sending mail from an external domain to my domain the mails is delivered as expected. So when I take out mailscanner/msmilter my setup/configurations works as expected.

**Comment by Hydranet** [comment]
I switched back to processing mail without milter so how it is documented [here](https://www.mailscanner.info/postfix/) and then mailscanner correctly delivers the mail again. So it definitely seems to be a problem with the msmilter.

**Comment by shawniverson** [comment]
What are the owner/permissions on your milter queues?

```
drwxrwxr-x.  2 postfix mtagroup    6 Oct 29 08:17 milterin
drwxrwxr-x.  2 postfix mtagroup    6 Oct 29 08:17 milterout
```

**Comment by Hydranet** [comment]
`[root@magik ~]# ls -l /var/spool/MailScanner | grep milter
drwxrwxr-x.  2 postfix mtagroup 4096 Oct 29 09:49 milterin
drwxrwxr-x.  2 postfix mtagroup 4096 Oct 25 21:29 milterout`

Before I upgraded to 5.4.5-2 my msmilter setup was working, after I upgraded it was broken and when I tried to downgrade back to 5.4.5-1 my msmilter setup remained broken. Could it be that one of the upgraded perl modules that was upgraded during the mailscanner upgrade process is having a problem with msmilter?

I also posted in the mailinglist about an hour ago, not sure if here or there is the better place to post?

**Comment by shawniverson** [comment]
With your detailed information, should be easy enough for me to check for something going sideways with a perl module.  I'll get a Rocky instance going and try an upgrade from the older package.

**Comment by Hydranet** [comment]
Great, if you need any more information from me just let me know. Also is there a way to see or find out what happened to all the mails that have disappeared after seeing the message "milter-discard: END-OF-MESSAGE" in the maillog. Because since when receiving they never were delivered in the mailbox and when sending they never actually where transferred to the destination mx host. So technically they should still be somewhere on the system I would think, it would be nice if the messages I missed and my test messages would still be able to get transferred correctly after having figured this out.

**Comment by shawniverson** [comment]
Well, the milter writes directly to the the `Incoming Queue Dir` as defined in MailScanner.conf.  Which should be /var/spool/MailScanner/milterin.  If this path changed for some reason is the only thing I could think that would cause them to write elsewhere.

**Comment by Hydranet** [comment]
Also it may be more appropriate to change the title of my question to  "After Upgrade from 5.4.5-1 to 5.4.5-2 msmilter seems broken", the current topic title was what I made up from before I tested different things myself.

This is what I have use for Queue dirs as how it is mentioned in your MSMilter documentation. 
```
Incoming Queue Dir = /var/spool/MailScanner/milterin
Outgoing Queue Dir = /var/spool/postfix/incoming
```
That is when I have the msmilter configuration active, currently still on HOLD method until this problem is sorted out. Selinux isn't the problem either because I tried the setup with permissive mode enable and the problem still persisted then.

**Comment by shawniverson** [comment]
Yeah, if nothing wrote to that directory (perhaps because of something wrong in a perl module), then the messages never made it to disk.

**Comment by shawniverson** [comment]
What I don't understand, though, is this...

```
 my $ret;
    $ret = MailScanner::Lock::openlock($queuehandle,'>>' . $file, 'w');
    if ($ret != 1) {
        MailScanner::Log::WarnLog("Unable to to open queue temp file for writing!");
        Sendmail::PMilter::SMFIS_TEMPFAIL;
        return;
    }
    $queuehandle->print($body_chunk);
```

How did it make it past all the error handling?

**Comment by Hydranet** [comment]
When I grep for "Unable to to open queue temp file for writing" in maillog I don't get any hits on that message either.

**Comment by shawniverson** [comment]
Yeah, if you made it to the DISCARD action no errors were thrown.

**Comment by shawniverson** [comment]
I didn't even make it to the latest and I'm having the same issue on my test box.

**Comment by shawniverson** [comment]
Even more disturbing is the jump in postfix straight to the `eom_callback` without anything else.  Which would produce nothing and generate the described behavior.  This is on postfix v3.5.8-4.

**Comment by Hydranet** [comment]
I also see that back in my maillog from the times I enabled Debug mode to see if I could see any useful debug output from MSMilter.
```
Oct 29 09:30:04 magik MSMilter[21857]: eom_callback: incoming = /var/spool/MailScanner/milterin
Oct 29 09:30:35 magik MSMilter[21857]: eom_callback: incoming = /var/spool/MailScanner/milterin
```

**Comment by Hydranet** [comment]
> I didn't even make it to the latest and I'm having the same issue on my test box.

That makes it a bug, never would have though I would be helping out by reporting a bug. I have donated to the mailscanner project in in the past but it's something different to report a bug.  So I was I correct coming to the conclusion thinking it was one of the updated perl modules not playing nice with the MSMilter?

**Comment by shawniverson** [comment]
Problem is with the following module:

Sendmail::PMilter
Version 1.21

There's an open bug at CPAN:
https://rt.cpan.org/Public/Bug/Display.html?id=144273

**Comment by shawniverson** [comment]
I'm working on figuring out what is going on here...

**Comment by shawniverson** [comment]
I reported the bug, now for the workaround (also to buy me time to study the problem with the author). Due to its severity I'm going to pull the working version of this module into the MailScanner codebase which will take priority over any version installed on the system until this is fixed permanently.

**Comment by Hydranet** [comment]
Great! Thanks so much for having responded to my issue Shawn!

I'm glad I ran into the issue so I was able to report it but it's not a good feeling knowing that I might have missed some mail and not being able to know what I missed if I missed it. Good to know it is being worked on now. Where did you report it so that I can follow along?

Does that mean you will in the future always have tested a working version of Sendmail::PMilter in the Mailscanner codebose or is that just temporary until the upstream module is fixed?

**Comment by shawniverson** [comment]
I am working with PR #623 right now. I added a failsafe to the code to protect it from the condition we encountered here so that postfix returns a temporary failure.  

I reported it here:
https://rt.cpan.org/Public/Bug/Display.html?id=144971

I'm going to sleep on it, but I may end up permanently integrating Sendmail::PMilter going forward. I may even at this point take the relevant code and roll it into MailScanner itself because milter protocols don't change much.

**Comment by shawniverson** [comment]
It will take me a little bit to test this out, once I do I'll tag the new release and let you know.

**Comment by Hydranet** [comment]
Awesome thanks for sharing the link where you reported it! I'll just keep using the Mailscanner Hold method for now until the the issue is resolved. Let me know if you need me to test anything.

**Comment by shawniverson** [comment]
Please test:

https://github.com/MailScanner/v5/releases/tag/5.4.5-3

**Comment by Hydranet** [comment]
Yes that works as expected the mails are now being processed again, when receiving they are being delivered into my mailbox and when sending they are being transferred to the receiving mta for the other domain and ending up in the mailbox for that domain as well.
```
Receiving:
Oct 29 22:00:34 magik postfix/cleanup[14401]: 08758E09FD: milter-discard: END-OF-MESSAGE from mail-ot1-f41.google.com[209.85.210.41]: milter triggers DISCARD action; from=<****@gmail.com> to=<****@feedmebits.nl> proto=ESMTP helo=<mail-ot1-f41.google.com>
Oct 29 22:00:37 magik MailScanner[14385]: New Batch: Scanning 1 messages, 3435 bytes
Oct 29 22:00:37 magik MailScanner[14385]: Virus and Content Scanning: Starting
Oct 29 22:00:42 magik MailScanner[14385]: Requeue: 08758E09FD.ABE9F to 08758E09FD.ABE9F

Sending:
Oct 29 22:02:46 magik postfix/cleanup[14463]: 0A631E09FD: milter-discard: host.example.com[1.2.3.4]: milter triggers DISCARD action; from=<****@feedmebits.nl> to=<****@outlook.com> proto=ESMTP helo=<[10.31.251.11]>
Oct 29 22:02:46 magik postfix/smtpd[14459]: disconnect from host.example.com[1.2.3.4] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Oct 29 22:02:50 magik MailScanner[14381]: New Batch: Scanning 1 messages, 1525 bytes
Oct 29 22:02:50 magik MailScanner[14381]: Virus and Content Scanning: Starting
Oct 29 22:02:55 magik MailScanner[14381]: Requeue: 0A631E09FD.A1A89 to 0A631E09FD.A1A89
```

**Comment by shawniverson** [comment]
I'll keep a close eye on this and keep the working copy of the perl module in this and future releases until I either do away with it entirely or come to a consensus with the author on a fix.

**Comment by Hydranet** [comment]
Thanks a lot for the fix!  I have been using Mailscanner since I setup my own personal mailserver and I've been using the MSMilter since you first released it. Can I ask you one question, which I have always wanted an answer to when it comes to Mailscanner and Postfix?

**Comment by Hydranet** [comment]
I've looked at different opensource anti-spam solutions mailscanner and amavisd-new always stood out as the better solutions from what is listed on the [Postfix Addon-page](https://www.postfix.org/addon.html) 
`mailscanner system, works with Postfix and other MTAs. WARNING: This software uses unsupported methods to manipulate Postfix queue files directly. This will result in corruption or loss of mail. The mailscanner authors have sofar refused to discuss a proper access API or protocol.
`
But what's the deal with the Postfix project not recommending Mailscanner? While from my experience Mailscanner has always just worked perfectly fine and and it's way easier to configure then amavisd-new and all the other anti-spam solutions listed on that page.

**Comment by shawniverson** [comment]
That warning relates specifically to the HOLD method.  They don't support talking directly to the Postfix queues.  The Milter is a Postfix API compliant way to do this without directly manipulating the postfix queues, but as you witnessed today, it had a problem that needed fixed quickly.

**Comment by Hydranet** [comment]
Before the MSMilter came out I never experienced any issues with the HOLD method either. However it's nice to have the option to be able to use the MSMilter now because that warning has caused me with questions marks in the back of my head even though I've had no bad experiences with the HOLD method.  All software can break when updated or the dependencies are updated, so it's a general thing when it comes to updating and improving software.

Thanks again so much for fixing the MSMilter!! Are you going to keep this issue open or wait till the issue of the upstream Perl module is fixed as well?

**Comment by shawniverson** [comment]
I think we should keep this issue open if you are okay with that.

**Comment by Hydranet** [comment]
Yes that is fine with me.

**Comment by msapiro** [comment]
I agree that we should keep it open to track the situation with Sendmail::PMilter.

I have upgraded to 5.4.5-3 which seems OK so far although this wasn't actually an issue for me as my servers run Ubuntu 20.04 and it's version of libsendmail-pmilter-perl is 1.00-1.

Also FYI, I emailed wietse@porcupine.org and asked him to remove the warning from the [Postfix Addon-page](https://www.postfix.org/addon.html) as it's no longer applicable.

**Comment by shawniverson** [comment]
@msapiro Thanks! I emailed him once before, hopefully he helps us out.  Also, this release will protect you in case upstream Ubuntu releases the updated perl module without our knowledge.

**Comment by Hydranet** [comment]
Looks like Wietse updated the warning.
`MailScanner system, works with Postfix and other MTAs. Note: **MailScanner versions before 5.1** use unsupported methods to manipulate Postfix queue files directly, and can result in corruption or loss of mail.`

**Comment by shawniverson** [comment]
Version 1.23 of Sendmail::PMilter with modified code to address the issue has been released. I'll be testing it out before we return to using the upstream code.

**Comment by Hydranet** [comment]
So you will be going back to upstream code of the Sendmail::PMilter module if it has been fixed there?

**Comment by shawniverson** [comment]
Yes, now that we have a failsafe check we should be good to proceed if the code checks out.

**Comment by shawniverson** [comment]
If we didn't write anything to disk (file not present) we will return a TEMPFAIL to the sender, which will trigger them to hold off on sending the emails again, preventing loss.

**Comment by Hydranet** [comment]
Now that is happened once I am still a bit worried it could happen again in the future. Good to know the fail-safe is kept in place in case upstream breaks.

**Comment by shawniverson** [comment]
Code is working upstream, going to drop local copy of module for next release.
