### ISSUE TITLE
No-ASCII character in email header

### ISSUE THREAD

**Issue by bukowski12** [MailScanner/v5#626]
Some servers which use Amavis denied emails from my server wit error
amavis[838601]: (838601-16) check_header: 2, Non-encoded non-ASCII data (and not UTF-8) (char E1 hex): Received: Header encoded (all-ASCII): X-Amavis-Alert: BAD HEADER SECTION, Non-encoded non-ASCII data (and not UTF-8)

I found that header in email  contain non-ASCII characters and specifically is it czech day in date  (Pá, Čt...)

Received: from mail.example.cz ([192.168.16.10] [192.168.16.10]) (no client certificate requested) by mail.example.cz (MailScanner Milter) with SMTP id 3F1D43402B2 for test@volny.cz; Pá, 18 lis 2022 13:17:30 +0100 (CET)

Its this code in MSMilter:

sub header_callback
{
    ...
    my $datestring = strftime "%a, %e %b %Y %T %z (%Z)", localtime;
    ...
}

What is best solution?

**Comment by shawniverson** [comment]
We probably need to override the locale in this perl
```
use POSIX qw(setlocale strftime);
setlocale(POSIX::LC_ALL,'en_US.utf8');
```

**Comment by shawniverson** [comment]
Preparing PR

**Comment by shawniverson** [comment]
@bukowski12 Can you try this PR?

**Comment by bukowski12** [comment]
Doesnt  work, still czech day in datestamp. I have version 5.3.3 but it doesnt matter i hope.

**Comment by shawniverson** [comment]
That must mean that `localtime` doesn't honor the locale override.  Doing some research on this.

**Comment by shawniverson** [comment]
@bukowski12 I made an adjustment to the PR, please try again and restart msmilter.

**Comment by bukowski12** [comment]
Same problem.

**Comment by shawniverson** [comment]
Yeah, same here, it is like it is completely ignored. Tried multiple different functions.

**Comment by shawniverson** [comment]
I may have to build our own or find a similar non-localized function.

**Comment by shawniverson** [comment]
Okay, I may have one, going to redo the PR and rebase.

**Comment by shawniverson** [comment]
@bukowski12 This one uses DateTime, which, according to the perl docs, defaults to en_US.  Give it a try.

**Comment by bukowski12** [comment]
Problem, msmilter doesnt work:
Nov 22 10:10:48 mail-ul postfix/cleanup[3998699]: 647AE3401F7: milter-reject: END-OF-MESSAGE from unknown[192.168.16.220]: 4.7.1 Service unavailable - try again later;

**Comment by shawniverson** [comment]
Apologies, I'm probably going to have to define $tz inside the callback.  Fixing.

**Comment by shawniverson** [comment]
@bukowski12 I moved the $tz into the header_callback in the PR, that should resolve the issue. Since these are callbacks the global variable didn't get set.

**Comment by bukowski12** [comment]
It works! Thanks.
