### ISSUE TITLE
milter: textbody with colons interpreted as headerlines!?

### ISSUE THREAD

**Issue by dneuhaeuser** [MailScanner/v5#640]
I'm using mailscanner v5.4.5-3 in milter mode.

When receiving certain emails from a webform the textbody is missing some lines which contain colons.
Milter sends these lines to my downstream server as headers.

Example of incoming mail:

```
Received: [...]
To: <info@here.com>
Subject: Webform
X-PHP-Originating-Script: 1052:PHPMailer.php
Date: Tue, 14 Feb 2023 11:53:41 +0000
From: <web@domain.com>
Reply-To: <customer@there.com>
X-Mailer: PHPMailer 6.6.5 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Name: Test Test
E-Mail: email@domain.com

Here is the text...
```

After mailscanner/milter handling this arrives on downstream server like this:

```
Received: [...]
To: <info@here.com>
Subject: Webform
X-PHP-Originating-Script: 1052:PHPMailer.php
Date: Tue, 14 Feb 2023 11:53:41 +0000
From: <web@domain.com>
Reply-To: <customer@there.com>
X-Mailer: PHPMailer 6.6.5 (https://github.com/PHPMailer/PHPMailer)
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 8bit
Name: Test Test
E-Mail: email@domain.com
MIME-Version: 1.0

Here is the text...
```

The lines with "Name:" and "E-Mail:" are now in the headers.

**Comment by shawniverson** [comment]
Is this another example of `Sign Clean Messages` dropping the newline at the end of the header, by chance?

**Comment by dneuhaeuser** [comment]
Indeed this is the same problem as in #638.
I did not see that at first. Thought the other issue only had to do with the MIME boundaries.

With **Sign Clean Messages = no** the problem is not occuring.

**Comment by shawniverson** [comment]
Hopefully this fixes it:

https://github.com/MailScanner/v5/pull/642

**Comment by dneuhaeuser** [comment]
I'll give this a try and come back to you soon...

**Comment by shawniverson** [comment]
Try the new PR please.  It hopefully will fix both this issue and the other. I found the spot where the newline was being left out.

**Comment by dneuhaeuser** [comment]
I can confirm that #650 solves this issue.
Thank you!
