### ISSUE TITLE
MailScanner crashes after scanning attachment by av

### ISSUE THREAD

**Issue by hamidmdh** [MailScanner/v5#660]
**Describe the bug**
When we send malware via email, MailScanner crashes after scanning the AV file and deleting the file.

**Expected behavior**
Sender and receiver should be notified that the file is infected and blocked

**Log**
May 13 15:17:17 myscanner MailScanner[15194]: Virus and Content Scanning: Starting
May 13 15:17:17 myscanner MailScanner[15194]: GenericScanner::
May 13 15:17:17 myscanner MailScanner[15194]: GenericScanner::INFECTED::Trojan.HTML.Phishing.HSBC.67990133::/var/spool/MailScanner/incoming/15194/./55D296E09D.A1512/ne2133b91-sample.html
May 13 15:17:17 myscanner MailScanner[15194]: GenericScanner::-----------------------------------------------------------------------
May 13 15:17:17 myscanner MailScanner[15194]: GenericScanner::Final scan Result: total scanned files: 4, total infected files: 1
May 13 15:17:17 myscanner MailScanner[15194]: GenericScanner::
May 13 15:17:17 myscanner MailScanner[15194]: Virus Scanning: myScanner found 5 infections
May 13 15:17:17 myscanner MailScanner[15194]: Virus Scanning: Found 5 viruses
May 13 15:17:17 myscanner MailScanner[15245]: **MailScanner Email Processor version 5.1.3 starting...**
May 13 15:17:17 myscanner MailScanner[15245]: **Reading configuration file /etc/MailScanner/MailScanner.conf**
May 13 15:17:17 myscanner MailScanner[15245]: **Reading configuration file /etc/MailScanner/conf.d/README**
May 13 15:17:17 myscanner MailScanner[15245]: **Read 1500 hostnames from the phishing whitelist**
May 13 15:17:18 myscanner MailScanner[15245]: **Read 47813 hostnames from the phishing blacklists**
May 13 15:17:18 myscanner MailScanner[15245]: **Using SpamAssassin results cache**
May 13 15:17:18 myscanner MailScanner[15245]: **Connected to SpamAssassin cache database**
May 13 15:17:18 myscanner MailScanner[15245]: **Enabling SpamAssassin auto-whitelist functionality...**
May 13 15:17:25 myscanner MailScanner[15245]: **Connected to Processing Attempts Database**
May 13 15:17:25 myscanner MailScanner[15245]: **Found 5 messages in the Processing Attempts Database**
May 13 15:17:25 myscanner MailScanner[15245]: **Using locktype = flock**

**Comment by shawniverson** [comment]
@hamidmdh Can you share more information about this GenericScanner called myScanner?

**Comment by shawniverson** [comment]
Closing due to lack of feedback regarding this GenericScanner instance.
