### ISSUE TITLE
date: invalid date error when running MailScanner --lint

### ISSUE THREAD

**Issue by gordoncolyn** [MailScanner/v5#664]
When running MailScanner --lint I get the following errors and esetsefs does not give a result at the end of the errors;

Output below;
There are 18 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = esetsefs clamd"
Found these virus scanners installed: esetsefs, clamd
===========================================================================
Virus and Content Scanning: Starting
date: invalid date ‘28/03/2023 12:55:34’
/usr/lib/MailScanner/wrapper/esetsefs-wrapper: line 53: [: -ge: unary operator expected
date: invalid date ‘28/03/2023 12:58:36’
/usr/lib/MailScanner/wrapper/esetsefs-wrapper: line 53: [: -ge: unary operator expected
date: invalid date ‘28/05/2023 19:24:04’
/usr/lib/MailScanner/wrapper/esetsefs-wrapper: line 53: [: -ge: unary operator expected
Clamd::ERROR:: Can't open file or directory ERROR :: ./1/neicar.com
Clamd::INFECTED::Win.Test.EICAR_HDB-1 :: ./1/
Virus Scanning: Clamd found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses
===========================================================================

**To Reproduce**
MailScanner --lint on command line

**Expected behavior**
There are 34 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = esetsefs clamd"
Found these virus scanners installed: esetsefs, clamd
===========================================================================
Virus and Content Scanning: Starting
Esets::INFECTED::Eicar
Virus Scanning: esetsefs found 1 infections
Clamd::INFECTED::Win.Test.EICAR_HDB-1 :: ./1/
Clamd::INFECTED:: Win.Test.EICAR_HDB-1 :: ./1/eicar.com
Virus Scanning: Clamd found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 3 viruses
===========================================================================
Virus Scanner test reports:
Esets said "found Eicar in eicar.com"
Clamd said "eicar.com was infected: Win.Test.EICAR_HDB-1"

**Server (please complete the following information):**
 - OS: Rocky Linux 8.8
 - Mandatory Access Control Enforcement: none
 - MailScanner Version: 5.4.4-1
 - OS Version: Linux version 4.18.0-477.10.1.el8_8.x86_64 (mockbuild@iad1-prod-build001.bld.equ.rockylinux.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-18) (GCC)) #1 SMP Tue May 16 11:38:37 UTC 2023
 - Installation method: Package - MailScanner-5.4.4-1.rhel.noarch.rpm
 - Installation: New
 - Containerized: No

**Additional context**
This error did not show on intial install, it seemed to only show up after patching, but I cannot tell when....

**Comment by shawniverson** [comment]
@gordoncolyn Take a look at /usr/lib/MailScanner/esetefs-wrapper and adjust the DATEORDER variable as follows.

`DATEORDER='%d %m %Y'`
