### ISSUE TITLE
False Positive Fraud

### ISSUE THREAD

**Issue by moxsmaastricht** [MailScanner/v5#669]
Since a few months we are using Postmarkapp for sending our bi-weekly newsletter to members of [www.ureaknowhow.com](http://www.ureaknowhow.com/). 

In the last post of 15 september one of our members, who apparently is using your software for scanning incoming messages, got a 'suspected fraud' message from Mailscanner. 

Sender is [mark.brouwer@ureaknowhow.com](mailto:mark.brouwer@ureaknowhow.com)
Subject Bi-weekly UreaKnowHow.com Technical Paper 15 September 2023

We would appreciate if you could have a look at this issue. I will paste a part of the message our member sent to us below

Thank you and kind regards
Roger van Montfort

a%2F2023-09-15.html/-g_p/e-2vAQ/AQ/66737b09-4b63-458a-b050-0197f5664461/1/N= DbEeF3Iw4">MailScanner has detected definite fraud i= n the website at "[click.pstmrk.it](http://click.pstmrk.it/)". Do not trust this website: click here if this newsletter is unreadable
=20

MailScanner has detected definite fraud in the website at "[click.pstmrk.it](http://click.pstmrk.it/)= ". Do not trust this website:

Bi-weekly UreaK= nowHow.com Technical Paper 15 September 2023 =20=20=20=20

<= div align=3D"right">September 15, 2023

**Comment by shawniverson** [comment]
MailScanner admins can override the phishing bad sites list locally by editing phishing.safe.sites.custom.  Contact the admins of the affected receiving domains.
