### ISSUE TITLE
ms-init hanging

### ISSUE THREAD

**Issue by fwittekind4** [MailScanner/v5#67]
After installing MailScanner on CentOS 7, had multiple cases of ms-init hanging with MailScanner not running, I traced the issue down to this statement:

while (ps axww | grep -q '[M]ailScanner'); do

Should be:

while (ps axww | grep -q '[M]ailScanner': ); do

If it is missing the ":" then, the grep picks up on the ms-init process itself.
[root@censored ~]# ps axww | grep '[M]ailScanner'
24087 ? SN 0:46 /bin/bash /usr/lib/MailScanner/init/ms-init restart

There are multiple cases in ms-init of the grep statement missing the colon.

**Comment by shawniverson** [comment]
Confirmed.  Preparing fix.

**Comment by shawniverson** [comment]
Fixed in commit ed70848cb3ddcd66672e4f2253026aaf97b60c5c
