### ISSUE TITLE
Domain False Positives

### ISSUE THREAD

**Issue by FalconerTC** [MailScanner/v5#674]
**Describe the bug**
We have the following domains in http://phishing.mailscanner.info/phishing.bad.sites.conf
`bio.to`
`lnkfi.re`
These belong to Linkfire (https://linkfire.com/) which offers a service for creating "smart links", primarily for enabling musicians to link to released works on different streaming platforms.

I see the following have been identified
https://www.phishtank.com/phish_detail.php?phish_id=8396824
https://www.phishtank.com/phish_detail.php?phish_id=8393186

Both of these are links that have been removed as we maintain our product. I realize that these domains are marked by PhishTank and MailScanner just ingests that, but PhishTank doesn't allow new user registrations and I see you have been able to fix false-positives with PhishTank in the past. Can you assist here?

**Comment by shawniverson** [comment]
MailScanner admins can override the phishing bad sites list locally by editing phishing.safe.sites.custom.  Contact the admins of the affected receiving domains.
