### ISSUE TITLE
MailScanner v5.4.5-3 not starting on SuSE Linux Enterprise Server 15 SP4

### ISSUE THREAD

**Issue by ChiquitoDiego** [MailScanner/v5#684]
**Describe the bug**
MailScanner v5.4.5-3 does not start on SuSE Linux Enterprise Server 15 SP4

**To Reproduce**
1. Install MailScanner v5.4.5-3 downloaded from https://github.com/MailScanner/v5/releases/download/5.5.1-4/MailScanner-5.5.1-4.suse.noarch.rpm
2. systemctl start mailscanner
3. Error:

┌──(root☠kingof - Wed Mar 06 16:16 )-[/etc/postfix]
└─# systemctl start mailscanner
Job for mailscanner.service failed because the control process exited with error code.
See "systemctl status mailscanner.service" and "journalctl -xeu mailscanner.service" for details.

┌──(root☠kingof - Wed Mar 06 16:16 )-[/etc/postfix]
└─# systemctl status mailscanner.service 
× mailscanner.service - LSB: MailScanner daemon
     Loaded: loaded (/usr/lib/MailScanner/init/ms-init; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2024-03-06 16:16:13 CET; 4s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 22182 ExecStart=/usr/lib/MailScanner/init/ms-init start (code=exited, status=1/FAILURE)

Mar 06 16:16:11 kingof systemd[1]: Starting LSB: MailScanner daemon...
Mar 06 16:16:12 kingof ms-init[22182]: MailScanner starting ...
Mar 06 16:16:13 kingof ms-init[22758]: Can't locate Filesys/Df.pm in @INC (you may need to install the Filesys::Df module) (@INC contains: /usr/share/MailScanner/perl  /usr/share/MailScanner/perl /usr/lib/perl5>
Mar 06 16:16:13 kingof ms-init[22758]: BEGIN failed--compilation aborted at /usr/sbin/MailScanner line 88.
Mar 06 16:16:13 kingof root[22759]: MailScanner failed to start
Mar 06 16:16:13 kingof root[22760]: Found a possible dead PID. Stopping all MailScanner rogue processes ...
Mar 06 16:16:13 kingof systemd[1]: mailscanner.service: Control process exited, code=exited, status=1/FAILURE
Mar 06 16:16:13 kingof systemd[1]: mailscanner.service: Failed with result 'exit-code'.
Mar 06 16:16:13 kingof systemd[1]: Failed to start LSB: MailScanner daemon.

**Comment by shawniverson** [comment]
@ChiquitoDiego Did you run ms-configure to install the required perl modules?

**Comment by ChiquitoDiego** [comment]
@shawniverson Thanks a lot Shawn. I forgot to run /usr/sbin/ms-configure :-( My fault. MS is now installed and configured on SLES 15 SP4 :-) All the best !
