### ISSUE TITLE
False positive domain - google.com

### ISSUE THREAD

**Issue by andreanousr** [MailScanner/v5#686]
In your blacklist http://phishing.mailscanner.info/phishing.bad.sites.conf there is the google.com domain. Please check and fix it.

**Comment by jschenke488** [comment]
Can confirm, google.com is blocked

**Comment by msapiro** [comment]
Yes, google.com and many other google domains are listed in phishing.bad.sites.conf, but they are also listed in phishing.safe.sites.conf which should override the phishing.bad.sites.conf listing.

**Comment by shawniverson** [comment]
```
grep google\.com /etc/MailScanner/phishing.safe.sites.conf
*.google.com
*.google.com.hk
*.google.com.tw
*.google.com.mx
*.google.com.tr
*.google.com.sa
*.google.com.br
*.google.com.au
*.google.com.eg
*.google.com.ar
*.google.com.vn
*.google.com.ua
*.google.com.pk
*.google.com.pe
```

**Comment by shawniverson** [comment]
Safe sites should override any in the blocked list.

**Comment by shawniverson** [comment]
Double checked and confirmed that safe sites list is overriding, with phishing detection enabled.

![image](https://github.com/user-attachments/assets/96956b52-ca3b-45bc-af4f-04f7da0d6bc0)
