### ISSUE TITLE
ms-update-phishing: URLs are "301 Moved Permanently"

### ISSUE THREAD

**Issue by dneuhaeuser** [MailScanner/v5#694]
**/usr/sbin/ms-update-phishing** cannot download the phishing site updates anymore.

Apparently something changed on the website and the **http** URLs are now redirected to **https**.

With curl in use, this redirect is not followed.
The downloaded files **phishing.bad.sites.conf.master.gz** and **phishing.safe.sites.conf.master.gz**
only contain the message "**301 Moved Permanently**"

Should we update the URLs to https, like so?
```
BADURL='https://phishing.mailscanner.info/phishing.bad.sites.conf.gz';
SAFEURL='https://phishing.mailscanner.info/phishing.safe.sites.conf.gz';
```

And/or should we include the '**-L**' parameter in the curl commands to follow further redirects which might come in the future?

**Comment by mikaku** [comment]
I'm also experiencing the same.
The contents of the file `/etc/MailScanner/phishing.bad.sites.conf.master.gz` is:

```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

**Comment by shawniverson** [comment]
PR #695 going to merge this.

**Comment by jcbenton** [comment]
I corrected the config on the web server that was forcing https. It will now accept http connections. However, you should update your script to use https. I have also updated the cron download on the phishing website with the https pointers.

**Comment by shawniverson** [comment]
v5.5.3-1 contains PR #695.  Going to leave this issue open for a couple days for everyone.
