### ISSUE TITLE
Automate install script.

### ISSUE THREAD

**Issue by greenaar** [MailScanner/v5#73]
The install script is a solid piece of work.

It could use an 'auto' mode, where you specify params on the commandline or via a config file.  That would make it more automate-able.

With that in mind, making it idempotent would be good too (Ie, to let you install/update dependecies only, or to reinstall just the base package).

Strictly nice-to-haves, but they are the difference between 'i can use this in my configuration management flow' and 'I'll have to write something that does the same thing, but without prompts'

**Comment by jcbenton** [comment]
Glad someone noticed. A lot of work went into that.

If you have a modification, you can submit it and we could review it for inclusion.

**Comment by greenaar** [comment]
Fair enough. I'll think on it a bit and see what I can come up with.

**Comment by Skywalker-11** [comment]
At MailWatch we use a bash function to check if a variable is not set or is empty. If that is the case we ask the user for the specified option. First parameter is the text that should be displayed to the user if he has to make an input:
```
function ask() {
    message="$1"
    var="$2"
    if [ -z "${!var}" ]; then
        read -r -p "$message" "$var"
    else
        logprint "$var set by setup-config. Using that value"
    fi
}
```
You can call it like `ask "Enter text that should be displayed to user here [y/n/....]" variableToUse`
If all the user options have their corresponding variable set you can run the script unattended.
see [https://github.com/mailwatch/mailwatch-install-script/tree/develop](https://github.com/mailwatch/mailwatch-install-script/tree/develop)

**Comment by endelwar** [comment]
I have some work in progress debian install script for automated install, I'm going to post it as PR for comment.

**Comment by endelwar** [comment]
Here is the PR https://github.com/MailScanner/v5/pull/75, comments are very welcome!

**Comment by shawniverson** [comment]
Todo:  

Same thing for other OSes....

**Comment by shawniverson** [comment]
Some perl module compiles throwing prompts....look into this

**Comment by endelwar** [comment]
@shawniverson I managed to suppress them with App::cpanminus, specially with spamassassin install that asks for CONTACT_ADDRESS prompt

**Comment by Skywalker-11** [comment]
It would be nice if we can also make a parameter `--update` which takes the parameters from the conf files and doesn't require any additional parameters.
