### ISSUE TITLE
Phishing Update Script - Service restart

### ISSUE THREAD

**Issue by jcbenton** [MailScanner/v5#82]
The restart portion of the script needs to check for more than /etc/init.d/mailscanner because a true systemd implementation does not create this file.

**Comment by thomvanderboon** [comment]
I have added systemd support for this script in a new version (0,2,0). Currently testing it on various systems (Centos 6, Centos 7 and Ubuntu). Should be available for public testing in a couple of days

**Comment by shawniverson** [comment]
Thanks @thomvanderboon.  I can say that the phishing update itself otherwise works very well across multiple platforms :)

**Comment by jcbenton** [comment]
Thanks Thom. Let me know when the new version gets publish so I can put it on the phishing website. We can also do another minor version release of the entire package if you like.
