### ISSUE TITLE
clamav-wrapper permissions

### ISSUE THREAD

**Issue by gregh3269** [MailScanner/v5#95]
I use mailwatch and to make the clamAV status work consistently the folder /var/spool/MailScanner/incoming/clamav-tmp needs to have the correct ownership.  It would be better to clean up after running the wrapper, ie to also delete the parent directory.

Debugging, for me :

${TempDir}  == /var/spool/MailScanner/incoming/clamav-tmp/tmp.M4rmuXQ38A: Is a directory
${IWD} == /var/spool/MailScanner/incoming/clamav-tmp: Is a directory

rm -rf ${TempDir}
rm -rf ${IWD}

 v5/common/usr/lib/MailScanner/wrapper/clamav-wrapper 

Cheers

**Comment by Skywalker-11** [comment]
@gregh3269 The problem is that you can have multiple MailScanner threads running which simultaneously are scanning mails with ClamAV. If one of them finishes you can't simply delete the ${IWD} folder as that would also effect the other thread.

**Comment by gregh3269** [comment]
Checking clamav-tmp, the default user is postfix, group postfix.  mailwatch runs as apache for me.  I can add apache to the postfix group but, but the default for the folder clamav-tmp postfix group is none.

I guess that the group cannot be set easily to create and delete?

Cheers Greg

**Comment by shawniverson** [comment]
@gregh3269 Are you using the newest MailScanner?  MailScanner has a new group called mtagroup that takes care of issues such as this.  You would add clamav to this group and ensure that clamav-tmp has the same group assigned, as well as the MailScanner config/daemon.

**Comment by gregh3269** [comment]
Checking, mtagroup group has clamscan, mail and postfix, but the php call to the clamav-wrapper uses the user that runs the web server, for me apache,  adding clamav to mtagroup wont help.

The clamav-tmp has group postfix access *none* (centos 7).  Create and delete would help. 

Best to close this request as the new version seems wip.

Cheers Greg
