### ISSUE TITLE
Broken link in comments in MailScanner.conf

### ISSUE THREAD

**Issue by msapiro** [MailScanner/v5#97]
There are a few links in comments in MailScanner.conf and in config.index/conf_array.php to http://www.mailscanner.info/mcp.html, http://www.mailscanner.info/mcp.html#patches and http://www.mailscanner.info/mcp.htmlpatches (sic). http://www.mailscanner.info/mcp.html no longer exists. It should either be restored or the links removed or possibly linked to the wayback machine at https://web.archive.org/web/20150323143115/http://www.mailscanner.info/mcp.html.

**Comment by shawniverson** [comment]
@jcbenton What are your thoughts?  Should we restore these pages or perhaps link to wayback?

**Comment by jcbenton** [comment]
The way back thing is a good idea.

**Comment by shawniverson** [comment]
Thanks @jcbenton .
